import { createModuleManifest, MODULE_KINDS } from "@atlas/core";

export const contactsMap = createModuleManifest({
  key: "atlas.contacts",
  name: "Contactos",
  description: "Clientes, proveedores, personas y empresas.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "ContactRound",
  color: "#0ea5e9",
  category: "operaciones",
  summary: "Clientes, proveedores, personas y empresas",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Contact"],
    sharedEntities: ["Company", "AuditLog"],
  },
  navigation: [
    {
      label: "Contactos",
      path: "/contacts",
      icon: "Contact",
      layout: "main",
      permissionKey: "contacts.contacts.read",
    },
  ],
  permissions: [
    { key: "contacts.access", name: "Access Contacts" },
    { key: "contacts.contacts.read", name: "Read Contacts Feature" },
    { key: "contacts.contacts.create", name: "Create Contacts Feature" },
    { key: "contacts.contacts.update", name: "Update Contacts Feature" },
    { key: "contacts.contacts.delete", name: "Delete Contacts Feature" },
  ],
  exposes: {
    contactPicker: true,
    getContactById: true,
  },
  acl: {
    module: "contacts.access",
    actions: {
      "contacts.contacts.read": "contacts.contacts.read",
      "contacts.contacts.create": "contacts.contacts.create",
      "contacts.contacts.update": "contacts.contacts.update",
      "contacts.contacts.delete": "contacts.contacts.delete",
      "contacts.list": "contacts.contacts.read",
      "contacts.picker": "contacts.contacts.read",
      "contacts.enabled": "contacts.contacts.update",
    },
    models: {
      Contact: {
        read: "contacts.contacts.read",
        create: "contacts.contacts.create",
        update: "contacts.contacts.update",
        delete: "contacts.contacts.delete",
      },
    },
  },
  blueprints: [
    {
      key: "contacts.contact.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Contact",
        label: "Contacto",
        fields: [
          {
            name: "type",
            label: "Tipo",
            type: "select",
            options: ["customer", "supplier", "person", "company"],
            required: true,
          },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "legalName", label: "Nombre legal", type: "text" },
          { name: "email", label: "Correo", type: "email" },
          { name: "phone", label: "Telefono", type: "phone" },
          { name: "taxId", label: "RFC / Tax ID", type: "text" },
          {
            name: "notesMarkdown",
            label: "Observaciones",
            type: "markdown",
            maxLength: 5000,
          },
        ],
        table: { columns: ["type", "name", "email", "phone", "taxId"] },
      },
    },
  ],
});

export const hrMap = createModuleManifest({
  key: "atlas.hr",
  name: "Recursos Humanos",
  description: "Colaboradores, notas internas y expedientes.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "UsersRound",
  color: "#2563eb",
  category: "operaciones",
  summary: "Gestión de personal y expediente",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files", optional: true }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["HrEmployee", "HrDepartment", "HrJobTitle"],
    sharedEntities: ["Company", "UserProfile", "FileAsset", "AuditLog"],
  },
  navigation: [
    {
      label: "Colaboradores",
      path: "/hr/employees",
      icon: "Users",
      layout: "main",
      permissionKey: "hr.employee.read",
    },
    {
      label: "Organigrama",
      path: "/hr/org-chart",
      icon: "Network",
      layout: "main",
      permissionKey: "hr.org_chart.read",
    },
    {
      label: "Catálogos",
      path: "/hr/catalogs",
      icon: "BookOpen",
      layout: "main",
      permissionKey: "hr.department.read",
    },
  ],
  permissions: [
    { key: "hr.access", name: "Access HR" },
    { key: "hr.employee.read", name: "Read HR Employees" },
    { key: "hr.employee.create", name: "Create HR Employees" },
    { key: "hr.employee.update", name: "Update HR Employees" },
    { key: "hr.employee.delete", name: "Delete HR Employees" },
    { key: "hr.department.read", name: "Read HR Departments" },
    { key: "hr.department.create", name: "Create HR Departments" },
    { key: "hr.department.update", name: "Update HR Departments" },
    { key: "hr.department.delete", name: "Delete HR Departments" },
    { key: "hr.job_title.read", name: "Read HR Job Titles" },
    { key: "hr.job_title.create", name: "Create HR Job Titles" },
    { key: "hr.job_title.update", name: "Update HR Job Titles" },
    { key: "hr.job_title.delete", name: "Delete HR Job Titles" },
    { key: "hr.org_chart.read", name: "Read HR Org Chart" },
    { key: "hr.org_chart.create", name: "Create HR Org Chart" },
    { key: "hr.org_chart.update", name: "Update HR Org Chart" },
    { key: "hr.org_chart.delete", name: "Delete HR Org Chart" },
  ],
  acl: {
    module: "hr.access",
    actions: {
      "hr.employee.read": "hr.employee.read",
      "hr.employee.create": "hr.employee.create",
      "hr.employee.update": "hr.employee.update",
      "hr.employee.delete": "hr.employee.delete",
      "hr.employee.enable": "hr.employee.update",
      "hr.employee.disable": "hr.employee.update",
      "hr.employee.file.attach": "hr.employee.update",
      "hr.employee.file.delete": "hr.employee.update",
      "hr.department.read": "hr.department.read",
      "hr.department.create": "hr.department.create",
      "hr.department.update": "hr.department.update",
      "hr.department.delete": "hr.department.delete",
      "hr.job_title.read": "hr.job_title.read",
      "hr.job_title.create": "hr.job_title.create",
      "hr.job_title.update": "hr.job_title.update",
      "hr.job_title.delete": "hr.job_title.delete",
      "hr.org_chart.read": "hr.org_chart.read",
      "hr.org_chart.create": "hr.org_chart.create",
      "hr.org_chart.update": "hr.org_chart.update",
      "hr.org_chart.delete": "hr.org_chart.delete",
    },
    models: {
      HrEmployee: {
        read: "hr.employee.read",
        create: "hr.employee.create",
        update: "hr.employee.update",
        delete: "hr.employee.delete",
      },
      HrDepartment: {
        read: "hr.department.read",
        create: "hr.department.create",
        update: "hr.department.update",
        delete: "hr.department.delete",
      },
      HrJobTitle: {
        read: "hr.job_title.read",
        create: "hr.job_title.create",
        update: "hr.job_title.update",
        delete: "hr.job_title.delete",
      },
    },
  },
  blueprints: [
    {
      key: "hr.employee.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "HrEmployee",
        label: "Colaborador",
        fields: [
          { name: "employeeCode", label: "Codigo", type: "text" },
          { name: "userProfileId", label: "Cuenta de usuario", type: "text" },
          { name: "firstName", label: "Nombre", type: "text", required: true },
          {
            name: "lastName",
            label: "Apellidos",
            type: "text",
            required: true,
          },
          { name: "workEmail", label: "Correo laboral", type: "email" },
          { name: "personalEmail", label: "Correo personal", type: "email" },
          { name: "phone", label: "Teléfono", type: "phone" },
          {
            name: "emergencyContactName",
            label: "Contacto de emergencia",
            type: "text",
          },
          {
            name: "emergencyContactPhone",
            label: "Telefono de emergencia",
            type: "phone",
          },
          { name: "jobTitle", label: "Puesto", type: "text" },
          { name: "department", label: "Departamento", type: "text" },
          { name: "managerName", label: "Supervisor", type: "text" },
          {
            name: "employmentType",
            label: "Tipo de empleo",
            type: "select",
            options: ["full_time", "part_time", "contractor", "intern"],
          },
          { name: "workLocation", label: "Ubicacion de trabajo", type: "text" },
          { name: "terminationDate", label: "Fecha de baja", type: "text" },
          {
            name: "status",
            label: "Estado",
            type: "select",
            options: ["active", "inactive", "vacation", "terminated"],
            required: true,
          },
          { name: "notesMarkdown", label: "Notas", type: "markdown" },
        ],
      },
    },
  ],
});

export const featureModules = [];
