import { createModuleManifest } from "@atlas/core";

export const contactsMap = createModuleManifest({
  key: "atlas.contacts",
  name: "Contactos",
  description: "Clientes, proveedores, personas y empresas.",
  version: "0.1.0",
  icon: "ContactRound",
  color: "#0ea5e9",
  category: "operaciones",
  summary: "Clientes, proveedores, personas y empresas",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "preserve-data",
    ownedEntities: ["Contact"],
    sharedEntities: ["Company", "AuditLog"],
  },
  navigation: [
    {
      label: "Contactos",
      path: "/contacts",
      icon: "Contact",
      layout: "main",
      permissionKey: "contacts.contacts.read",
    },
  ],
  permissions: [
    { key: "contacts.access", name: "Access Contacts" },
    { key: "contacts.contacts.read", name: "Read Contacts Feature" },
    { key: "contacts.contacts.create", name: "Create Contacts Feature" },
    { key: "contacts.contacts.update", name: "Update Contacts Feature" },
    { key: "contacts.contacts.delete", name: "Delete Contacts Feature" },
  ],
  exposes: {
    contactPicker: true,
    getContactById: true,
  },
  acl: {
    module: "contacts.access",
    actions: {
      "contacts.contacts.read": "contacts.contacts.read",
      "contacts.contacts.create": "contacts.contacts.create",
      "contacts.contacts.update": "contacts.contacts.update",
      "contacts.contacts.delete": "contacts.contacts.delete",
      "contacts.list": "contacts.contacts.read",
      "contacts.picker": "contacts.contacts.read",
      "contacts.enabled": "contacts.contacts.update",
    },
    models: {
      Contact: {
        read: "contacts.contacts.read",
        create: "contacts.contacts.create",
        update: "contacts.contacts.update",
        delete: "contacts.contacts.delete",
      },
    },
  },
  blueprints: [
    {
      key: "contacts.contact.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Contact",
        label: "Contacto",
        fields: [
          {
            name: "type",
            label: "Tipo",
            type: "select",
            options: ["customer", "supplier", "person", "company"],
            required: true,
          },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "legalName", label: "Nombre legal", type: "text" },
          { name: "email", label: "Correo", type: "email" },
          { name: "phone", label: "Telefono", type: "phone" },
          { name: "taxId", label: "RFC / Tax ID", type: "text" },
          {
            name: "notesMarkdown",
            label: "Observaciones",
            type: "markdown",
            maxLength: 5000,
          },
        ],
        table: { columns: ["type", "name", "email", "phone", "taxId"] },
      },
    },
  ],
});

export const financeMap = createModuleManifest({
  key: "atlas.finance",
  name: "Finanzas",
  description: "Cuentas, movimientos, ingresos, egresos y conciliacion basica.",
  version: "0.1.0",
  icon: "Landmark",
  color: "#10b981",
  category: "contabilidad",
  summary: "Cuentas, movimientos, ingresos y egresos",
  dependencies: [
    { key: "atlas.core" },
    { key: "atlas.contacts", optional: true },
  ],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "preserve-data",
    ownedEntities: ["FinanceAccount", "FinanceJournalEntry", "FinanceJournalLine", "FinanceDocument", "FinanceFxRate", "FinanceTaxRate", "FinanceDocumentApplication"],
    sharedEntities: ["Company", "Contact", "AuditLog"],
  },
  navigation: [
    {
      label: "Resumen",
      path: "/finance",
      icon: "Wallet",
      layout: "main",
      permissionKey: "finance.dashboard.read",
    },
    {
      label: "CxC",
      path: "/finance/ar",
      icon: "HandCoins",
      layout: "main",
      permissionKey: "finance.ar.read",
    },
    {
      label: "CxP",
      path: "/finance/ap",
      icon: "Receipt",
      layout: "main",
      permissionKey: "finance.ap.read",
    },
    {
      label: "Aging",
      path: "/finance/aging",
      icon: "CalendarDays",
      layout: "main",
      permissionKey: "finance.aging.read",
    },
    {
      label: "Aplicaciones",
      path: "/finance/applications",
      icon: "ArrowRightLeft",
      layout: "main",
      permissionKey: "finance.applications.read",
    },
    {
      label: "Cuentas",
      path: "/finance/accounts",
      icon: "ListTree",
      layout: "main",
      permissionKey: "finance.accounts.read",
    },
    {
      label: "Polizas",
      path: "/finance/entries",
      icon: "NotebookPen",
      layout: "main",
      permissionKey: "finance.entries.read",
    },
    {
      label: "Impuestos",
      path: "/finance/taxes",
      icon: "FileText",
      layout: "main",
      permissionKey: "finance.tax_rates.read",
    },
    {
      label: "Tipo de cambio",
      path: "/finance/fx-rates",
      icon: "TrendingUp",
      layout: "main",
      permissionKey: "finance.fx_rates.read",
    },
  ],
  permissions: [
    { key: "finance.access", name: "Access Finance" },
    { key: "finance.ar.read", name: "Read Finance AR" },
    { key: "finance.ar.create", name: "Create Finance AR" },
    { key: "finance.ar.update", name: "Update Finance AR" },
    { key: "finance.ar.delete", name: "Delete Finance AR" },
    { key: "finance.ap.read", name: "Read Finance AP" },
    { key: "finance.ap.create", name: "Create Finance AP" },
    { key: "finance.ap.update", name: "Update Finance AP" },
    { key: "finance.ap.delete", name: "Delete Finance AP" },
    { key: "finance.accounts.read", name: "Read Finance Accounts" },
    { key: "finance.accounts.create", name: "Create Finance Accounts" },
    { key: "finance.accounts.update", name: "Update Finance Accounts" },
    { key: "finance.accounts.delete", name: "Delete Finance Accounts" },
    { key: "finance.entries.read", name: "Read Finance Entries" },
    { key: "finance.entries.create", name: "Create Finance Entries" },
    { key: "finance.entries.update", name: "Update Finance Entries" },
    { key: "finance.entries.delete", name: "Delete Finance Entries" },
    { key: "finance.applications.read", name: "Read Finance Applications" },
    { key: "finance.applications.create", name: "Create Finance Applications" },
    { key: "finance.applications.update", name: "Update Finance Applications" },
    { key: "finance.applications.delete", name: "Delete Finance Applications" },
    { key: "finance.tax_rates.read", name: "Read Finance Tax Rates" },
    { key: "finance.tax_rates.create", name: "Create Finance Tax Rates" },
    { key: "finance.tax_rates.update", name: "Update Finance Tax Rates" },
    { key: "finance.tax_rates.delete", name: "Delete Finance Tax Rates" },
    { key: "finance.fx_rates.read", name: "Read Finance FX Rates" },
    { key: "finance.fx_rates.create", name: "Create Finance FX Rates" },
    { key: "finance.fx_rates.update", name: "Update Finance FX Rates" },
    { key: "finance.fx_rates.delete", name: "Delete Finance FX Rates" },
    { key: "finance.dashboard.read", name: "Read Finance Dashboard" },
    { key: "finance.dashboard.create", name: "Create Finance Dashboard" },
    { key: "finance.dashboard.update", name: "Update Finance Dashboard" },
    { key: "finance.dashboard.delete", name: "Delete Finance Dashboard" },
    { key: "finance.aging.read", name: "Read Finance Aging" },
    { key: "finance.aging.create", name: "Create Finance Aging" },
    { key: "finance.aging.update", name: "Update Finance Aging" },
    { key: "finance.aging.delete", name: "Delete Finance Aging" },
    { key: "finance.documents.read", name: "Read Finance Documents" },
    { key: "finance.documents.create", name: "Create Finance Documents" },
    { key: "finance.documents.update", name: "Update Finance Documents" },
    { key: "finance.documents.delete", name: "Delete Finance Documents" },
    {
      key: "finance.applications.reverse",
      name: "Reverse Finance Applications",
    },
    {
      key: "finance.documents.reminder.send",
      name: "Send Finance Document Reminders",
    },
  ],
  acl: {
    module: "finance.access",
    actions: {
      "finance.dashboard.read": "finance.dashboard.read",
      "finance.dashboard.create": "finance.dashboard.create",
      "finance.dashboard.update": "finance.dashboard.update",
      "finance.dashboard.delete": "finance.dashboard.delete",
      "finance.ar.read": "finance.ar.read",
      "finance.ar.create": "finance.ar.create",
      "finance.ar.update": "finance.ar.update",
      "finance.ar.delete": "finance.ar.delete",
      "finance.ap.read": "finance.ap.read",
      "finance.ap.create": "finance.ap.create",
      "finance.ap.update": "finance.ap.update",
      "finance.ap.delete": "finance.ap.delete",
      "finance.accounts.read": "finance.accounts.read",
      "finance.accounts.create": "finance.accounts.create",
      "finance.accounts.update": "finance.accounts.update",
      "finance.accounts.delete": "finance.accounts.delete",
      "finance.entries.read": "finance.entries.read",
      "finance.entries.create": "finance.entries.create",
      "finance.entries.update": "finance.entries.update",
      "finance.entries.delete": "finance.entries.delete",
      "finance.applications.read": "finance.applications.read",
      "finance.applications.create": "finance.applications.create",
      "finance.applications.update": "finance.applications.update",
      "finance.applications.delete": "finance.applications.delete",
      "finance.applications.reverse": "finance.applications.reverse",
      "finance.tax_rates.read": "finance.tax_rates.read",
      "finance.tax_rates.create": "finance.tax_rates.create",
      "finance.tax_rates.update": "finance.tax_rates.update",
      "finance.tax_rates.delete": "finance.tax_rates.delete",
      "finance.fx_rates.read": "finance.fx_rates.read",
      "finance.fx_rates.create": "finance.fx_rates.create",
      "finance.fx_rates.update": "finance.fx_rates.update",
      "finance.fx_rates.delete": "finance.fx_rates.delete",
      "finance.aging.read": "finance.aging.read",
      "finance.aging.create": "finance.aging.create",
      "finance.aging.update": "finance.aging.update",
      "finance.aging.delete": "finance.aging.delete",
      "finance.documents.read": "finance.documents.read",
      "finance.documents.create": "finance.documents.create",
      "finance.documents.update": "finance.documents.update",
      "finance.documents.delete": "finance.documents.delete",
      "finance.documents.reminder.send": "finance.documents.reminder.send",
    },
    models: {
      FinanceAccount: {
        read: "finance.accounts.read",
        create: "finance.accounts.create",
        update: "finance.accounts.update",
        delete: "finance.accounts.delete",
      },
      FinanceJournalEntry: {
        read: "finance.entries.read",
        create: "finance.entries.create",
        update: "finance.entries.update",
        delete: "finance.entries.delete",
      },
      FinanceDocument: {
        read: "finance.documents.read",
        create: "finance.documents.create",
        update: "finance.documents.update",
        delete: "finance.documents.delete",
      },
      FinanceTaxRate: {
        read: "finance.tax_rates.read",
        create: "finance.tax_rates.create",
        update: "finance.tax_rates.update",
        delete: "finance.tax_rates.delete",
      },
      FinanceFxRate: {
        read: "finance.fx_rates.read",
        create: "finance.fx_rates.create",
        update: "finance.fx_rates.update",
        delete: "finance.fx_rates.delete",
      },
      FinanceDocumentApplication: {
        read: "finance.applications.read",
        create: "finance.applications.create",
        update: "finance.applications.update",
        delete: "finance.applications.delete",
      },
    },
  },
});

export const hrMap = createModuleManifest({
  key: "atlas.hr",
  name: "Recursos Humanos",
  description: "Colaboradores, notas internas y expedientes.",
  version: "0.1.0",
  icon: "UsersRound",
  color: "#2563eb",
  category: "operaciones",
  summary: "Gestión de personal y expediente",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files", optional: true }],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "preserve-data",
    ownedEntities: ["HrEmployee", "HrDepartment", "HrJobTitle"],
    sharedEntities: ["Company", "UserProfile", "FileAsset", "AuditLog"],
  },
  navigation: [
    {
      label: "Colaboradores",
      path: "/hr/employees",
      icon: "Users",
      layout: "main",
      permissionKey: "hr.employee.read",
    },
    {
      label: "Organigrama",
      path: "/hr/org-chart",
      icon: "Network",
      layout: "main",
      permissionKey: "hr.org_chart.read",
    },
    {
      label: "Catálogos",
      path: "/hr/catalogs",
      icon: "BookOpen",
      layout: "main",
      permissionKey: "hr.department.read",
    },
  ],
  permissions: [
    { key: "hr.access", name: "Access HR" },
    { key: "hr.employee.read", name: "Read HR Employees" },
    { key: "hr.employee.create", name: "Create HR Employees" },
    { key: "hr.employee.update", name: "Update HR Employees" },
    { key: "hr.employee.delete", name: "Delete HR Employees" },
    { key: "hr.department.read", name: "Read HR Departments" },
    { key: "hr.department.create", name: "Create HR Departments" },
    { key: "hr.department.update", name: "Update HR Departments" },
    { key: "hr.department.delete", name: "Delete HR Departments" },
    { key: "hr.job_title.read", name: "Read HR Job Titles" },
    { key: "hr.job_title.create", name: "Create HR Job Titles" },
    { key: "hr.job_title.update", name: "Update HR Job Titles" },
    { key: "hr.job_title.delete", name: "Delete HR Job Titles" },
    { key: "hr.org_chart.read", name: "Read HR Org Chart" },
    { key: "hr.org_chart.create", name: "Create HR Org Chart" },
    { key: "hr.org_chart.update", name: "Update HR Org Chart" },
    { key: "hr.org_chart.delete", name: "Delete HR Org Chart" },
  ],
  acl: {
    module: "hr.access",
    actions: {
      "hr.employee.read": "hr.employee.read",
      "hr.employee.create": "hr.employee.create",
      "hr.employee.update": "hr.employee.update",
      "hr.employee.delete": "hr.employee.delete",
      "hr.employee.enable": "hr.employee.update",
      "hr.employee.disable": "hr.employee.update",
      "hr.employee.file.attach": "hr.employee.update",
      "hr.employee.file.delete": "hr.employee.update",
      "hr.department.read": "hr.department.read",
      "hr.department.create": "hr.department.create",
      "hr.department.update": "hr.department.update",
      "hr.department.delete": "hr.department.delete",
      "hr.job_title.read": "hr.job_title.read",
      "hr.job_title.create": "hr.job_title.create",
      "hr.job_title.update": "hr.job_title.update",
      "hr.job_title.delete": "hr.job_title.delete",
      "hr.org_chart.read": "hr.org_chart.read",
      "hr.org_chart.create": "hr.org_chart.create",
      "hr.org_chart.update": "hr.org_chart.update",
      "hr.org_chart.delete": "hr.org_chart.delete",
    },
    models: {
      HrEmployee: {
        read: "hr.employee.read",
        create: "hr.employee.create",
        update: "hr.employee.update",
        delete: "hr.employee.delete",
      },
      HrDepartment: {
        read: "hr.department.read",
        create: "hr.department.create",
        update: "hr.department.update",
        delete: "hr.department.delete",
      },
      HrJobTitle: {
        read: "hr.job_title.read",
        create: "hr.job_title.create",
        update: "hr.job_title.update",
        delete: "hr.job_title.delete",
      },
    },
  },
  blueprints: [
    {
      key: "hr.employee.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "HrEmployee",
        label: "Colaborador",
        fields: [
          { name: "employeeCode", label: "Codigo", type: "text" },
          { name: "userProfileId", label: "Cuenta de usuario", type: "text" },
          { name: "firstName", label: "Nombre", type: "text", required: true },
          {
            name: "lastName",
            label: "Apellidos",
            type: "text",
            required: true,
          },
          { name: "workEmail", label: "Correo laboral", type: "email" },
          { name: "personalEmail", label: "Correo personal", type: "email" },
          { name: "phone", label: "Teléfono", type: "phone" },
          {
            name: "emergencyContactName",
            label: "Contacto de emergencia",
            type: "text",
          },
          {
            name: "emergencyContactPhone",
            label: "Telefono de emergencia",
            type: "phone",
          },
          { name: "jobTitle", label: "Puesto", type: "text" },
          { name: "department", label: "Departamento", type: "text" },
          { name: "managerName", label: "Supervisor", type: "text" },
          {
            name: "employmentType",
            label: "Tipo de empleo",
            type: "select",
            options: ["full_time", "part_time", "contractor", "intern"],
          },
          { name: "workLocation", label: "Ubicacion de trabajo", type: "text" },
          { name: "terminationDate", label: "Fecha de baja", type: "text" },
          {
            name: "status",
            label: "Estado",
            type: "select",
            options: ["active", "inactive", "vacation", "terminated"],
            required: true,
          },
          { name: "notesMarkdown", label: "Notas", type: "markdown" },
        ],
      },
    },
  ],
});

export const ledgerMap = createModuleManifest({
  key: "atlas.ledger",
  name: "Cuentas y Movimientos",
  description: "Libro auxiliar de cuentas con movimientos y exportacion a PDF y Excel.",
  version: "0.1.0",
  icon: "BookOpen",
  color: "#6366f1",
  category: "contabilidad",
  summary: "Libro auxiliar de cuentas y movimientos",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: true,
    supportsDataPurge: true,
    defaultUninstallPolicy: "preserve-data",
    ownedEntities: ["LedgerAccount", "LedgerMovement"],
    sharedEntities: ["Company", "AuditLog"],
    purgeStrategy: "service-defined",
    resetStrategy: "service-defined",
  },
  navigation: [
    {
      label: "Resumen",
      path: "/ledger",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "ledger.accounts.read",
    },
    {
      label: "Cuentas",
      path: "/ledger/accounts",
      icon: "Wallet",
      layout: "main",
      permissionKey: "ledger.accounts.read",
    },
    {
      label: "Movimientos",
      path: "/ledger/movements",
      icon: "ArrowRightLeft",
      layout: "main",
      permissionKey: "ledger.movements.read",
    },
    {
      label: "Reportes",
      path: "/ledger/reports",
      icon: "FileText",
      layout: "main",
      permissionKey: "ledger.reports.read",
    },
  ],
  permissions: [
    { key: "ledger.access", name: "Access Ledger" },
    { key: "ledger.accounts.read", name: "Read Ledger Accounts" },
    { key: "ledger.accounts.create", name: "Create Ledger Accounts" },
    { key: "ledger.accounts.update", name: "Update Ledger Accounts" },
    { key: "ledger.accounts.delete", name: "Delete Ledger Accounts" },
    { key: "ledger.movements.read", name: "Read Ledger Movements" },
    { key: "ledger.movements.create", name: "Create Ledger Movements" },
    { key: "ledger.movements.cancel", name: "Cancel Ledger Movements" },
    { key: "ledger.reports.read", name: "Read Ledger Reports" },
    { key: "ledger.reports.export", name: "Export Ledger Reports" },
  ],
  acl: {
    module: "ledger.access",
    actions: {
      "ledger.accounts.read": "ledger.accounts.read",
      "ledger.accounts.create": "ledger.accounts.create",
      "ledger.accounts.update": "ledger.accounts.update",
      "ledger.accounts.delete": "ledger.accounts.delete",
      "ledger.accounts.enable": "ledger.accounts.delete",
      "ledger.movements.read": "ledger.movements.read",
      "ledger.movements.create": "ledger.movements.create",
      "ledger.movements.cancel": "ledger.movements.cancel",
      "ledger.reports.read": "ledger.reports.read",
      "ledger.reports.export": "ledger.reports.export",
    },
    models: {
      LedgerAccount: {
        read: "ledger.accounts.read",
        create: "ledger.accounts.create",
        update: "ledger.accounts.update",
        delete: "ledger.accounts.delete",
      },
      LedgerMovement: {
        read: "ledger.movements.read",
        create: "ledger.movements.create",
        update: "ledger.movements.cancel",
        delete: "ledger.movements.cancel",
      },
    },
  },
});

export const featureModules = [contactsMap, financeMap, hrMap, ledgerMap];
