-- Synthetic subset of prisma/schema.prisma. No production schema or migration.
-- UUIDs are generated by PostgreSQL 18, never by JavaScript.
CREATE TEMP TABLE runly_module_key_fixture (synthetic boolean);
CREATE TABLE atlas_module (id uuid PRIMARY KEY DEFAULT uuidv7(), key text UNIQUE NOT NULL,
  manifest jsonb NOT NULL, lifecycle_config jsonb, enabled boolean DEFAULT true,
  installed_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), bundle_hash text);
CREATE TABLE company (id uuid PRIMARY KEY DEFAULT uuidv7(), name text);
CREATE TABLE user_profile (id uuid PRIMARY KEY DEFAULT uuidv7());
CREATE TABLE role (id uuid PRIMARY KEY DEFAULT uuidv7(), company_id uuid REFERENCES company(id));
CREATE TABLE company_module (id uuid PRIMARY KEY DEFAULT uuidv7(), company_id uuid REFERENCES company(id),
  module_id uuid REFERENCES atlas_module(id), enabled boolean, config jsonb, UNIQUE(company_id, module_id));
CREATE TABLE module_dependency (id uuid PRIMARY KEY DEFAULT uuidv7(), module_id uuid REFERENCES atlas_module(id),
  dependency_id uuid REFERENCES atlas_module(id), version_range text, UNIQUE(module_id, dependency_id));
CREATE TABLE blueprint (id uuid PRIMARY KEY DEFAULT uuidv7(), key text UNIQUE,
  module_id uuid REFERENCES atlas_module(id), schema jsonb);
CREATE TABLE atlas_model (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text NOT NULL,
  name text UNIQUE, table_name text UNIQUE, schema jsonb);
CREATE TABLE atlas_view (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text NOT NULL,
  key text UNIQUE, model_name text REFERENCES atlas_model(name) ON UPDATE CASCADE, schema jsonb);
CREATE TABLE module_migration (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text NOT NULL,
  filename text, checksum text, applied_at timestamptz DEFAULT now(), UNIQUE(module_key, filename));
CREATE TABLE permission (id uuid PRIMARY KEY DEFAULT uuidv7(), key text UNIQUE,
  module_id uuid REFERENCES atlas_module(id), module_key text, active boolean DEFAULT true);
CREATE TABLE role_permission (id uuid PRIMARY KEY DEFAULT uuidv7(), role_id uuid REFERENCES role(id),
  permission_id uuid REFERENCES permission(id), UNIQUE(role_id, permission_id));
CREATE TABLE user_permission_grant (id uuid PRIMARY KEY DEFAULT uuidv7(), user_id uuid REFERENCES user_profile(id),
  company_id uuid REFERENCES company(id), permission_id uuid REFERENCES permission(id),
  UNIQUE(user_id, company_id, permission_id));
CREATE TABLE file_asset (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text, bucket text,
  object_key text, entity_type text, entity_id uuid, uploaded_by_id uuid REFERENCES user_profile(id), metadata jsonb);
CREATE TABLE file_asset_share (id uuid PRIMARY KEY DEFAULT uuidv7(), file_id uuid REFERENCES file_asset(id),
  user_id uuid REFERENCES user_profile(id), role text, UNIQUE(file_id, user_id));
CREATE TABLE audit_log (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text, payload jsonb);
CREATE TABLE sync_cursor (id uuid PRIMARY KEY DEFAULT uuidv7(), company_id uuid, module_key text,
  entity_type text, cursor timestamptz, UNIQUE(company_id, module_key, entity_type));
CREATE TABLE sync_mutation_log (id uuid PRIMARY KEY DEFAULT uuidv7(), module_key text,
  idempotency_key uuid UNIQUE DEFAULT uuidv7(), record_id uuid, applied_at timestamptz DEFAULT now());
CREATE TABLE user_preference (id uuid PRIMARY KEY DEFAULT uuidv7(), value jsonb);
