export const MODULE_ICON_NAMES = Object.freeze([
  'Activity',
  'ArrowRightLeft',
  'BarChart3',
  'Bell',
  'BookOpen',
  'Box',
  'Boxes',
  'Building2',
  'Calendar',
  'CalendarDays',
  'ClipboardList',
  'Contact',
  'ContactRound',
  'CreditCard',
  'Files',
  'FileText',
  'FolderOpen',
  'Globe',
  'HandCoins',
  'Landmark',
  'Layers',
  'LayoutDashboard',
  'LayoutTemplate',
  'Library',
  'ListOrdered',
  'ListTree',
  'MapPin',
  'Menu',
  'Network',
  'NotebookPen',
  'Package',
  'Palette',
  'Puzzle',
  'Receipt',
  'Settings',
  'Shield',
  'ShieldCheck',
  'ShoppingBag',
  'ShoppingCart',
  'SlidersHorizontal',
  'SquareKanban',
  'Store',
  'Tag',
  'TrendingUp',
  'Truck',
  'UserCheck',
  'Users',
  'UsersRound',
  'Wallet',
  'Wrench',
])

const MODULE_ICON_NAME_SET = new Set(MODULE_ICON_NAMES)

export function isModuleIconName(value) {
  return typeof value === 'string' && MODULE_ICON_NAME_SET.has(value)
}
