import { defineModel } from "@atlas/module-engine";

export default defineModel({
  key: "report",
  name: "fleet.report",
  label: "Reporte",
  tableName: "fleet_report",
  companyScoped: true,
  softDelete: true,
  fields: [
    { name: "report_type", type: "select", label: "Tipo de reporte", required: true, options: ["maintenance", "service", "repair", "other"] },
    { name: "folio", type: "text", label: "Folio", required: true, maxLength: 32 },
    { name: "status", type: "select", label: "Estado", required: true, options: ["draft", "finalized"], default: "draft" },
    { name: "vehicle_id", type: "relation", label: "Vehiculo", required: true, relatedModel: "fleet.vehicle" },
    { name: "title", type: "text", label: "Titulo", required: true, maxLength: 255 },
    { name: "report_date", type: "date", label: "Fecha", required: true },
    { name: "odometer_km", type: "number", label: "Kilometraje" },
    { name: "is_inhouse_workshop", type: "boolean", label: "Taller propio", required: true, default: true },
    { name: "workshop_name", type: "text", label: "Taller", maxLength: 200 },
    { name: "workshop_phone", type: "text", label: "Telefono", maxLength: 50 },
    { name: "workshop_address", type: "text", label: "Direccion", maxLength: 300 },
    { name: "invoice_number", type: "text", label: "No factura", maxLength: 80 },
    { name: "labor_cost", type: "decimal", label: "Mano de obra", default: 0 },
    { name: "parts_cost", type: "decimal", label: "Refacciones", default: 0 },
    { name: "total_cost", type: "decimal", label: "Total", default: 0 },
    { name: "notes", type: "textarea", label: "Observaciones", maxLength: 5000 },
    { name: "finalized_at", type: "datetime", label: "Fecha finalizado" },
    { name: "finalized_by_profile_id", type: "relation", label: "Finalizado por" },
    { name: "maintenance_subtype", type: "select", label: "Subtipo mantenimiento", options: ["preventive", "corrective", "inspection", "alignment", "oil_change", "tire_service", "other"] },
    { name: "next_service_date", type: "date", label: "Proximo servicio fecha" },
    { name: "next_service_odometer", type: "number", label: "Proximo servicio km" },
    { name: "service_subtype", type: "select", label: "Subtipo servicio", options: ["general", "diagnostic", "cleaning", "electrical", "other"] },
    { name: "repair_priority", type: "select", label: "Prioridad reparacion", options: ["low", "normal", "high", "urgent"] },
    { name: "repair_damage_type", type: "select", label: "Tipo de dano", options: ["mechanical", "electrical", "body", "interior", "other"] },
    { name: "repair_start_date", type: "date", label: "Inicio reparacion" },
    { name: "repair_completion_date", type: "date", label: "Fin reparacion" },
    { name: "repair_estimated_cost", type: "decimal", label: "Costo estimado" },
    { name: "warranty_days", type: "number", label: "Dias garantia" },
    { name: "warranty_notes", type: "textarea", label: "Notas garantia", maxLength: 1000 },
    { name: "other_category_label", type: "text", label: "Categoria otro", maxLength: 120 },
  ],
  indexes: [
    { fields: ["company_id", "report_type"] },
    { fields: ["company_id", "status"] },
    { fields: ["company_id", "vehicle_id"] },
    { fields: ["company_id", "report_date"] },
    { fields: ["company_id", "folio"], unique: true },
  ],
});
