import { createModuleManifest, MODULE_KINDS } from "@atlas/core";
import {
  contactsMap,
  hrMap,
  atlasWebsiteManifest,
  activityMap,
  notificationsMap,
} from "./feature-modules.js";

export const atlasCoreMap = createModuleManifest({
  key: "atlas.core",
  name: "Atlas Core",
  description:
    "Nucleo del sistema: modulos, permisos, bitacora y configuracion de instancia.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Layers",
  color: "#0A7BFF",
  category: "sistema",
  summary: "Modulos, permisos, bitacora y configuracion del sistema",
  navigation: [
    {
      label: "Dashboard",
      path: "/",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "core.access",
    },
    {
      label: "Modulos",
      path: "/modules",
      icon: "Puzzle",
      layout: "main",
      permissionKey: "core.modules.read",
    },
    {
      label: "Configuracion",
      path: "/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "core.instance.read",
    },
  ],
  permissions: [
    { key: "core.access", name: "Access Core" },
    { key: "core.modules.read", name: "Read Core Modules" },
    { key: "core.modules.create", name: "Install Core Modules" },
    { key: "core.modules.update", name: "Enable or Disable Core Modules" },
    { key: "core.modules.delete", name: "Uninstall Core Modules" },
    { key: "core.instance.read", name: "Read Core Instance" },
    { key: "core.instance.create", name: "Create Core Instance Config" },
    { key: "core.instance.update", name: "Update Core Instance Config" },
    { key: "core.instance.delete", name: "Delete Core Instance Config" },
    { key: "core.read", name: "Read Core" },
    { key: "core.manage", name: "Manage Core" },
    { key: "audit.read", name: "Read Audit Logs" },
  ],
  acl: {
    module: "core.access",
    actions: {
      "modules.catalog.read": "core.modules.read",
      "instance.config.read": "core.instance.read",
      "instance.config.update": "core.instance.update",
    },
    models: {
      AtlasModule: {
        read: "core.modules.read",
        create: "core.modules.create",
        update: "core.modules.update",
        delete: "core.modules.delete",
      },
    },
  },
  blueprints: [
    {
      key: "atlas.module.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "AtlasModule",
        label: "Modulo",
        fields: [
          { name: "key", label: "Clave", type: "text", required: true },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "version", label: "Version", type: "text", required: true },
          {
            name: "kind",
            label: "Tipo",
            type: "select",
            options: ["CORE", "FEATURE", "INTEGRATION", "WEBSITE"],
          },
          { name: "enabled", label: "Activo", type: "boolean" },
        ],
      },
    },
  ],
});

export const identityMap = createModuleManifest({
  key: "atlas.identity",
  name: "Identidad",
  description: "Usuarios, roles, permisos, membresias y control de acceso.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Shield",
  color: "#21C7FF",
  category: "sistema",
  summary: "Usuarios, empresas, roles y membresias",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Usuarios",
      path: "/identity/users",
      icon: "Users",
      layout: "main",
      permissionKey: "identity.users.read",
    },
    {
      label: "Roles",
      path: "/identity/roles",
      icon: "Shield",
      layout: "main",
      permissionKey: "identity.roles.read",
    },
  ],
  permissions: [
    { key: "identity.access", name: "Access Identity" },
    { key: "identity.users.read", name: "Read Users" },
    { key: "identity.users.create", name: "Create Users" },
    { key: "identity.users.update", name: "Update Users" },
    { key: "identity.users.delete", name: "Delete Users" },
    { key: "identity.roles.read", name: "Read Identity Roles" },
    { key: "identity.roles.create", name: "Create Identity Roles" },
    { key: "identity.roles.update", name: "Update Identity Roles" },
    { key: "identity.roles.delete", name: "Delete Identity Roles" },
    { key: "identity.permissions.read", name: "Read Identity Permissions" },
    { key: "identity.permissions.create", name: "Create Identity Permissions" },
    { key: "identity.permissions.update", name: "Update Identity Permissions" },
    { key: "identity.permissions.delete", name: "Delete Identity Permissions" },
    { key: "profile.self.read", name: "Read Own Profile" },
    { key: "profile.self.update", name: "Update Own Profile" },
    { key: "profile.avatar.update", name: "Update Own Avatar" },
    { key: "profile.password.update", name: "Update Own Password" },
  ],
  acl: {
    module: "identity.access",
    actions: {
      "identity.users.read": "identity.users.read",
      "identity.users.create": "identity.users.create",
      "identity.users.update": "identity.users.update",
      "identity.users.delete": "identity.users.delete",
      "identity.roles.read": "identity.roles.read",
      "identity.roles.create": "identity.roles.create",
      "identity.roles.update": "identity.roles.update",
      "identity.roles.delete": "identity.roles.delete",
      "identity.permissions.read": "identity.permissions.read",
      "identity.permissions.create": "identity.permissions.create",
      "identity.permissions.update": "identity.permissions.update",
      "identity.permissions.delete": "identity.permissions.delete",
      "profile.self.read": "profile.self.read",
      "profile.self.update": "profile.self.update",
      "profile.avatar.update": "profile.avatar.update",
      "profile.password.update": "profile.password.update",
    },
    models: {
      UserProfile: {
        read: "identity.users.read",
        create: "identity.users.create",
        update: "identity.users.update",
        delete: "identity.users.delete",
      },
      Role: {
        read: "identity.roles.read",
        create: "identity.roles.create",
        update: "identity.roles.update",
        delete: "identity.roles.delete",
      },
      Permission: {
        read: "identity.permissions.read",
        create: "identity.permissions.create",
        update: "identity.permissions.update",
        delete: "identity.permissions.delete",
      },
    },
  },
});

export const filesMap = createModuleManifest({
  key: "atlas.files",
  name: "Archivos",
  description: "Gestion de archivos, carga, almacenamiento y acceso seguro.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "FolderOpen",
  color: "#f59e0b",
  category: "sistema",
  summary: "Gestion de archivos y almacenamiento",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Archivos",
      path: "/files",
      icon: "FolderOpen",
      layout: "main",
      permissionKey: "files.assets.read",
    },
  ],
  permissions: [
    { key: "files.access", name: "Access Files" },
    { key: "files.assets.read", name: "Read File Assets" },
    { key: "files.assets.create", name: "Create File Assets" },
    { key: "files.assets.update", name: "Update File Assets" },
    { key: "files.assets.delete", name: "Delete File Assets" },
  ],
  acl: {
    module: "files.access",
    actions: {
      "files.assets.read": "files.assets.read",
      "files.assets.create": "files.assets.create",
      "files.assets.update": "files.assets.update",
      "files.assets.delete": "files.assets.delete",
      "files.rename": "files.assets.update",
      "files.enabled": "files.assets.update",
      "files.bulk-download": "files.assets.read",
      "files.signed-url": "files.assets.read",
    },
    models: {
      FileAsset: {
        read: "files.assets.read",
        create: "files.assets.create",
        update: "files.assets.update",
        delete: "files.assets.delete",
      },
    },
  },
});

export const companyMap = createModuleManifest({
  key: "atlas.company",
  name: "Empresa",
  description:
    "Perfil de empresa, direccion, marca visual e identidad corporativa.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Building2",
  color: "#ec4899",
  category: "sistema",
  summary: "Perfil, direccion y marca visual de la empresa",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files" }],
  navigation: [
    {
      label: "Resumen",
      path: "/",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Perfil",
      path: "/company",
      icon: "Building2",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Direccion",
      path: "/company/address",
      icon: "MapPin",
      layout: "main",
      permissionKey: "company.address.read",
    },
    {
      label: "Marca visual",
      path: "/company/branding",
      icon: "Palette",
      layout: "main",
      permissionKey: "company.branding.read",
    },
  ],
  permissions: [
    { key: "company.access", name: "Access Company" },
    { key: "company.profile.read", name: "Read Company Profile" },
    { key: "company.profile.create", name: "Create Company Profile" },
    { key: "company.profile.update", name: "Update Company Profile" },
    { key: "company.profile.delete", name: "Delete Company Profile" },
    { key: "company.address.read", name: "Read Company Address" },
    { key: "company.address.create", name: "Create Company Address" },
    { key: "company.address.update", name: "Update Company Address" },
    { key: "company.address.delete", name: "Delete Company Address" },
    { key: "company.branding.read", name: "Read Company Branding" },
    { key: "company.branding.create", name: "Create Company Branding" },
    { key: "company.branding.update", name: "Update Company Branding" },
    { key: "company.branding.delete", name: "Delete Company Branding" },
  ],
  acl: {
    module: "company.access",
    actions: {
      "company.profile.read": "company.profile.read",
      "company.profile.update": "company.profile.update",
      "company.address.read": "company.address.read",
      "company.address.update": "company.address.update",
      "company.branding.read": "company.branding.read",
      "company.branding.update": "company.branding.update",
    },
    models: {
      Company: {
        read: "company.profile.read",
        create: "company.profile.create",
        update: "company.profile.update",
        delete: "company.profile.delete",
      },
      BrandingConfig: {
        read: "company.branding.read",
        create: "company.branding.create",
        update: "company.branding.update",
        delete: "company.branding.delete",
      },
    },
  },
  exposes: {
    logoUrl: "string",
    primaryColor: "string",
    companyName: "string",
    contactEmail: "string",
    phone: "string",
  },
});

export const atlasLedgerManifest = createModuleManifest({
  key: "atlas.ledger",
  name: "Libro de cuentas",
  version: "0.1.1",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  description:
    "Registro bancario tipo hoja de calculo: depositos, retiros y saldo corriente.",
  summary: "Cuentas bancarias, registro de movimientos y exportacion.",
  icon: "Landmark",
  color: "#16a34a",
  accentColor: "#15803d",
  initials: "LC",
  fullscreenPaths: ["/accounts/:id", "/accounts/:id/import"],
  dependencies: [{ key: "atlas.core" }],
  permissions: [
    { key: "ledger.accounts.read", name: "Ver cuentas" },
    { key: "ledger.accounts.create", name: "Crear cuentas" },
    { key: "ledger.accounts.update", name: "Editar cuentas" },
    { key: "ledger.accounts.delete", name: "Desactivar cuentas" },
    { key: "ledger.transactions.read", name: "Ver movimientos" },
    { key: "ledger.transactions.create", name: "Crear movimientos" },
    { key: "ledger.transactions.update", name: "Editar movimientos" },
    { key: "ledger.transactions.delete", name: "Desactivar movimientos" },
    { key: "ledger.export", name: "Exportar movimientos" },
    { key: "ledger.import", name: "Importar movimientos" },
    { key: "ledger.categories.manage", name: "Gestionar categorias" },
    { key: "ledger.types.manage", name: "Gestionar tipos de movimiento" },
  ],
  acl: {
    module: "ledger.accounts.read",
    actions: {
      "ledger.accounts.read": "ledger.accounts.read",
      "ledger.accounts.create": "ledger.accounts.create",
      "ledger.accounts.update": "ledger.accounts.update",
      "ledger.accounts.delete": "ledger.accounts.delete",
      "ledger.transactions.read": "ledger.transactions.read",
      "ledger.transactions.create": "ledger.transactions.create",
      "ledger.transactions.update": "ledger.transactions.update",
      "ledger.transactions.delete": "ledger.transactions.delete",
      "ledger.export": "ledger.export",
      "ledger.import": "ledger.import",
      "ledger.categories.manage": "ledger.categories.manage",
      "ledger.types.manage": "ledger.types.manage",
    },
  },
  navigation: [
    {
      label: "Cuentas",
      path: "/app/m/atlas.ledger/accounts",
      icon: "Landmark",
      layout: "main",
      permissionKey: "ledger.accounts.read",
    },
    {
      label: "Categorias",
      path: "/app/m/atlas.ledger/categories",
      icon: "Tag",
      layout: "main",
      permissionKey: "ledger.categories.manage",
    },
    {
      label: "Tipos de mov.",
      path: "/app/m/atlas.ledger/types",
      icon: "SlidersHorizontal",
      layout: "main",
      permissionKey: "ledger.types.manage",
    },
  ],
});

export const atlasFleetManifest = createModuleManifest({
  key: "atlas.fleet",
  name: "Flota",
  version: "0.5.1",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  description:
    "Gestion de flota vehicular: vehiculos, reportes y asignacion de conductores.",
  summary: "Vehiculos, conductores, reportes y control operativo.",
  icon: "Truck",
  color: "#14B8A6",
  accentColor: "#0F766E",
  initials: "FL",
  logoUrl: "/module-logos/custom-fleet-128.webp",
  dependencies: [{ key: "atlas.core" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedModels: [
      "fleet.vehicle",
      "fleet.driver",
      "fleet.vehicle_type",
      "fleet.vehicle_brand",
      "fleet.vehicle_document",
      "fleet.driver_document",
      "fleet.vehicle_model",
      "fleet.report",
      "fleet.report_part",
      "fleet.report_document",
      "fleet.insurance_policy",
    ],
    ownedTables: [
      "fleet_vehicle",
      "fleet_driver",
      "fleet_vehicle_type",
      "fleet_vehicle_brand",
      "fleet_vehicle_document",
      "fleet_driver_document",
      "fleet_vehicle_model",
      "fleet_report",
      "fleet_report_part",
      "fleet_report_document",
      "fleet_insurance_policy",
    ],
    ownedEntities: ["Vehicle"],
    sharedEntities: ["Company", "AuditLog"],
  },
  permissions: [
    { key: "fleet.access", name: "Acceso a Flota" },
    { key: "fleet.vehicles.read", name: "Ver vehiculos" },
    { key: "fleet.vehicles.create", name: "Crear vehiculos" },
    { key: "fleet.vehicles.update", name: "Editar vehiculos" },
    { key: "fleet.vehicles.delete", name: "Desactivar vehiculos" },
    { key: "fleet.reports.read", name: "Ver reportes" },
    { key: "fleet.reports.create", name: "Crear reportes" },
    { key: "fleet.reports.update", name: "Editar reportes" },
    { key: "fleet.reports.delete", name: "Eliminar reportes" },
    { key: "fleet.drivers.read", name: "Ver choferes" },
    { key: "fleet.drivers.create", name: "Crear choferes" },
    { key: "fleet.drivers.update", name: "Editar choferes" },
    { key: "fleet.drivers.delete", name: "Desactivar choferes" },
    { key: "fleet.catalogs.read", name: "Ver catalogos de flota" },
    { key: "fleet.catalogs.create", name: "Crear catalogos de flota" },
    { key: "fleet.catalogs.update", name: "Editar catalogos de flota" },
    { key: "fleet.catalogs.delete", name: "Desactivar catalogos de flota" },
    { key: "fleet.insurance.read", name: "Ver polizas de seguro" },
    { key: "fleet.insurance.create", name: "Crear polizas de seguro" },
    { key: "fleet.insurance.update", name: "Editar polizas de seguro" },
    { key: "fleet.insurance.delete", name: "Desactivar polizas de seguro" },
  ],
  acl: {
    module: "fleet.access",
    actions: {
      "fleet.vehicles.read": "fleet.vehicles.read",
      "fleet.vehicles.create": "fleet.vehicles.create",
      "fleet.vehicles.update": "fleet.vehicles.update",
      "fleet.vehicles.delete": "fleet.vehicles.delete",
      "fleet.reports.read": "fleet.reports.read",
      "fleet.reports.create": "fleet.reports.create",
      "fleet.reports.update": "fleet.reports.update",
      "fleet.reports.delete": "fleet.reports.delete",
      "fleet.drivers.read": "fleet.drivers.read",
      "fleet.drivers.create": "fleet.drivers.create",
      "fleet.drivers.update": "fleet.drivers.update",
      "fleet.drivers.delete": "fleet.drivers.delete",
      "fleet.catalogs.read": "fleet.catalogs.read",
      "fleet.catalogs.create": "fleet.catalogs.create",
      "fleet.catalogs.update": "fleet.catalogs.update",
      "fleet.catalogs.delete": "fleet.catalogs.delete",
      "fleet.insurance.read": "fleet.insurance.read",
      "fleet.insurance.create": "fleet.insurance.create",
      "fleet.insurance.update": "fleet.insurance.update",
      "fleet.insurance.delete": "fleet.insurance.delete",
    },
    models: {
      Vehicle: {
        read: "fleet.vehicles.read",
        create: "fleet.vehicles.create",
        update: "fleet.vehicles.update",
        delete: "fleet.vehicles.delete",
      },
      Report: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      ReportPart: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      ReportDocument: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      Driver: {
        read: "fleet.drivers.read",
        create: "fleet.drivers.create",
        update: "fleet.drivers.update",
        delete: "fleet.drivers.delete",
      },
      VehicleType: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      VehicleBrand: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      VehicleDocument: {
        read: "fleet.vehicles.read",
        create: "fleet.vehicles.create",
        update: "fleet.vehicles.update",
        delete: "fleet.vehicles.delete",
      },
      DriverDocument: {
        read: "fleet.drivers.read",
        create: "fleet.drivers.create",
        update: "fleet.drivers.update",
        delete: "fleet.drivers.delete",
      },
      VehicleModel: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      InsurancePolicy: {
        read: "fleet.insurance.read",
        create: "fleet.insurance.create",
        update: "fleet.insurance.update",
        delete: "fleet.insurance.delete",
      },
    },
  },
  navigation: [
    {
      label: "Vehiculos",
      path: "/app/m/atlas.fleet/vehicles",
      icon: "Truck",
      layout: "main",
      permissionKey: "fleet.vehicles.read",
    },
    {
      label: "Seguros",
      path: "/app/m/atlas.fleet/insurance",
      icon: "ShieldCheck",
      layout: "main",
      permissionKey: "fleet.insurance.read",
    },
    {
      label: "Reportes",
      path: "/app/m/atlas.fleet/reports",
      icon: "ClipboardList",
      layout: "main",
      permissionKey: "fleet.reports.read",
      children: [
        {
          label: "Mantenimiento",
          path: "/app/m/atlas.fleet/reports/maintenance",
          permissionKey: "fleet.reports.read",
        },
        {
          label: "Servicio",
          path: "/app/m/atlas.fleet/reports/service",
          permissionKey: "fleet.reports.read",
        },
        {
          label: "Reparacion",
          path: "/app/m/atlas.fleet/reports/repair",
          permissionKey: "fleet.reports.read",
        },
      ],
    },
    {
      label: "Choferes",
      path: "/app/m/atlas.fleet/drivers",
      icon: "UserCheck",
      layout: "main",
      permissionKey: "fleet.drivers.read",
    },
    {
      label: "Catalogos",
      path: "/app/m/atlas.fleet/catalogs",
      icon: "Layers",
      layout: "main",
      permissionKey: "fleet.catalogs.read",
      children: [
        {
          label: "Tipos de vehiculo",
          path: "/app/m/atlas.fleet/catalogs/vehicle-types",
          permissionKey: "fleet.catalogs.read",
        },
        {
          label: "Marcas",
          path: "/app/m/atlas.fleet/catalogs/vehicle-brands",
          permissionKey: "fleet.catalogs.read",
        },
        {
          label: "Modelos",
          path: "/app/m/atlas.fleet/catalogs/vehicle-models",
          permissionKey: "fleet.catalogs.read",
        },
      ],
    },
  ],
});

export const atlasCalendarManifest = createModuleManifest({
  key: "atlas.calendar",
  name: "Calendario",
  description:
    "Calendario personal y compartido con eventos, recordatorios y vistas por dia, semana y mes.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Calendar",
  color: "#7C3AED",
  accentColor: "#6D28D9",
  initials: "CA",
  logoUrl: "/module-logos/atlas-calendar-128.svg",
  category: "sistema",
  summary: "Calendarios personales, eventos y recordatorios",
  fullscreenPaths: ["/calendar"],
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  navigation: [
    {
      label: "Calendario",
      path: "/app/m/atlas.calendar/calendar",
      icon: "Calendar",
      layout: "main",
      permissionKey: "calendar.access",
    },
  ],
  permissions: [
    { key: "calendar.access", name: "Acceso al calendario" },
    { key: "calendar.calendars.read", name: "Ver calendarios" },
    { key: "calendar.calendars.create", name: "Crear calendarios" },
    { key: "calendar.calendars.update", name: "Editar calendarios" },
    { key: "calendar.calendars.delete", name: "Eliminar calendarios" },
    { key: "calendar.events.read", name: "Ver eventos" },
    { key: "calendar.events.create", name: "Crear eventos" },
    { key: "calendar.events.update", name: "Editar eventos" },
    { key: "calendar.events.delete", name: "Eliminar eventos" },
    { key: "calendar.share.manage", name: "Gestionar accesos compartidos" },
  ],
  acl: {
    module: "calendar.access",
    actions: {
      "calendar.calendars.read": "calendar.calendars.read",
      "calendar.calendars.create": "calendar.calendars.create",
      "calendar.calendars.update": "calendar.calendars.update",
      "calendar.calendars.delete": "calendar.calendars.delete",
      "calendar.events.read": "calendar.events.read",
      "calendar.events.create": "calendar.events.create",
      "calendar.events.update": "calendar.events.update",
      "calendar.events.delete": "calendar.events.delete",
      "calendar.share.manage": "calendar.share.manage",
    },
  },
  exposes: {
    "calendar.createEvent": "function",
    "calendar.getEvents": "function",
  },
  consumes: ["atlas.files"],
});

export const atlasCatalogManifest = createModuleManifest({
  key: "atlas.catalog",
  name: "Catalogo",
  description: "Gestiona productos, categorias, variantes e inventario",
  version: "2.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "ShoppingBag",
  color: "#F97316",
  accentColor: "#EA580C",
  initials: "CT",
  category: "comercial",
  logoUrl: "/module-logos/atlas-catalog-128.svg",
  summary: "Productos, categorias, variantes e inventario unificados.",
  dependencies: [{ key: "atlas.core" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [
      "CatalogCategory",
      "CatalogProduct",
      "CatalogProductOption",
      "CatalogProductOptionValue",
      "CatalogProductVariant",
      "CatalogStockMovement",
    ],
    ownedTables: [
      "catalog_category",
      "catalog_product",
      "catalog_product_option",
      "catalog_product_option_value",
      "catalog_product_variant",
      "catalog_stock_movement",
    ],
    sharedEntities: ["Company"],
  },
  permissions: [
    { key: "catalog.access",            name: "Acceder al catalogo" },
    { key: "catalog.products.read",     name: "Ver productos" },
    { key: "catalog.products.create",   name: "Crear productos" },
    { key: "catalog.products.update",   name: "Editar productos" },
    { key: "catalog.products.delete",   name: "Eliminar productos" },
    { key: "catalog.categories.read",   name: "Ver categorias" },
    { key: "catalog.categories.create", name: "Crear categorias" },
    { key: "catalog.categories.update", name: "Editar categorias" },
    { key: "catalog.categories.delete", name: "Eliminar categorias" },
    { key: "catalog.inventory.adjust",  name: "Ajustar stock" },
  ],
  acl: {
    module: "catalog.access",
    actions: {
      "catalog.products.read":     "catalog.products.read",
      "catalog.products.create":   "catalog.products.create",
      "catalog.products.update":   "catalog.products.update",
      "catalog.products.delete":   "catalog.products.delete",
      "catalog.categories.read":   "catalog.categories.read",
      "catalog.categories.create": "catalog.categories.create",
      "catalog.categories.update": "catalog.categories.update",
      "catalog.categories.delete": "catalog.categories.delete",
      "catalog.inventory.adjust":  "catalog.inventory.adjust",
    },
    models: {
      CatalogProduct: {
        read:   "catalog.products.read",
        create: "catalog.products.create",
        update: "catalog.products.update",
        delete: "catalog.products.delete",
      },
      CatalogCategory: {
        read:   "catalog.categories.read",
        create: "catalog.categories.create",
        update: "catalog.categories.update",
        delete: "catalog.categories.delete",
      },
    },
  },
  navigation: [
    {
      label: "Productos",
      path: "/app/m/atlas.catalog",
      icon: "ShoppingCart",
      layout: "main",
      permissionKey: "catalog.products.read",
    },
    {
      label: "Categorias",
      path: "/app/m/atlas.catalog/categories",
      icon: "Tag",
      layout: "main",
      permissionKey: "catalog.categories.read",
    },
    {
      label: "Inventario",
      path: "/app/m/atlas.catalog/inventory",
      icon: "BarChart3",
      layout: "main",
      permissionKey: "catalog.products.read",
    },
  ],
  blueprints: [],
});

export const coreModules = [
  atlasCoreMap,
  identityMap,
  filesMap,
  companyMap,
  contactsMap,
  hrMap,
  atlasFleetManifest,
  atlasLedgerManifest,
  atlasWebsiteManifest,
  atlasCalendarManifest,
  activityMap,
  notificationsMap,
  atlasCatalogManifest,
];
