import { createModuleManifest, MODULE_KINDS } from "@atlas/core";
import { contactsMap, hrMap } from "./feature-modules.js";
import atlasFleetManifest from "../../../../../modules/official/atlas.fleet/module.manifest.js";

export const atlasCoreMap = createModuleManifest({
  key: "atlas.core",
  name: "Atlas Core",
  description:
    "Core runtime, registry, permissions, audit and system configuration.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Layers",
  color: "#0A7BFF",
  category: "sistema",
  summary: "Modulos, permisos, bitacora y configuracion del sistema",
  navigation: [
    {
      label: "Dashboard",
      path: "/",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "core.access",
    },
    {
      label: "Modulos",
      path: "/modules",
      icon: "Puzzle",
      layout: "main",
      permissionKey: "core.modules.read",
    },
    {
      label: "Configuracion",
      path: "/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "core.instance.read",
    },
  ],
  permissions: [
    { key: "core.access", name: "Access Core" },
    { key: "core.modules.read", name: "Read Core Modules" },
    { key: "core.modules.create", name: "Install Core Modules" },
    { key: "core.modules.update", name: "Enable or Disable Core Modules" },
    { key: "core.modules.delete", name: "Uninstall Core Modules" },
    { key: "core.instance.read", name: "Read Core Instance" },
    { key: "core.instance.create", name: "Create Core Instance Config" },
    { key: "core.instance.update", name: "Update Core Instance Config" },
    { key: "core.instance.delete", name: "Delete Core Instance Config" },
    { key: "core.read", name: "Read Core" },
    { key: "core.manage", name: "Manage Core" },
    { key: "audit.read", name: "Read Audit Logs" },
  ],
  acl: {
    module: "core.access",
    actions: {
      "modules.catalog.read": "core.modules.read",
      "instance.config.read": "core.instance.read",
      "instance.config.update": "core.instance.update",
    },
    models: {
      AtlasModule: {
        read: "core.modules.read",
        create: "core.modules.create",
        update: "core.modules.update",
        delete: "core.modules.delete",
      },
    },
  },
  blueprints: [
    {
      key: "atlas.module.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "AtlasModule",
        label: "Modulo",
        fields: [
          { name: "key", label: "Clave", type: "text", required: true },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "version", label: "Version", type: "text", required: true },
          {
            name: "kind",
            label: "Tipo",
            type: "select",
            options: ["CORE", "FEATURE", "INTEGRATION", "WEBSITE"],
          },
          { name: "enabled", label: "Activo", type: "boolean" },
        ],
      },
    },
  ],
});

export const identityMap = createModuleManifest({
  key: "atlas.identity",
  name: "Identidad",
  description: "Profiles, companies, roles, permissions and memberships.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Users",
  color: "#21C7FF",
  category: "sistema",
  summary: "Usuarios, empresas, roles y membresias",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Usuarios",
      path: "/identity/users",
      icon: "Users",
      layout: "main",
      permissionKey: "identity.users.read",
    },
    {
      label: "Roles",
      path: "/identity/roles",
      icon: "Shield",
      layout: "main",
      permissionKey: "identity.roles.read",
    },
  ],
  permissions: [
    { key: "identity.access", name: "Access Identity" },
    { key: "identity.users.read", name: "Read Users" },
    { key: "identity.users.create", name: "Create Users" },
    { key: "identity.users.update", name: "Update Users" },
    { key: "identity.users.delete", name: "Delete Users" },
    { key: "identity.roles.read", name: "Read Identity Roles" },
    { key: "identity.roles.create", name: "Create Identity Roles" },
    { key: "identity.roles.update", name: "Update Identity Roles" },
    { key: "identity.roles.delete", name: "Delete Identity Roles" },
    { key: "identity.permissions.read", name: "Read Identity Permissions" },
    { key: "identity.permissions.create", name: "Create Identity Permissions" },
    { key: "identity.permissions.update", name: "Update Identity Permissions" },
    { key: "identity.permissions.delete", name: "Delete Identity Permissions" },
    { key: "profile.self.read", name: "Read Own Profile" },
    { key: "profile.self.update", name: "Update Own Profile" },
    { key: "profile.avatar.update", name: "Update Own Avatar" },
    { key: "profile.password.update", name: "Update Own Password" },
  ],
  acl: {
    module: "identity.access",
    actions: {
      "identity.users.read": "identity.users.read",
      "identity.users.create": "identity.users.create",
      "identity.users.update": "identity.users.update",
      "identity.users.delete": "identity.users.delete",
      "identity.roles.read": "identity.roles.read",
      "identity.roles.create": "identity.roles.create",
      "identity.roles.update": "identity.roles.update",
      "identity.roles.delete": "identity.roles.delete",
      "identity.permissions.read": "identity.permissions.read",
      "identity.permissions.create": "identity.permissions.create",
      "identity.permissions.update": "identity.permissions.update",
      "identity.permissions.delete": "identity.permissions.delete",
      "profile.self.read": "profile.self.read",
      "profile.self.update": "profile.self.update",
      "profile.avatar.update": "profile.avatar.update",
      "profile.password.update": "profile.password.update",
    },
    models: {
      UserProfile: {
        read: "identity.users.read",
        create: "identity.users.create",
        update: "identity.users.update",
        delete: "identity.users.delete",
      },
      Role: {
        read: "identity.roles.read",
        create: "identity.roles.create",
        update: "identity.roles.update",
        delete: "identity.roles.delete",
      },
      Permission: {
        read: "identity.permissions.read",
        create: "identity.permissions.create",
        update: "identity.permissions.update",
        delete: "identity.permissions.delete",
      },
    },
  },
});

export const filesMap = createModuleManifest({
  key: "atlas.files",
  name: "Archivos",
  description: "File metadata and storage integration.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "FolderOpen",
  color: "#f59e0b",
  category: "sistema",
  summary: "Gestion de archivos y almacenamiento",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Archivos",
      path: "/files",
      icon: "FolderOpen",
      layout: "main",
      permissionKey: "files.assets.read",
    },
  ],
  permissions: [
    { key: "files.access", name: "Access Files" },
    { key: "files.assets.read", name: "Read File Assets" },
    { key: "files.assets.create", name: "Create File Assets" },
    { key: "files.assets.update", name: "Update File Assets" },
    { key: "files.assets.delete", name: "Delete File Assets" },
  ],
  acl: {
    module: "files.access",
    actions: {
      "files.assets.read": "files.assets.read",
      "files.assets.create": "files.assets.create",
      "files.assets.update": "files.assets.update",
      "files.assets.delete": "files.assets.delete",
      "files.rename": "files.assets.update",
      "files.enabled": "files.assets.update",
      "files.bulk-download": "files.assets.read",
      "files.signed-url": "files.assets.read",
    },
    models: {
      FileAsset: {
        read: "files.assets.read",
        create: "files.assets.create",
        update: "files.assets.update",
        delete: "files.assets.delete",
      },
    },
  },
});

export const companyMap = createModuleManifest({
  key: "atlas.company",
  name: "Empresa",
  description:
    "Company profile, address, branding and visual identity management.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Building2",
  color: "#ec4899",
  category: "sistema",
  summary: "Perfil, direccion y marca visual de la empresa",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files" }],
  navigation: [
    {
      label: "Resumen",
      path: "/",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Perfil",
      path: "/company",
      icon: "Building2",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Direccion",
      path: "/company/address",
      icon: "MapPin",
      layout: "main",
      permissionKey: "company.address.read",
    },
    {
      label: "Marca visual",
      path: "/company/branding",
      icon: "Palette",
      layout: "main",
      permissionKey: "company.branding.read",
    },
  ],
  permissions: [
    { key: "company.access", name: "Access Company" },
    { key: "company.profile.read", name: "Read Company Profile" },
    { key: "company.profile.create", name: "Create Company Profile" },
    { key: "company.profile.update", name: "Update Company Profile" },
    { key: "company.profile.delete", name: "Delete Company Profile" },
    { key: "company.address.read", name: "Read Company Address" },
    { key: "company.address.create", name: "Create Company Address" },
    { key: "company.address.update", name: "Update Company Address" },
    { key: "company.address.delete", name: "Delete Company Address" },
    { key: "company.branding.read", name: "Read Company Branding" },
    { key: "company.branding.create", name: "Create Company Branding" },
    { key: "company.branding.update", name: "Update Company Branding" },
    { key: "company.branding.delete", name: "Delete Company Branding" },
  ],
  acl: {
    module: "company.access",
    actions: {
      "company.profile.read": "company.profile.read",
      "company.profile.update": "company.profile.update",
      "company.address.read": "company.address.read",
      "company.address.update": "company.address.update",
      "company.branding.read": "company.branding.read",
      "company.branding.update": "company.branding.update",
    },
    models: {
      Company: {
        read: "company.profile.read",
        create: "company.profile.create",
        update: "company.profile.update",
        delete: "company.profile.delete",
      },
      BrandingConfig: {
        read: "company.branding.read",
        create: "company.branding.create",
        update: "company.branding.update",
        delete: "company.branding.delete",
      },
    },
  },
  exposes: {
    logoUrl: "string",
    primaryColor: "string",
    companyName: "string",
    contactEmail: "string",
    phone: "string",
  },
});

export const atlasLedgerManifest = createModuleManifest({
  key: "atlas.ledger",
  name: "Libro de cuentas",
  version: "0.1.1",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  description: "Registro bancario tipo hoja de calculo: depositos, retiros y saldo corriente.",
  summary: "Cuentas bancarias, registro de movimientos y exportacion.",
  icon: "Landmark",
  color: "#16a34a",
  accentColor: "#15803d",
  initials: "LC",
  fullscreenPaths: ["/accounts/:id", "/accounts/:id/import"],
  dependencies: [{ key: "atlas.core" }],
  permissions: [
    { key: "ledger.accounts.read",       name: "Ver cuentas" },
    { key: "ledger.accounts.create",     name: "Crear cuentas" },
    { key: "ledger.accounts.update",     name: "Editar cuentas" },
    { key: "ledger.accounts.delete",     name: "Desactivar cuentas" },
    { key: "ledger.transactions.read",   name: "Ver movimientos" },
    { key: "ledger.transactions.create", name: "Crear movimientos" },
    { key: "ledger.transactions.update", name: "Editar movimientos" },
    { key: "ledger.transactions.delete", name: "Desactivar movimientos" },
    { key: "ledger.export",              name: "Exportar movimientos" },
    { key: "ledger.import",              name: "Importar movimientos" },
    { key: "ledger.categories.manage",   name: "Gestionar categorias" },
    { key: "ledger.types.manage",        name: "Gestionar tipos de movimiento" },
  ],
  acl: {
    module: "ledger.accounts.read",
    actions: {
      "ledger.accounts.read":       "ledger.accounts.read",
      "ledger.accounts.create":     "ledger.accounts.create",
      "ledger.accounts.update":     "ledger.accounts.update",
      "ledger.accounts.delete":     "ledger.accounts.delete",
      "ledger.transactions.read":   "ledger.transactions.read",
      "ledger.transactions.create": "ledger.transactions.create",
      "ledger.transactions.update": "ledger.transactions.update",
      "ledger.transactions.delete": "ledger.transactions.delete",
      "ledger.export":              "ledger.export",
      "ledger.import":              "ledger.import",
      "ledger.categories.manage":   "ledger.categories.manage",
      "ledger.types.manage":        "ledger.types.manage",
    },
  },
  navigation: [
    {
      label: "Cuentas",
      path: "/app/m/atlas.ledger/accounts",
      icon: "Landmark",
      layout: "main",
      permissionKey: "ledger.accounts.read",
    },
    {
      label: "Categorias",
      path: "/app/m/atlas.ledger/categories",
      icon: "Tag",
      layout: "main",
      permissionKey: "ledger.categories.manage",
    },
    {
      label: "Tipos de mov.",
      path: "/app/m/atlas.ledger/types",
      icon: "SlidersHorizontal",
      layout: "main",
      permissionKey: "ledger.types.manage",
    },
  ],
});

export const coreModules = [
  atlasCoreMap,
  identityMap,
  filesMap,
  companyMap,
  contactsMap,
  hrMap,
  atlasFleetManifest,
  atlasLedgerManifest,
];
