import { createModuleManifest, MODULE_KINDS } from "@atlas/core";
import {
  contactsMap,
  hrMap,
  atlasWebsiteManifest,
  atlasGrowthManifest,
  atlasDocumentsManifest,
  activityMap,
  notificationsMap,
  projectsMap,
  chatMap,
} from "./feature-modules.js";

export const atlasCoreMap = createModuleManifest({
  key: "atlas.core",
  name: "Atlas Core",
  description:
    "Nucleo del sistema: modulos, permisos, bitacora y configuracion de instancia.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Layers",
  color: "#0A7BFF",
  pwa: { shortName: "Atlas Core", startPath: "/modules" },
  category: "sistema",
  summary: "Modulos, permisos, bitacora y configuracion del sistema",
  navigation: [
    {
      label: "Modulos",
      path: "/modules",
      icon: "Puzzle",
      layout: "main",
      permissionKey: "core.modules.read",
    },
    {
      label: "Configuracion",
      path: "/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "core.instance.read",
    },
  ],
  permissions: [
    { key: "platform.erp.access", name: "Access Atlas ERP" },
    { key: "platform.settings.manage", name: "Manage Platform Settings" },
    { key: "core.access", name: "Access Core" },
    { key: "core.modules.read", name: "Read Core Modules" },
    { key: "core.modules.create", name: "Install Core Modules" },
    { key: "core.modules.update", name: "Enable or Disable Core Modules" },
    { key: "core.modules.delete", name: "Uninstall Core Modules" },
    { key: "core.modules.upload", name: "Upload Custom Module ZIP" },
    { key: "core.modules.purge", name: "Purge Custom Module from Server" },
    { key: "core.instance.read", name: "Read Core Instance" },
    { key: "core.instance.create", name: "Create Core Instance Config" },
    { key: "core.instance.update", name: "Update Core Instance Config" },
    { key: "core.instance.delete", name: "Delete Core Instance Config" },
    { key: "core.read", name: "Read Core" },
    { key: "core.manage", name: "Manage Core" },
    { key: "audit.read", name: "Read Audit Logs" },
  ],
  acl: {
    module: "core.access",
    actions: {
      "modules.catalog.read": "core.modules.read",
      "instance.config.read": "core.instance.read",
      "instance.config.update": "core.instance.update",
    },
    models: {
      AtlasModule: {
        read: "core.modules.read",
        create: "core.modules.create",
        update: "core.modules.update",
        delete: "core.modules.delete",
      },
    },
  },
  blueprints: [
    {
      key: "atlas.module.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "AtlasModule",
        label: "Modulo",
        fields: [
          { name: "key", label: "Clave", type: "text", required: true },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "version", label: "Version", type: "text", required: true },
          {
            name: "kind",
            label: "Tipo",
            type: "select",
            options: ["CORE", "FEATURE", "INTEGRATION", "WEBSITE"],
          },
          { name: "enabled", label: "Activo", type: "boolean" },
        ],
      },
    },
  ],
});

export const identityMap = createModuleManifest({
  key: "atlas.identity",
  blueprints: [
    {
      key: "identity.user.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "UserProfile",
        label: "Usuario",
        fields: [
          { name: "displayName", label: "Nombre de usuario", type: "text", required: true },
          { name: "firstName",   label: "Nombre",            type: "text" },
          { name: "lastName",    label: "Apellido",          type: "text" },
          { name: "email",       label: "Correo",            type: "email", required: true },
          { name: "phone",       label: "Telefono",          type: "phone" },
          { name: "bio",         label: "Biografia",         type: "textarea" },
          { name: "enabled",     label: "Activo",            type: "boolean" },
        ],
        table: { columns: ["displayName", "email", "phone", "enabled"] },
      },
    },
    {
      key: "identity.role.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Role",
        label: "Rol",
        fields: [
          { name: "key",         label: "Clave",       type: "text",     required: true },
          { name: "name",        label: "Nombre",      type: "text",     required: true },
          { name: "description", label: "Descripcion", type: "textarea" },
          { name: "system",      label: "Sistema",     type: "boolean" },
          { name: "enabled",     label: "Activo",      type: "boolean" },
        ],
        table: { columns: ["key", "name", "system", "enabled"] },
      },
    },
  ],
  name: "Identidad",
  description: "Usuarios, roles, permisos, membresias y control de acceso.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Shield",
  color: "#21C7FF",
  pwa: { shortName: "Identidad", startPath: "/identity/users" },
  category: "sistema",
  summary: "Usuarios, empresas, roles y membresias",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Usuarios",
      path: "/identity/users",
      icon: "Users",
      layout: "main",
      permissionKey: "identity.users.read",
    },
    {
      label: "Roles",
      path: "/identity/roles",
      icon: "Shield",
      layout: "main",
      permissionKey: "identity.roles.read",
    },
  ],
  permissions: [
    { key: "identity.access", name: "Access Identity" },
    { key: "identity.users.read", name: "Read Users" },
    { key: "identity.users.create", name: "Create Users" },
    { key: "identity.users.update", name: "Update Users" },
    { key: "identity.users.delete", name: "Delete Users" },
    { key: "identity.roles.read", name: "Read Identity Roles" },
    { key: "identity.roles.create", name: "Create Identity Roles" },
    { key: "identity.roles.update", name: "Update Identity Roles" },
    { key: "identity.roles.delete", name: "Delete Identity Roles" },
    { key: "identity.permissions.read", name: "Read Identity Permissions" },
    { key: "identity.permissions.create", name: "Create Identity Permissions" },
    { key: "identity.permissions.update", name: "Update Identity Permissions" },
    { key: "identity.permissions.delete", name: "Delete Identity Permissions" },
    { key: "profile.self.read", name: "Read Own Profile" },
    { key: "profile.self.update", name: "Update Own Profile" },
    { key: "profile.avatar.update", name: "Update Own Avatar" },
    { key: "profile.password.update", name: "Update Own Password" },
  ],
  acl: {
    module: "identity.access",
    actions: {
      "identity.users.read": "identity.users.read",
      "identity.users.create": "identity.users.create",
      "identity.users.update": "identity.users.update",
      "identity.users.delete": "identity.users.delete",
      "identity.roles.read": "identity.roles.read",
      "identity.roles.create": "identity.roles.create",
      "identity.roles.update": "identity.roles.update",
      "identity.roles.delete": "identity.roles.delete",
      "identity.permissions.read": "identity.permissions.read",
      "identity.permissions.create": "identity.permissions.create",
      "identity.permissions.update": "identity.permissions.update",
      "identity.permissions.delete": "identity.permissions.delete",
      "profile.self.read": "profile.self.read",
      "profile.self.update": "profile.self.update",
      "profile.avatar.update": "profile.avatar.update",
      "profile.password.update": "profile.password.update",
    },
    models: {
      UserProfile: {
        read: "identity.users.read",
        create: "identity.users.create",
        update: "identity.users.update",
        delete: "identity.users.delete",
      },
      Role: {
        read: "identity.roles.read",
        create: "identity.roles.create",
        update: "identity.roles.update",
        delete: "identity.roles.delete",
      },
      Permission: {
        read: "identity.permissions.read",
        create: "identity.permissions.create",
        update: "identity.permissions.update",
        delete: "identity.permissions.delete",
      },
    },
  },
});

export const filesMap = createModuleManifest({
  key: "atlas.files",
  name: "Archivos",
  description: "Gestion de archivos, carga, almacenamiento y acceso seguro.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "FolderOpen",
  color: "#f59e0b",
  pwa: { shortName: "Archivos", startPath: "/files" },
  category: "sistema",
  summary: "Gestion de archivos y almacenamiento",
  dependencies: [{ key: "atlas.core" }],
  navigation: [
    {
      label: "Archivos",
      path: "/files",
      icon: "FolderOpen",
      layout: "main",
      permissionKey: "files.assets.read",
    },
  ],
  permissions: [
    { key: "files.access", name: "Access Files" },
    { key: "files.assets.read", name: "Read File Assets" },
    { key: "files.assets.create", name: "Create File Assets" },
    { key: "files.assets.update", name: "Update File Assets" },
    { key: "files.assets.delete", name: "Delete File Assets" },
  ],
  acl: {
    module: "files.access",
    actions: {
      "files.assets.read": "files.assets.read",
      "files.assets.create": "files.assets.create",
      "files.assets.update": "files.assets.update",
      "files.assets.delete": "files.assets.delete",
      "files.rename": "files.assets.update",
      "files.enabled": "files.assets.update",
      "files.bulk-download": "files.assets.read",
      "files.signed-url": "files.assets.read",
    },
    models: {
      FileAsset: {
        read: "files.assets.read",
        create: "files.assets.create",
        update: "files.assets.update",
        delete: "files.assets.delete",
      },
    },
  },
  blueprints: [
    {
      key: "files.asset.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "FileAsset",
        label: "Archivo",
        fields: [
          { name: "originalName", label: "Nombre",      type: "text" },
          { name: "mimeType",     label: "Tipo MIME",   type: "text" },
          { name: "sizeBytes",    label: "Tamano",      type: "number" },
          { name: "bucket",       label: "Bucket",      type: "text" },
          { name: "visibility",   label: "Visibilidad", type: "select", options: ["PRIVATE", "PUBLIC"] },
          { name: "entityType",   label: "Entidad",     type: "text" },
          { name: "enabled",      label: "Activo",      type: "boolean" },
        ],
        table: { columns: ["originalName", "mimeType", "sizeBytes", "visibility", "enabled"] },
      },
    },
  ],
});

export const companyMap = createModuleManifest({
  key: "atlas.company",
  name: "Empresa",
  description:
    "Perfil de empresa, direccion, marca visual e identidad corporativa.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Building2",
  color: "#ec4899",
  pwa: { shortName: "Empresa", startPath: "/" },
  category: "sistema",
  summary: "Perfil, direccion y marca visual de la empresa",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files" }],
  navigation: [
    {
      label: "Resumen",
      path: "/",
      icon: "LayoutDashboard",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Perfil",
      path: "/company",
      icon: "Building2",
      layout: "main",
      permissionKey: "company.profile.read",
    },
    {
      label: "Direccion",
      path: "/company/address",
      icon: "MapPin",
      layout: "main",
      permissionKey: "company.address.read",
    },
    {
      label: "Marca visual",
      path: "/company/branding",
      icon: "Palette",
      layout: "main",
      permissionKey: "company.branding.read",
    },
  ],
  permissions: [
    { key: "company.access", name: "Access Company" },
    { key: "company.profile.read", name: "Read Company Profile" },
    { key: "company.profile.create", name: "Create Company Profile" },
    { key: "company.profile.update", name: "Update Company Profile" },
    { key: "company.profile.delete", name: "Delete Company Profile" },
    { key: "company.address.read", name: "Read Company Address" },
    { key: "company.address.create", name: "Create Company Address" },
    { key: "company.address.update", name: "Update Company Address" },
    { key: "company.address.delete", name: "Delete Company Address" },
    { key: "company.branding.read", name: "Read Company Branding" },
    { key: "company.branding.create", name: "Create Company Branding" },
    { key: "company.branding.update", name: "Update Company Branding" },
    { key: "company.branding.delete", name: "Delete Company Branding" },
  ],
  acl: {
    module: "company.access",
    actions: {
      "company.profile.read": "company.profile.read",
      "company.profile.update": "company.profile.update",
      "company.address.read": "company.address.read",
      "company.address.update": "company.address.update",
      "company.branding.read": "company.branding.read",
      "company.branding.update": "company.branding.update",
    },
    models: {
      Company: {
        read: "company.profile.read",
        create: "company.profile.create",
        update: "company.profile.update",
        delete: "company.profile.delete",
      },
      BrandingConfig: {
        read: "company.branding.read",
        create: "company.branding.create",
        update: "company.branding.update",
        delete: "company.branding.delete",
      },
    },
  },
  exposes: {
    logoUrl: "string",
    primaryColor: "string",
    companyName: "string",
    contactEmail: "string",
    phone: "string",
  },
  blueprints: [
    {
      key: "company.profile.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Company",
        label: "Empresa",
        fields: [
          { name: "name",         label: "Nombre",         type: "text",  required: true },
          { name: "legalName",    label: "Nombre legal",   type: "text" },
          { name: "rfc",          label: "RFC",            type: "text" },
          { name: "contactEmail", label: "Correo",         type: "email" },
          { name: "phone",        label: "Telefono",       type: "phone" },
          { name: "website",      label: "Sitio web",      type: "url" },
          { name: "country",      label: "Pais",           type: "text" },
          { name: "state",        label: "Estado",         type: "text" },
          { name: "city",         label: "Ciudad",         type: "text" },
          { name: "postalCode",   label: "Codigo postal",  type: "text" },
        ],
        table: { columns: ["name", "rfc", "contactEmail", "phone"] },
      },
    },
    {
      key: "company.branding.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "BrandingConfig",
        label: "Marca visual",
        fields: [
          { name: "primaryColor", label: "Color primario", type: "color", required: true },
          { name: "logoFileId",   label: "Logo",           type: "file" },
        ],
      },
    },
  ],
});

export const atlasLedgerManifest = createModuleManifest({
  key: "atlas.ledger",
  name: "Libro de cuentas",
  version: "0.1.3",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  description:
    "Registro bancario tipo hoja de calculo: depositos, retiros y saldo corriente.",
  summary: "Cuentas bancarias, registro de movimientos y exportacion.",
  icon: "Landmark",
  color: "#16a34a",
  pwa: { shortName: "Cuentas", startPath: "/accounts" },
  accentColor: "#15803d",
  initials: "LC",
  fullscreenPaths: ["/accounts/:id", "/accounts/:id/import"],
  dependencies: [{ key: "atlas.core" }],
  permissions: [
    { key: "ledger.accounts.read", name: "Ver cuentas" },
    { key: "ledger.accounts.create", name: "Crear cuentas" },
    { key: "ledger.accounts.update", name: "Editar cuentas" },
    { key: "ledger.accounts.delete", name: "Desactivar cuentas" },
    { key: "ledger.transactions.read", name: "Ver movimientos" },
    { key: "ledger.transactions.create", name: "Crear movimientos" },
    { key: "ledger.transactions.update", name: "Editar movimientos" },
    { key: "ledger.transactions.delete", name: "Desactivar movimientos" },
    { key: "ledger.export", name: "Exportar movimientos" },
    { key: "ledger.import", name: "Importar movimientos" },
    { key: "ledger.categories.manage", name: "Gestionar categorias" },
    { key: "ledger.types.manage", name: "Gestionar tipos de movimiento" },
    { key: "ledger.groups.read",   name: "Ver grupos" },
    { key: "ledger.groups.write",  name: "Gestionar grupos" },
    { key: "ledger.members.write", name: "Gestionar colaboradores" },
  ],
  acl: {
    module: "ledger.accounts.read",
    actions: {
      "ledger.accounts.read": "ledger.accounts.read",
      "ledger.accounts.create": "ledger.accounts.create",
      "ledger.accounts.update": "ledger.accounts.update",
      "ledger.accounts.delete": "ledger.accounts.delete",
      "ledger.transactions.read": "ledger.transactions.read",
      "ledger.transactions.create": "ledger.transactions.create",
      "ledger.transactions.update": "ledger.transactions.update",
      "ledger.transactions.delete": "ledger.transactions.delete",
      "ledger.export": "ledger.export",
      "ledger.import": "ledger.import",
      "ledger.categories.manage": "ledger.categories.manage",
      "ledger.types.manage": "ledger.types.manage",
      "ledger.groups.read":   "ledger.groups.read",
      "ledger.groups.write":  "ledger.groups.write",
      "ledger.members.write": "ledger.members.write",
    },
  },
  blueprints: [
    {
      key: "ledger.account.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "LedgerAccount",
        label: "Cuenta bancaria",
        fields: [
          { name: "name",           label: "Nombre",          type: "text",   required: true },
          { name: "bank",           label: "Banco",           type: "text",   required: true },
          { name: "accountNumber",  label: "No. de cuenta",   type: "text" },
          { name: "currency",       label: "Moneda",          type: "text" },
          { name: "openingBalance", label: "Saldo inicial",   type: "currency" },
          { name: "enabled",        label: "Activo",          type: "boolean" },
        ],
        table: { columns: ["name", "bank", "accountNumber", "currency", "openingBalance"] },
      },
    },
    {
      key: "ledger.transaction.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "LedgerTransaction",
        label: "Movimiento",
        fields: [
          { name: "nombre",     label: "Descripcion",  type: "text",     required: true },
          { name: "fecha",      label: "Fecha",        type: "date",     required: true },
          { name: "deposito",   label: "Deposito",     type: "currency" },
          { name: "retiro",     label: "Retiro",       type: "currency" },
          { name: "referencia", label: "Referencia",   type: "text" },
          { name: "concepto",   label: "Concepto",     type: "text" },
          { name: "enabled",    label: "Activo",       type: "boolean" },
        ],
        table: { columns: ["fecha", "nombre", "referencia", "deposito", "retiro"] },
      },
    },
  ],
  navigation: [
    {
      label: "Cuentas",
      path: "/app/m/atlas.ledger/accounts",
      icon: "Landmark",
      layout: "main",
      permissionKey: "ledger.accounts.read",
    },
    {
      label: "Grupos",
      path: "/app/m/atlas.ledger/groups",
      icon: "FolderOpen",
      layout: "main",
      permissionKey: "ledger.groups.read",
    },
    {
      label: "Categorias",
      path: "/app/m/atlas.ledger/categories",
      icon: "Tag",
      layout: "main",
      permissionKey: "ledger.categories.manage",
    },
  ],
});

export const atlasFleetManifest = createModuleManifest({
  key: "atlas.fleet",
  name: "Flota",
  version: "0.5.1",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  description:
    "Gestion de flota vehicular: vehiculos, reportes y asignacion de conductores.",
  summary: "Vehiculos, conductores, reportes y control operativo.",
  icon: "Gauge",
  color: "#14B8A6",
  pwa: { shortName: "Flota", startPath: "/vehicles" },
  accentColor: "#0F766E",
  initials: "FL",
  dependencies: [{ key: "atlas.core" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedModels: [
      "fleet.vehicle",
      "fleet.driver",
      "fleet.vehicle_type",
      "fleet.vehicle_brand",
      "fleet.vehicle_document",
      "fleet.driver_document",
      "fleet.vehicle_model",
      "fleet.report",
      "fleet.report_part",
      "fleet.report_document",
      "fleet.insurance_policy",
    ],
    ownedTables: [
      "fleet_vehicle",
      "fleet_driver",
      "fleet_vehicle_type",
      "fleet_vehicle_brand",
      "fleet_vehicle_document",
      "fleet_driver_document",
      "fleet_vehicle_model",
      "fleet_report",
      "fleet_report_part",
      "fleet_report_document",
      "fleet_insurance_policy",
    ],
    ownedEntities: ["Vehicle"],
    sharedEntities: ["Company", "AuditLog"],
  },
  permissions: [
    { key: "fleet.access", name: "Acceso a Flota" },
    { key: "fleet.vehicles.read", name: "Ver vehiculos" },
    { key: "fleet.vehicles.create", name: "Crear vehiculos" },
    { key: "fleet.vehicles.update", name: "Editar vehiculos" },
    { key: "fleet.vehicles.delete", name: "Desactivar vehiculos" },
    { key: "fleet.reports.read", name: "Ver reportes" },
    { key: "fleet.reports.create", name: "Crear reportes" },
    { key: "fleet.reports.update", name: "Editar reportes" },
    { key: "fleet.reports.delete", name: "Eliminar reportes" },
    { key: "fleet.drivers.read", name: "Ver choferes" },
    { key: "fleet.drivers.create", name: "Crear choferes" },
    { key: "fleet.drivers.update", name: "Editar choferes" },
    { key: "fleet.drivers.delete", name: "Desactivar choferes" },
    { key: "fleet.catalogs.read", name: "Ver catalogos de flota" },
    { key: "fleet.catalogs.create", name: "Crear catalogos de flota" },
    { key: "fleet.catalogs.update", name: "Editar catalogos de flota" },
    { key: "fleet.catalogs.delete", name: "Desactivar catalogos de flota" },
    { key: "fleet.insurance.read", name: "Ver polizas de seguro" },
    { key: "fleet.insurance.create", name: "Crear polizas de seguro" },
    { key: "fleet.insurance.update", name: "Editar polizas de seguro" },
    { key: "fleet.insurance.delete", name: "Desactivar polizas de seguro" },
  ],
  acl: {
    module: "fleet.access",
    actions: {
      "fleet.vehicles.read": "fleet.vehicles.read",
      "fleet.vehicles.create": "fleet.vehicles.create",
      "fleet.vehicles.update": "fleet.vehicles.update",
      "fleet.vehicles.delete": "fleet.vehicles.delete",
      "fleet.reports.read": "fleet.reports.read",
      "fleet.reports.create": "fleet.reports.create",
      "fleet.reports.update": "fleet.reports.update",
      "fleet.reports.delete": "fleet.reports.delete",
      "fleet.drivers.read": "fleet.drivers.read",
      "fleet.drivers.create": "fleet.drivers.create",
      "fleet.drivers.update": "fleet.drivers.update",
      "fleet.drivers.delete": "fleet.drivers.delete",
      "fleet.catalogs.read": "fleet.catalogs.read",
      "fleet.catalogs.create": "fleet.catalogs.create",
      "fleet.catalogs.update": "fleet.catalogs.update",
      "fleet.catalogs.delete": "fleet.catalogs.delete",
      "fleet.insurance.read": "fleet.insurance.read",
      "fleet.insurance.create": "fleet.insurance.create",
      "fleet.insurance.update": "fleet.insurance.update",
      "fleet.insurance.delete": "fleet.insurance.delete",
    },
    models: {
      Vehicle: {
        read: "fleet.vehicles.read",
        create: "fleet.vehicles.create",
        update: "fleet.vehicles.update",
        delete: "fleet.vehicles.delete",
      },
      Report: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      ReportPart: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      ReportDocument: {
        read: "fleet.reports.read",
        create: "fleet.reports.create",
        update: "fleet.reports.update",
        delete: "fleet.reports.delete",
      },
      Driver: {
        read: "fleet.drivers.read",
        create: "fleet.drivers.create",
        update: "fleet.drivers.update",
        delete: "fleet.drivers.delete",
      },
      VehicleType: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      VehicleBrand: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      VehicleDocument: {
        read: "fleet.vehicles.read",
        create: "fleet.vehicles.create",
        update: "fleet.vehicles.update",
        delete: "fleet.vehicles.delete",
      },
      DriverDocument: {
        read: "fleet.drivers.read",
        create: "fleet.drivers.create",
        update: "fleet.drivers.update",
        delete: "fleet.drivers.delete",
      },
      VehicleModel: {
        read: "fleet.catalogs.read",
        create: "fleet.catalogs.create",
        update: "fleet.catalogs.update",
        delete: "fleet.catalogs.delete",
      },
      InsurancePolicy: {
        read: "fleet.insurance.read",
        create: "fleet.insurance.create",
        update: "fleet.insurance.update",
        delete: "fleet.insurance.delete",
      },
    },
  },
  blueprints: [
    {
      key: "fleet.vehicle.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "FleetVehicle",
        label: "Vehiculo",
        fields: [
          { name: "plate",         label: "Placas",       type: "text",   required: true },
          { name: "brand",         label: "Marca",        type: "text" },
          { name: "modelName",     label: "Modelo",       type: "text" },
          { name: "year",          label: "Anio",         type: "number" },
          { name: "color",         label: "Color",        type: "color" },
          { name: "status",        label: "Estado",       type: "select", options: ["active", "inactive", "maintenance"] },
          { name: "economicGroupNumber",      label: "No. economico grupo",      type: "text" },
          { name: "economicIndividualNumber", label: "No. economico individual", type: "text" },
          { name: "notes",         label: "Notas",        type: "textarea" },
          { name: "enabled",       label: "Activo",       type: "boolean" },
        ],
        table: { columns: ["plate", "brand", "modelName", "year", "status"] },
      },
    },
    {
      key: "fleet.driver.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "FleetDriver",
        label: "Chofer",
        fields: [
          { name: "firstName",        label: "Nombre",           type: "text",  required: true },
          { name: "lastName",         label: "Apellido",         type: "text",  required: true },
          { name: "phone",            label: "Telefono",         type: "phone", required: true },
          { name: "email",            label: "Correo",           type: "email" },
          { name: "licenseNumber",    label: "No. de licencia",  type: "text",  required: true },
          { name: "licenseType",      label: "Tipo de licencia", type: "text" },
          { name: "licenseExpiryDate",label: "Vencimiento lic.", type: "date" },
          { name: "status",           label: "Estado",           type: "select", options: ["active", "inactive"] },
          { name: "enabled",          label: "Activo",           type: "boolean" },
        ],
        table: { columns: ["firstName", "lastName", "phone", "licenseNumber", "status"] },
      },
    },
  ],
  navigation: [
    {
      label: "Vehiculos",
      path: "/app/m/atlas.fleet/vehicles",
      icon: "Truck",
      layout: "main",
      permissionKey: "fleet.vehicles.read",
    },
    {
      label: "Seguros",
      path: "/app/m/atlas.fleet/insurance",
      icon: "ShieldCheck",
      layout: "main",
      permissionKey: "fleet.insurance.read",
    },
    {
      label: "Reportes",
      path: "/app/m/atlas.fleet/reports",
      icon: "ClipboardList",
      layout: "main",
      permissionKey: "fleet.reports.read",
      children: [
        {
          label: "Mantenimiento",
          path: "/app/m/atlas.fleet/reports/maintenance",
          permissionKey: "fleet.reports.read",
        },
        {
          label: "Servicio",
          path: "/app/m/atlas.fleet/reports/service",
          permissionKey: "fleet.reports.read",
        },
        {
          label: "Reparacion",
          path: "/app/m/atlas.fleet/reports/repair",
          permissionKey: "fleet.reports.read",
        },
      ],
    },
    {
      label: "Choferes",
      path: "/app/m/atlas.fleet/drivers",
      icon: "UserCheck",
      layout: "main",
      permissionKey: "fleet.drivers.read",
    },
    {
      label: "Catalogos",
      path: "/app/m/atlas.fleet/catalogs",
      icon: "Layers",
      layout: "main",
      permissionKey: "fleet.catalogs.read",
      children: [
        {
          label: "Tipos de vehiculo",
          path: "/app/m/atlas.fleet/catalogs/vehicle-types",
          permissionKey: "fleet.catalogs.read",
        },
        {
          label: "Marcas",
          path: "/app/m/atlas.fleet/catalogs/vehicle-brands",
          permissionKey: "fleet.catalogs.read",
        },
        {
          label: "Modelos",
          path: "/app/m/atlas.fleet/catalogs/vehicle-models",
          permissionKey: "fleet.catalogs.read",
        },
      ],
    },
  ],
});

export const atlasCalendarManifest = createModuleManifest({
  key: "atlas.calendar",
  name: "Calendario",
  description:
    "Calendario personal y compartido con eventos, recordatorios y vistas por dia, semana y mes.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Calendar",
  color: "#7C3AED",
  pwa: { shortName: "Calendario", startPath: "/calendar" },
  accentColor: "#6D28D9",
  initials: "CA",
  logoUrl: "/module-logos/atlas-calendar-128.svg",
  category: "sistema",
  summary: "Calendarios personales, eventos y recordatorios",
  fullscreenPaths: ["/calendar"],
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  navigation: [
    {
      label: "Calendario",
      path: "/app/m/atlas.calendar/calendar",
      icon: "Calendar",
      layout: "main",
      permissionKey: "calendar.access",
    },
  ],
  permissions: [
    { key: "calendar.access", name: "Acceso al calendario" },
    { key: "calendar.calendars.read", name: "Ver calendarios" },
    { key: "calendar.calendars.create", name: "Crear calendarios" },
    { key: "calendar.calendars.update", name: "Editar calendarios" },
    { key: "calendar.calendars.delete", name: "Eliminar calendarios" },
    { key: "calendar.events.read", name: "Ver eventos" },
    { key: "calendar.events.create", name: "Crear eventos" },
    { key: "calendar.events.update", name: "Editar eventos" },
    { key: "calendar.events.delete", name: "Eliminar eventos" },
    { key: "calendar.share.manage", name: "Gestionar accesos compartidos" },
  ],
  acl: {
    module: "calendar.access",
    actions: {
      "calendar.calendars.read": "calendar.calendars.read",
      "calendar.calendars.create": "calendar.calendars.create",
      "calendar.calendars.update": "calendar.calendars.update",
      "calendar.calendars.delete": "calendar.calendars.delete",
      "calendar.events.read": "calendar.events.read",
      "calendar.events.create": "calendar.events.create",
      "calendar.events.update": "calendar.events.update",
      "calendar.events.delete": "calendar.events.delete",
      "calendar.share.manage": "calendar.share.manage",
    },
  },
  exposes: {
    "calendar.createEvent": "function",
    "calendar.getEvents": "function",
  },
  consumes: ["atlas.files"],
});

export const atlasCatalogManifest = createModuleManifest({
  key: "atlas.catalog",
  name: "Catalogo",
  description: "Gestiona productos, categorias, variantes e inventario",
  version: "2.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "ShoppingBag",
  color: "#F97316",
  pwa: { shortName: "Catalogo", startPath: "/" },
  accentColor: "#EA580C",
  initials: "CT",
  category: "comercial",
  logoUrl: "/module-logos/atlas-catalog-128.svg",
  summary: "Productos, categorias, variantes e inventario unificados.",
  dependencies: [{ key: "atlas.core" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [
      "CatalogCategory",
      "CatalogProduct",
      "CatalogProductOption",
      "CatalogProductOptionValue",
      "CatalogProductVariant",
      "CatalogStockMovement",
    ],
    ownedTables: [
      "catalog_category",
      "catalog_product",
      "catalog_product_option",
      "catalog_product_option_value",
      "catalog_product_variant",
      "catalog_stock_movement",
    ],
    sharedEntities: ["Company"],
  },
  permissions: [
    { key: "catalog.access",            name: "Acceder al catalogo" },
    { key: "catalog.products.read",     name: "Ver productos" },
    { key: "catalog.products.create",   name: "Crear productos" },
    { key: "catalog.products.update",   name: "Editar productos" },
    { key: "catalog.products.delete",   name: "Eliminar productos" },
    { key: "catalog.categories.read",   name: "Ver categorias" },
    { key: "catalog.categories.create", name: "Crear categorias" },
    { key: "catalog.categories.update", name: "Editar categorias" },
    { key: "catalog.categories.delete", name: "Eliminar categorias" },
    { key: "catalog.inventory.adjust",  name: "Ajustar stock" },
  ],
  acl: {
    module: "catalog.access",
    actions: {
      "catalog.products.read":     "catalog.products.read",
      "catalog.products.create":   "catalog.products.create",
      "catalog.products.update":   "catalog.products.update",
      "catalog.products.delete":   "catalog.products.delete",
      "catalog.categories.read":   "catalog.categories.read",
      "catalog.categories.create": "catalog.categories.create",
      "catalog.categories.update": "catalog.categories.update",
      "catalog.categories.delete": "catalog.categories.delete",
      "catalog.inventory.adjust":  "catalog.inventory.adjust",
    },
    models: {
      CatalogProduct: {
        read:   "catalog.products.read",
        create: "catalog.products.create",
        update: "catalog.products.update",
        delete: "catalog.products.delete",
      },
      CatalogCategory: {
        read:   "catalog.categories.read",
        create: "catalog.categories.create",
        update: "catalog.categories.update",
        delete: "catalog.categories.delete",
      },
    },
  },
  navigation: [
    {
      label: "Productos",
      path: "/app/m/atlas.catalog",
      icon: "ShoppingCart",
      layout: "main",
      permissionKey: "catalog.products.read",
    },
    {
      label: "Categorias",
      path: "/app/m/atlas.catalog/categories",
      icon: "Tag",
      layout: "main",
      permissionKey: "catalog.categories.read",
    },
    {
      label: "Inventario",
      path: "/app/m/atlas.catalog/inventory",
      icon: "BarChart3",
      layout: "main",
      permissionKey: "catalog.products.read",
    },
  ],
  blueprints: [
    {
      key: "catalog.product.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "CatalogProduct",
        label: "Producto",
        fields: [
          { name: "name",         label: "Nombre",          type: "text",     required: true },
          { name: "slug",         label: "Slug",            type: "text",     required: true },
          { name: "sku",          label: "SKU",             type: "text" },
          { name: "barcode",      label: "Codigo de barras",type: "text" },
          { name: "description",  label: "Descripcion",     type: "textarea" },
          { name: "price",        label: "Precio",          type: "currency", required: true },
          { name: "comparePrice", label: "Precio anterior", type: "currency" },
          { name: "currency",     label: "Moneda",          type: "text" },
          { name: "stock",        label: "Stock",           type: "number" },
          { name: "trackStock",   label: "Rastrear stock",  type: "boolean" },
          { name: "productType",  label: "Tipo",            type: "select", options: ["SIMPLE", "VARIABLE"] },
          { name: "published",    label: "Publicado",       type: "boolean" },
        ],
        table: { columns: ["name", "sku", "price", "stock", "published"] },
      },
    },
    {
      key: "catalog.category.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "CatalogCategory",
        label: "Categoria",
        fields: [
          { name: "name",        label: "Nombre",      type: "text", required: true },
          { name: "slug",        label: "Slug",        type: "text", required: true },
          { name: "description", label: "Descripcion", type: "textarea" },
        ],
        table: { columns: ["name", "slug", "description"] },
      },
    },
  ],
});

export const atlasPosManifest = createModuleManifest({
  key: "atlas.pos",
  name: "POS",
  description: "Punto de venta para restaurante, tienda y operaciones hibridas.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Store",
  color: "#008C8C",
  pwa: { shortName: "POS", startPath: "/pos/terminal" },
  accentColor: "#007A7A",
  initials: "POS",
  category: "comercial",
  summary: "Terminal de venta, mesas, comandas, pagos y cierres de caja.",
  fullscreenPaths: [
    "/pos/terminal",
    "/pos/tables",
    "/pos/floor-planner",
    "/pos/stations",
  ],
  dependencies: [
    { key: "atlas.core" },
    { key: "atlas.company" },
    { key: "atlas.identity" },
    { key: "atlas.catalog" },
  ],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: false,
    ownedEntities: [
      "PosSettings",
      "PosOutlet",
      "PosTerminal",
      "PosSession",
      "PosPaymentMethod",
      "PosOrder",
      "PosOrderLine",
      "PosGuestSeat",
      "PosPayment",
      "PosCashMovement",
      "PosFloor",
      "PosFloorZone",
      "PosTable",
      "PosFloorElement",
      "PosKitchenStation",
      "PosKitchenTicket",
      "PosKitchenTicketLine",
      "PosProductConfig",
      "PosReceipt",
      "PosReservation",
    ],
    ownedTables: [
      "pos_settings",
      "pos_outlet",
      "pos_terminal",
      "pos_session",
      "pos_payment_method",
      "pos_order",
      "pos_order_line",
      "pos_guest_seat",
      "pos_payment",
      "pos_cash_movement",
      "pos_floor",
      "pos_floor_zone",
      "pos_table",
      "pos_floor_element",
      "pos_kitchen_station",
      "pos_kitchen_ticket",
      "pos_kitchen_ticket_line",
      "pos_product_config",
      "pos_receipt",
      "pos_reservation",
    ],
    sharedEntities: [
      "Company",
      "UserProfile",
      "CatalogProduct",
      "CatalogProductVariant",
      "AuditLog",
    ],
  },
  permissions: [
    { key: "pos.access", name: "Acceder a POS" },
    { key: "pos.terminal.use", name: "Usar terminal POS" },
    { key: "pos.orders.read", name: "Ver ordenes POS" },
    { key: "pos.orders.create", name: "Crear ordenes POS" },
    { key: "pos.orders.update", name: "Editar ordenes POS" },
    { key: "pos.orders.cancel", name: "Cancelar ordenes POS" },
    { key: "pos.payments.create", name: "Registrar pagos POS" },
    { key: "pos.sessions.read", name: "Ver sesiones de caja" },
    { key: "pos.sessions.manage", name: "Abrir y cerrar cajas" },
    { key: "pos.cash.manage", name: "Registrar movimientos de efectivo" },
    { key: "pos.floor.read", name: "Ver planos POS" },
    { key: "pos.floor.manage", name: "Gestionar planos POS" },
    { key: "pos.stations.read", name: "Ver estaciones de preparacion" },
    { key: "pos.stations.manage", name: "Gestionar estaciones de preparacion" },
    { key: "pos.settings.manage", name: "Gestionar configuracion POS" },
    { key: "pos.external.manage", name: "Gestionar canales externos POS" },
  ],
  acl: {
    module: "pos.access",
    actions: {
      "pos.terminal.use": "pos.terminal.use",
      "pos.orders.read": "pos.orders.read",
      "pos.orders.create": "pos.orders.create",
      "pos.orders.update": "pos.orders.update",
      "pos.orders.cancel": "pos.orders.cancel",
      "pos.payments.create": "pos.payments.create",
      "pos.sessions.read": "pos.sessions.read",
      "pos.sessions.manage": "pos.sessions.manage",
      "pos.cash.manage": "pos.cash.manage",
      "pos.floor.read": "pos.floor.read",
      "pos.floor.manage": "pos.floor.manage",
      "pos.stations.read": "pos.stations.read",
      "pos.stations.manage": "pos.stations.manage",
      "pos.settings.manage": "pos.settings.manage",
      "pos.external.manage": "pos.external.manage",
    },
  },
  navigation: [
    {
      label: "Terminal",
      path: "/app/m/atlas.pos/pos/terminal",
      icon: "BadgeDollarSign",
      layout: "main",
      permissionKey: "pos.terminal.use",
    },
    {
      label: "Mesas",
      path: "/app/m/atlas.pos/pos/tables",
      icon: "Armchair",
      layout: "main",
      permissionKey: "pos.terminal.use",
    },
    {
      label: "Planos",
      path: "/app/m/atlas.pos/pos/floor-planner",
      icon: "LayoutGrid",
      layout: "main",
      permissionKey: "pos.floor.manage",
    },
    {
      label: "Estaciones",
      path: "/app/m/atlas.pos/pos/stations",
      icon: "ChefHat",
      layout: "main",
      permissionKey: "pos.stations.read",
    },
    {
      label: "Ordenes",
      path: "/app/m/atlas.pos/pos/orders",
      icon: "ReceiptText",
      layout: "main",
      permissionKey: "pos.orders.read",
    },
    {
      label: "Cajas",
      path: "/app/m/atlas.pos/pos/sessions",
      icon: "Landmark",
      layout: "main",
      permissionKey: "pos.sessions.read",
    },
    {
      label: "Configuracion",
      path: "/app/m/atlas.pos/pos/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "pos.settings.manage",
    },
  ],
  blueprints: [],
  consumes: ["atlas.files", "atlas.ledger", "atlas.notifications"],
  exposes: [],
});

export const inventoryMap = createModuleManifest({
  key: 'atlas.inventory',
  name: 'Inventario',
  description: 'Gestion de inventario y activos de la empresa',
  version: '1.0.0',
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: 'Boxes',
  color: '#7c3aed',
  pwa: { shortName: 'Inventario', startPath: '/inventory' },
  category: 'operaciones',
  summary: 'Gestion de inventario y activos de la empresa',
  dependencies: [{ key: 'atlas.core' }, { key: 'atlas.hr' }],
  navigation: [
    {
      label: 'Inventario',
      path: '/inventory',
      icon: 'Boxes',
      layout: 'main',
      permissionKey: 'inventory.item.read',
    },
    {
      label: 'Asignaciones',
      path: '/inventory/assignments',
      icon: 'UserCheck',
      layout: 'main',
      permissionKey: 'inventory.assignment.read',
    },
    {
      label: 'Catalogos',
      path: '/inventory/catalogs',
      icon: 'FolderOpen',
      layout: 'main',
      permissionKey: 'inventory.catalog.manage',
    },
  ],
  permissions: [
    { key: 'inventory.access',             name: 'Acceder al modulo de inventario' },
    { key: 'inventory.item.read',          name: 'Ver items del inventario' },
    { key: 'inventory.item.create',        name: 'Crear items de inventario' },
    { key: 'inventory.item.update',        name: 'Editar items de inventario' },
    { key: 'inventory.item.delete',        name: 'Eliminar items de inventario' },
    { key: 'inventory.assignment.read',    name: 'Ver asignaciones de inventario' },
    { key: 'inventory.assignment.manage',  name: 'Gestionar asignaciones de inventario' },
    { key: 'inventory.catalog.read',       name: 'Ver catalogos de inventario' },
    { key: 'inventory.catalog.manage',     name: 'Gestionar catalogos de inventario' },
    { key: 'inventory.customfield.manage', name: 'Gestionar campos personalizados de inventario' },
  ],
  acl: {
    module: 'inventory.access',
    actions: {
      'inventory.item.read':          'inventory.item.read',
      'inventory.item.create':        'inventory.item.create',
      'inventory.item.update':        'inventory.item.update',
      'inventory.item.delete':        'inventory.item.delete',
      'inventory.assignment.read':    'inventory.assignment.read',
      'inventory.assignment.manage':  'inventory.assignment.manage',
      'inventory.catalog.read':       'inventory.catalog.read',
      'inventory.catalog.manage':     'inventory.catalog.manage',
      'inventory.customfield.manage': 'inventory.customfield.manage',
    },
  },
  blueprints: [],
  exposes: [],
  consumes: [],
});

export const notesMap = createModuleManifest({
  key: 'atlas.notes',
  name: 'Notas',
  version: '0.1.0',
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: 'NotebookPen',
  color: '#f59e0b',
  category: 'productividad',
  pwa: { shortName: 'Notas', startPath: '/notes' },
  fullscreenPaths: ['/notes'],
  navigation: [
    {
      label: 'Notas',
      path: '/notes',
      icon: 'NotebookPen',
      layout: 'main',
      permissionKey: 'notes.notes.read',
    },
  ],
  permissions: [
    { key: 'notes.access', name: 'Acceso a notas', description: 'Puede ver el módulo de notas' },
    { key: 'notes.notes.read', name: 'Leer notas', description: 'Puede leer sus propias notas y notas compartidas' },
    { key: 'notes.notes.create', name: 'Crear notas', description: 'Puede crear nuevas notas' },
    { key: 'notes.notes.update', name: 'Editar notas', description: 'Puede editar el contenido de sus notas' },
    { key: 'notes.notes.delete', name: 'Eliminar notas', description: 'Puede mover sus notas a la papelera' },
    { key: 'notes.folders.read', name: 'Ver carpetas', description: 'Puede ver sus carpetas de notas' },
    { key: 'notes.folders.create', name: 'Crear carpetas', description: 'Puede crear carpetas de notas' },
    { key: 'notes.folders.update', name: 'Editar carpetas', description: 'Puede editar sus carpetas de notas' },
    { key: 'notes.folders.delete', name: 'Eliminar carpetas', description: 'Puede eliminar sus carpetas de notas' },
    { key: 'notes.tags.read', name: 'Ver etiquetas', description: 'Puede ver sus etiquetas de notas' },
    { key: 'notes.tags.create', name: 'Crear etiquetas', description: 'Puede crear etiquetas de notas' },
    { key: 'notes.tags.update', name: 'Editar etiquetas', description: 'Puede editar sus etiquetas de notas' },
    { key: 'notes.tags.delete', name: 'Eliminar etiquetas', description: 'Puede eliminar sus etiquetas de notas' },
    { key: 'notes.shares.read', name: 'Ver compartidos', description: 'Puede ver con quién están compartidas sus notas' },
    { key: 'notes.shares.create', name: 'Compartir notas', description: 'Puede compartir notas con otros usuarios' },
    { key: 'notes.shares.update', name: 'Editar acceso compartido', description: 'Puede cambiar permisos de notas compartidas' },
    { key: 'notes.shares.delete', name: 'Revocar acceso compartido', description: 'Puede revocar el acceso a notas compartidas' },
  ],
});

export const coreModules = [
  atlasCoreMap,
  identityMap,
  filesMap,
  companyMap,
  contactsMap,
  hrMap,
  atlasFleetManifest,
  atlasLedgerManifest,
  atlasWebsiteManifest,
  atlasGrowthManifest,
  atlasDocumentsManifest,
  atlasCalendarManifest,
  activityMap,
  notificationsMap,
  atlasCatalogManifest,
  atlasPosManifest,
  projectsMap,
  inventoryMap,
  chatMap,
  notesMap,
];
