import { createModuleManifest, MODULE_KINDS } from "@atlas/core";

export const contactsMap = createModuleManifest({
  key: "atlas.contacts",
  name: "Contactos",
  description: "Clientes, proveedores, personas y empresas.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "ContactRound",
  color: "#0ea5e9",
  category: "operaciones",
  summary: "Clientes, proveedores, personas y empresas",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Contact"],
    sharedEntities: ["Company", "AuditLog"],
  },
  navigation: [
    {
      label: "Contactos",
      path: "/contacts",
      icon: "Contact",
      layout: "main",
      permissionKey: "contacts.contacts.read",
    },
  ],
  permissions: [
    { key: "contacts.access", name: "Access Contacts" },
    { key: "contacts.contacts.read", name: "Read Contacts Feature" },
    { key: "contacts.contacts.create", name: "Create Contacts Feature" },
    { key: "contacts.contacts.update", name: "Update Contacts Feature" },
    { key: "contacts.contacts.delete", name: "Delete Contacts Feature" },
  ],
  exposes: {
    contactPicker: true,
    getContactById: true,
  },
  acl: {
    module: "contacts.access",
    actions: {
      "contacts.contacts.read": "contacts.contacts.read",
      "contacts.contacts.create": "contacts.contacts.create",
      "contacts.contacts.update": "contacts.contacts.update",
      "contacts.contacts.delete": "contacts.contacts.delete",
      "contacts.list": "contacts.contacts.read",
      "contacts.picker": "contacts.contacts.read",
      "contacts.enabled": "contacts.contacts.update",
    },
    models: {
      Contact: {
        read: "contacts.contacts.read",
        create: "contacts.contacts.create",
        update: "contacts.contacts.update",
        delete: "contacts.contacts.delete",
      },
    },
  },
  blueprints: [
    {
      key: "contacts.contact.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "Contact",
        label: "Contacto",
        fields: [
          {
            name: "type",
            label: "Tipo",
            type: "select",
            options: ["customer", "supplier", "person", "company"],
            required: true,
          },
          { name: "name", label: "Nombre", type: "text", required: true },
          { name: "legalName", label: "Nombre legal", type: "text" },
          { name: "email", label: "Correo", type: "email" },
          { name: "phone", label: "Telefono", type: "phone" },
          { name: "taxId", label: "RFC / Tax ID", type: "text" },
          {
            name: "notesMarkdown",
            label: "Observaciones",
            type: "markdown",
            maxLength: 5000,
          },
        ],
        table: { columns: ["type", "name", "email", "phone", "taxId"] },
      },
    },
  ],
});

export const hrMap = createModuleManifest({
  key: "atlas.hr",
  name: "Recursos Humanos",
  description: "Colaboradores, notas internas y expedientes.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "UsersRound",
  color: "#2563eb",
  category: "operaciones",
  summary: "Gestión de personal y expediente",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.files", optional: true }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["HrEmployee", "HrDepartment", "HrJobTitle"],
    sharedEntities: ["Company", "UserProfile", "FileAsset", "AuditLog"],
  },
  navigation: [
    {
      label: "Colaboradores",
      path: "/hr/employees",
      icon: "Users",
      layout: "main",
      permissionKey: "hr.employee.read",
    },
    {
      label: "Organigrama",
      path: "/hr/org-chart",
      icon: "Network",
      layout: "main",
      permissionKey: "hr.org_chart.read",
    },
    {
      label: "Catálogos",
      path: "/hr/catalogs",
      icon: "BookOpen",
      layout: "main",
      permissionKey: "hr.department.read",
    },
  ],
  permissions: [
    { key: "hr.access", name: "Access HR" },
    { key: "hr.employee.read", name: "Read HR Employees" },
    { key: "hr.employee.create", name: "Create HR Employees" },
    { key: "hr.employee.update", name: "Update HR Employees" },
    { key: "hr.employee.delete", name: "Delete HR Employees" },
    { key: "hr.department.read", name: "Read HR Departments" },
    { key: "hr.department.create", name: "Create HR Departments" },
    { key: "hr.department.update", name: "Update HR Departments" },
    { key: "hr.department.delete", name: "Delete HR Departments" },
    { key: "hr.job_title.read", name: "Read HR Job Titles" },
    { key: "hr.job_title.create", name: "Create HR Job Titles" },
    { key: "hr.job_title.update", name: "Update HR Job Titles" },
    { key: "hr.job_title.delete", name: "Delete HR Job Titles" },
    { key: "hr.org_chart.read", name: "Read HR Org Chart" },
    { key: "hr.org_chart.create", name: "Create HR Org Chart" },
    { key: "hr.org_chart.update", name: "Update HR Org Chart" },
    { key: "hr.org_chart.delete", name: "Delete HR Org Chart" },
  ],
  acl: {
    module: "hr.access",
    actions: {
      "hr.employee.read": "hr.employee.read",
      "hr.employee.create": "hr.employee.create",
      "hr.employee.update": "hr.employee.update",
      "hr.employee.delete": "hr.employee.delete",
      "hr.employee.enable": "hr.employee.update",
      "hr.employee.disable": "hr.employee.update",
      "hr.employee.file.attach": "hr.employee.update",
      "hr.employee.file.delete": "hr.employee.update",
      "hr.department.read": "hr.department.read",
      "hr.department.create": "hr.department.create",
      "hr.department.update": "hr.department.update",
      "hr.department.delete": "hr.department.delete",
      "hr.job_title.read": "hr.job_title.read",
      "hr.job_title.create": "hr.job_title.create",
      "hr.job_title.update": "hr.job_title.update",
      "hr.job_title.delete": "hr.job_title.delete",
      "hr.org_chart.read": "hr.org_chart.read",
      "hr.org_chart.create": "hr.org_chart.create",
      "hr.org_chart.update": "hr.org_chart.update",
      "hr.org_chart.delete": "hr.org_chart.delete",
    },
    models: {
      HrEmployee: {
        read: "hr.employee.read",
        create: "hr.employee.create",
        update: "hr.employee.update",
        delete: "hr.employee.delete",
      },
      HrDepartment: {
        read: "hr.department.read",
        create: "hr.department.create",
        update: "hr.department.update",
        delete: "hr.department.delete",
      },
      HrJobTitle: {
        read: "hr.job_title.read",
        create: "hr.job_title.create",
        update: "hr.job_title.update",
        delete: "hr.job_title.delete",
      },
    },
  },
  blueprints: [
    {
      key: "hr.employee.entity",
      kind: "ENTITY",
      version: "0.1.0",
      schema: {
        entity: "HrEmployee",
        label: "Colaborador",
        fields: [
          { name: "employeeCode", label: "Codigo", type: "text" },
          { name: "userProfileId", label: "Cuenta de usuario", type: "text" },
          { name: "firstName", label: "Nombre", type: "text", required: true },
          {
            name: "lastName",
            label: "Apellidos",
            type: "text",
            required: true,
          },
          { name: "workEmail", label: "Correo laboral", type: "email" },
          { name: "personalEmail", label: "Correo personal", type: "email" },
          { name: "phone", label: "Teléfono", type: "phone" },
          {
            name: "emergencyContactName",
            label: "Contacto de emergencia",
            type: "text",
          },
          {
            name: "emergencyContactPhone",
            label: "Telefono de emergencia",
            type: "phone",
          },
          { name: "jobTitle", label: "Puesto", type: "text" },
          { name: "department", label: "Departamento", type: "text" },
          { name: "managerName", label: "Supervisor", type: "text" },
          {
            name: "employmentType",
            label: "Tipo de empleo",
            type: "select",
            options: ["full_time", "part_time", "contractor", "intern"],
          },
          { name: "workLocation", label: "Ubicacion de trabajo", type: "text" },
          { name: "terminationDate", label: "Fecha de baja", type: "text" },
          {
            name: "status",
            label: "Estado",
            type: "select",
            options: ["active", "inactive", "vacation", "terminated"],
            required: true,
          },
          { name: "notesMarkdown", label: "Notas", type: "markdown" },
        ],
      },
    },
  ],
});

export const atlasWebsiteManifest = createModuleManifest({
  key: "atlas.website",
  name: "Sitio web",
  description:
    "Sitio web publico, editor visual de paginas y publicacion de contenido.",
  version: "0.2.0",
  kind: MODULE_KINDS.WEBSITE,
  core: true,
  uninstallable: false,
  icon: "Globe",
  color: "#6366f1",
  summary: "CMS, editor Puck y publicacion de paginas.",
  dependencies: [{ key: "atlas.core" }],
  lifecycle: {
    installable: true,
    uninstallable: true,
    resettable: true,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: [],
    sharedEntities: ["Company", "AuditLog"],
  },
  permissions: [
    { key: "website.access", name: "Acceso al Sitio web" },
    { key: "website.site.read", name: "Ver configuracion del sitio" },
    { key: "website.site.update", name: "Editar configuracion del sitio" },
    { key: "website.pages.read", name: "Ver paginas" },
    { key: "website.pages.create", name: "Crear paginas" },
    { key: "website.pages.update", name: "Editar paginas" },
    { key: "website.pages.publish", name: "Publicar paginas" },
    { key: "website.pages.delete", name: "Eliminar paginas" },
    { key: "website.theme.read", name: "Ver temas" },
    { key: "website.theme.update", name: "Editar temas" },
    { key: "website.menus.read", name: "Ver menus" },
    { key: "website.menus.update", name: "Editar menus" },
  ],
  acl: {
    module: "website.access",
    actions: {
      "website.site.read": "website.site.read",
      "website.site.update": "website.site.update",
      "website.pages.read": "website.pages.read",
      "website.pages.create": "website.pages.create",
      "website.pages.update": "website.pages.update",
      "website.pages.publish": "website.pages.publish",
      "website.pages.delete": "website.pages.delete",
      "website.theme.read": "website.theme.read",
      "website.theme.update": "website.theme.update",
      "website.menus.read": "website.menus.read",
      "website.menus.update": "website.menus.update",
    },
  },
  navigation: [
    {
      label: "Sitio web",
      path: "/app/m/atlas.website",
      icon: "Globe",
      layout: "main",
      permissionKey: "website.access",
    },
    {
      label: "Paginas",
      path: "/app/m/atlas.website/pages",
      icon: "FileText",
      layout: "main",
      permissionKey: "website.pages.read",
    },
    {
      label: "Plantillas",
      path: "/app/m/atlas.website/templates",
      icon: "LayoutTemplate",
      layout: "main",
      permissionKey: "website.pages.create",
    },
    {
      label: "Blog",
      path: "/app/m/atlas.website/blog",
      icon: "BookOpen",
      layout: "main",
      permissionKey: "website.pages.read",
    },
    {
      label: "Formularios",
      path: "/app/m/atlas.website/forms",
      icon: "FormInput",
      layout: "main",
      permissionKey: "website.pages.read",
    },
    {
      label: "Tema",
      path: "/app/m/atlas.website/theme",
      icon: "Palette",
      layout: "main",
      permissionKey: "website.theme.read",
    },
    {
      label: "Pagos",
      path: "/app/m/atlas.website/payments",
      icon: "CreditCard",
      layout: "main",
      permissionKey: "website.site.update",
    },
    {
      label: "Configuracion",
      path: "/app/m/atlas.website/settings",
      icon: "Settings",
      layout: "main",
      permissionKey: "website.site.update",
    },
  ],
});

export const featureModules = [];

export const activityMap = createModuleManifest({
  key: "atlas.activity",
  name: "Actividad",
  description: "Bitácora legible de eventos y feed transversal de Atlas ERP.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Activity",
  color: "#6366f1",
  category: "plataforma",
  summary: "Feed de actividad de negocio en tiempo real",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Activity"],
    sharedEntities: ["UserProfile", "Company"],
  },
  navigation: [
    {
      label: "Actividad",
      path: "/",
      icon: "Activity",
      layout: "main",
      permissionKey: "activity.read",
    },
  ],
  permissions: [
    { key: "activity.access", name: "Acceder al módulo de actividad" },
    { key: "activity.read", name: "Ver actividad" },
    { key: "activity.publish", name: "Publicar actividad" },
    { key: "activity.manage", name: "Administrar actividad" },
  ],
  exposes: {
    publishActivity: "function",
    logAndPublish: "function",
  },
  acl: {
    module: "activity.access",
    actions: {
      "activity.read": "activity.read",
      "activity.publish": "activity.publish",
      "activity.manage": "activity.manage",
      "activity.list": "activity.read",
      "activity.recent": "activity.read",
      "activity.entity": "activity.read",
    },
    models: {
      Activity: {
        read: "activity.read",
        create: "activity.publish",
        update: "activity.manage",
        delete: "activity.manage",
      },
    },
  },
  blueprints: [],
});

export const notificationsMap = createModuleManifest({
  key: "atlas.notifications",
  name: "Notificaciones",
  description: "Alertas accionables para eventos importantes del sistema.",
  version: "0.1.0",
  kind: MODULE_KINDS.CORE,
  core: true,
  uninstallable: false,
  icon: "Bell",
  color: "#0ea5e9",
  category: "plataforma",
  summary: "Inbox de notificaciones con prioridades y canales",
  dependencies: [{ key: "atlas.core" }, { key: "atlas.identity" }],
  lifecycle: {
    installable: true,
    uninstallable: false,
    resettable: false,
    supportsDataPurge: true,
    defaultUninstallPolicy: "purge-owned-tables",
    ownedEntities: ["Notification"],
    sharedEntities: ["UserProfile", "Company", "Activity"],
  },
  navigation: [
    {
      label: "Notificaciones",
      path: "/app/m/atlas.notifications",
      icon: "Bell",
      layout: "main",
      permissionKey: "notifications.read",
    },
  ],
  permissions: [
    { key: "notifications.access", name: "Acceder a notificaciones" },
    { key: "notifications.read", name: "Ver notificaciones" },
    { key: "notifications.publish", name: "Publicar notificaciones" },
    { key: "notifications.manage", name: "Administrar notificaciones" },
  ],
  acl: {
    module: "notifications.access",
    actions: {
      "notifications.read": "notifications.read",
      "notifications.publish": "notifications.publish",
      "notifications.manage": "notifications.manage",
      "notifications.list": "notifications.read",
      "notifications.markRead": "notifications.read",
      "notifications.markAllRead": "notifications.read",
      "notifications.preferences.read": "notifications.read",
      "notifications.preferences.update": "notifications.read",
      "notifications.push.subscribe": "notifications.read",
      "notifications.push.unsubscribe": "notifications.read",
    },
    models: {
      Notification: {
        read: "notifications.read",
        create: "notifications.publish",
        update: "notifications.manage",
        delete: "notifications.manage",
      },
      NotificationDelivery: {
        read: "notifications.read",
        create: "notifications.publish",
        update: "notifications.manage",
        delete: "notifications.manage",
      },
      NotificationPreference: {
        read: "notifications.read",
        create: "notifications.read",
        update: "notifications.read",
        delete: "notifications.manage",
      },
      PushSubscription: {
        read: "notifications.read",
        create: "notifications.read",
        update: "notifications.read",
        delete: "notifications.read",
      },
    },
  },
  blueprints: [],
});
