import { defineTemplate } from '@raulbellosom/atlas-web-builder'

export const agenciaTemplate = defineTemplate({
  id: 'atlas-agencia',
  label: 'Agencia & Portafolio',
  description: 'Plantilla bold y profesional para agencias creativas, estudios de diseño y portafolios.',
  category: 'agencia',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'services', 'stats', 'gallery', 'features', 'team', 'testimonials', 'contact', 'footer'],
      blocks: {
        navbar: {
          id: 'navbar',
          type: 'NavbarBlock',
          props: {
            variant: 'dark',
            brand: 'Nexus Studio',
            links: 'Inicio | /\nServicios | #servicios\nPortafolio | #portafolio\nEquipo | #equipo\nContacto | #contacto',
            ctaLabel: 'Hablemos',
            ctaHref: '#contacto',
            ctaVariant: 'solid',
            sticky: true,
            height: '68',
          },
          children: {},
        },
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Creamos experiencias digitales que transforman negocios',
            subtitle: 'Agencia creativa especializada en branding, diseño web y estrategia digital. Transformamos tus ideas en resultados medibles.',
            eyebrow: 'Agencia creativa',
            ctaLabel: 'Ver portafolio',
            ctaHref: '#portafolio',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Hablemos de tu proyecto',
            ctaSecondHref: '#contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '16',
            minHeight: '88vh',
            titleSize: '3xl',
            contentMaxWidth: '70ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Nuestras especialidades',
            title: 'Lo que hacemos mejor',
            subtitle: 'Combinamos estrategia, diseño y tecnología para crear soluciones digitales que impulsan tu negocio.',
            columns: '3',
            services: 'Branding & Identidad\nCreamos marcas memorables con personalidad propia. Desde la estrategia hasta el manual de identidad completo.\n---\nDiseño Web\nSitios web modernos, rápidos y optimizados para convertir visitantes en clientes. Mobile-first siempre.\n---\nMarketing Digital\nEstrategias 360° que combinan SEO, redes sociales y publicidad pagada para maximizar tu alcance.\n---\nDiseño UX/UI\nInterfases intuitivas y atractivas que mejoran la experiencia del usuario y aumentan la conversión.\n---\nDesarrollo a Medida\nAplicaciones web y móviles construidas con las tecnologías más modernas del mercado.\n---\nConsultoría Estratégica\nAnálisis profundo de tu negocio digital con recomendaciones accionables y medibles.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: '',
            title: '',
            stats: '200+\nProyectos entregados\nEn 5 años\n---\n50+\nClientes activos\nEn 8 países\n---\n98%\nTasa de retención\nClientes satisfechos\n---\n15\nPremios ganados\nReconocimientos internacionales',
            background: 'dark',
            align: 'center',
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Portafolio selecto',
            title: 'Proyectos que hablan por sí solos',
            subtitle: 'Una muestra de nuestro trabajo más reciente.',
            columns: '3',
            gap: 'normal',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Nuestra metodología',
            title: 'Cómo trabajamos contigo',
            subtitle: 'Un proceso claro, transparente y orientado a resultados en cada etapa.',
            layout: 'grid-3',
            iconStyle: 'number',
            background: 'muted',
            features: 'Descubrimiento\nIniciamos con una sesión profunda para entender tu negocio, tus objetivos y a tu audiencia ideal.\n---\nEstrategia & Propuesta\nDesarrollamos un plan detallado con tiempos, entregables y métricas de éxito claras.\n---\nDiseño & Prototipado\nCreamos wireframes y prototipos interactivos para validar la dirección antes de producción.\n---\nDesarrollo & Producción\nNuestro equipo técnico da vida al diseño con código limpio, rápido y escalable.\n---\nPruebas & Lanzamiento\nRevisamos cada detalle antes del lanzamiento para garantizar una experiencia impecable.\n---\nSoporte & Crecimiento\nNo desaparecemos después del lanzamiento. Te acompañamos en el crecimiento continuo.',
          },
          children: {},
        },
        team: {
          id: 'team',
          type: 'TeamGridBlock',
          props: {
            eyebrow: 'El equipo creativo',
            title: 'Las mentes detrás de Nexus',
            subtitle: 'Diseñadores, estrategas y desarrolladores apasionados por crear cosas extraordinarias.',
            columns: '4',
            layout: 'card',
            team: 'Andrés Villanueva|Director Creativo\nMás de 12 años liderando proyectos de branding y diseño digital para marcas en Europa y América Latina.\n---\nValeria Cruz|Directora de Estrategia\nEspecialista en marketing digital con MBA y experiencia en consultoras globales de primer nivel.\n---\nJorge Medina|Lead Developer\nDesarrollador full-stack apasionado por el código limpio y las arquitecturas modernas y escalables.\n---\nNatalia Ríos|UX Designer\nEspecialista en investigación de usuarios y diseño centrado en la experiencia y la conversión.',
            photo1: '', photo2: '', photo3: '', photo4: '',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Clientes que confían en nosotros',
            title: 'Resultados que hablan',
            columns: '3',
            background: 'white',
            testimonials: 'Ricardo Blanco|CEO, FinTech México|5\nNexus transformó completamente nuestra presencia digital. En 3 meses duplicamos el tráfico orgánico y aumentamos nuestras conversiones en un 180%. Un equipo extraordinario.\n---\nCristina Pacheco|Directora de Marketing, Retailmex|5\nEl rebrand que hicieron para nuestra marca fue exactamente lo que necesitábamos. Moderno, coherente y con una identidad visual poderosa que conecta con nuestra audiencia.\n---\nSamuel Orozco|Fundador, EduTech|5\nConfiamos en Nexus para desarrollar nuestra plataforma educativa desde cero. El resultado superó todo lo que imaginamos. Entregaron a tiempo, dentro del presupuesto y con una calidad excepcional.',
          },
          children: {},
        },
        contact: {
          id: 'contact',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Siguiente paso',
            title: '¿Listo para transformar tu negocio digital?',
            subtitle: 'Cuéntanos tu proyecto. Respondemos en menos de 24 horas con una propuesta sin compromiso.',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '#formulario',
            ctaSecondLabel: 'Enviar WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-dark',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: {
          id: 'footer',
          type: 'FooterBlock',
          props: {
            variant: 'dark',
            brand: 'Nexus Studio',
            tagline: 'Creatividad, estrategia y tecnología al servicio de tu marca.',
            columns: 'Servicios | Servicios\nBranding | /\nDiseño Web | /\nMarketing Digital | /\nDesarrollo | /\n---\nAgencia | Agencia\nNosotros | /\nPortafolio | /\nBlog | /\nCasos de éxito | /\n---\nContacto | Contacto\nHablemos | #contacto\nLinkedIn | /\nInstagram | /',
            copyright: `© ${new Date().getFullYear()} Nexus Studio. Todos los derechos reservados.`,
            showBrand: true,
          },
          children: {},
        },
      },
    }
  },
})
