import { defineTemplate } from '@raulbellosom/atlas-web-builder'

export const negocioTemplate = defineTemplate({
  id: 'atlas-negocio',
  label: 'Negocio & Servicios',
  description: 'Plantilla versátil para empresas de servicios, consultoras, despachos y negocios B2B.',
  category: 'negocio',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'services', 'stats', 'testimonials', 'pricing', 'cta', 'footer'],
      blocks: {
        navbar: {
          id: 'navbar',
          type: 'NavbarBlock',
          props: {
            variant: 'light',
            brand: 'Empresa',
            links: 'Inicio | /\nServicios | #servicios\nNosotros | #nosotros\nPrecios | #precios\nContacto | #contacto',
            ctaLabel: 'Solicitar demo',
            ctaHref: '#contacto',
            ctaVariant: 'solid',
            sticky: true,
            height: '64',
          },
          children: {},
        },
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Soluciones que impulsan tu negocio al siguiente nivel',
            subtitle: 'Ofrecemos servicios especializados con metodología probada para ayudar a empresas como la tuya a crecer de forma sostenible y eficiente.',
            eyebrow: 'Más de 10 años de experiencia',
            ctaLabel: 'Comenzar ahora',
            ctaHref: '#contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Conocer más',
            ctaSecondHref: '#servicios',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '16',
            minHeight: '80vh',
            titleSize: '3xl',
            contentMaxWidth: '70ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Por qué elegirnos',
            title: 'La ventaja de trabajar con nosotros',
            subtitle: 'No somos proveedores, somos aliados estratégicos de tu crecimiento.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'muted',
            features: 'Metodología comprobada\nAplicamos procesos validados en más de 200 proyectos para garantizar resultados consistentes y medibles.\n---\nEquipo senior dedicado\nTu cuenta es atendida por profesionales con experiencia real en tu industria, no por juniors.\n---\nComunicación transparente\nReportes semanales, acceso a tablero en tiempo real y comunicación directa con tu equipo asignado.\n---\nSin contratos forzosos\nMes a mes. Creemos tanto en nuestro trabajo que no necesitamos atarte con contratos largos.\n---\nEnfoque en ROI\nCada decisión que tomamos está orientada a generar retorno real y medible sobre tu inversión.\n---\nEscalabilidad inmediata\nCrecemos contigo. Nuestros servicios se adaptan al tamaño y ritmo de tu empresa en cada etapa.',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Nuestros servicios',
            title: 'Soluciones integrales para tu empresa',
            subtitle: 'Cada servicio está diseñado para resolver un problema real y generar valor tangible.',
            columns: '3',
            services: 'Consultoría Estratégica\nAnálisis profundo de tu modelo de negocio con un plan de acción claro, priorizado y con métricas de seguimiento.\n---\nOptimización de Procesos\nIdentificamos cuellos de botella, eliminamos ineficiencias y automatizamos tareas para reducir costos operativos.\n---\nCapacitación Empresarial\nProgramas de formación personalizados para equipos comerciales, directivos y operativos de tu organización.\n---\nTransformación Digital\nAcompañamos tu proceso de digitalización desde la estrategia hasta la implementación de herramientas tecnológicas.\n---\nGestión de Proyectos\nDirigimos proyectos complejos con metodologías ágiles, garantizando entregas en tiempo, forma y presupuesto.\n---\nAuditoria Financiera\nRevisión integral de la salud financiera de tu empresa con recomendaciones para optimizar recursos y rentabilidad.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: 'Nuestros números',
            title: 'Resultados que respaldan nuestra trayectoria',
            stats: '10+ años\nEn el mercado\nAyudando empresas a crecer\n---\n350+\nEmpresas asesoradas\nEn diversos sectores\n---\n$50M+\nEn ahorros generados\nPara nuestros clientes\n---\n97%\nRenovación de contratos\nClientes que continúan',
            background: 'white',
            align: 'center',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Casos de éxito',
            title: 'Empresas que crecieron con nosotros',
            columns: '3',
            background: 'muted',
            testimonials: 'Fernando Lozano|Director General, Grupo Lozano|5\nEn 6 meses logramos reducir nuestros costos operativos en un 28% sin sacrificar calidad. El equipo de consultoría entendió perfectamente nuestra industria y entregó soluciones prácticas.\n---\nMónica Valdez|CFO, Distribuidora Valdez|5\nLa reestructura financiera que implementaron nos permitió acceder a crédito preferencial por primera vez en 15 años. Un trabajo excepcional, metódico y transparente en todo momento.\n---\nGustavo Aranda|CEO, Tech Startup|5\nNos acompañaron desde el MVP hasta la Serie A. Su experiencia en scale-ups fue fundamental para ordenar nuestra operación y escalar sin perder el control.',
          },
          children: {},
        },
        pricing: {
          id: 'pricing',
          type: 'PricingBlock',
          props: {
            eyebrow: 'Planes y precios',
            title: 'Elige el plan que mejor se adapte a tu empresa',
            subtitle: 'Sin sorpresas, sin cargos ocultos. Precio claro desde el primer día.',
            currency: '$',
            period: 'mes',
            plans: 'Starter\nIdeal para pequeñas empresas y emprendedores\n4,500\nConsultoría mensual (4 hrs)\nDiagnóstico inicial incluido\nReporte mensual de avance\nSoporte por email\n---\nProfesional\nPara empresas en crecimiento activo\n12,000\nConsultoría mensual (16 hrs)\nGestión de 1 proyecto activo\nTablero de métricas en tiempo real\nSoporte WhatsApp prioritario\nCapacitación trimestral\n---\nEnterprise\nPara organizaciones con necesidades complejas\nA medida\nConsultoría ilimitada\nEquipo dedicado senior\nProyectos simultáneos ilimitados\nIntegración con tus sistemas\nSLA con tiempos de respuesta garantizados',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Hablamos de tu empresa?',
            subtitle: 'Agenda una sesión de diagnóstico gratuita de 45 minutos. Sin compromiso, solo valor.',
            ctaLabel: 'Agendar sesión gratuita',
            ctaHref: '#contacto',
            ctaSecondLabel: 'Descargar brochure',
            ctaSecondHref: '#',
            variant: 'gradient-primary',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: {
          id: 'footer',
          type: 'FooterBlock',
          props: {
            variant: 'dark',
            brand: 'Empresa',
            tagline: 'Tu aliado estratégico para el crecimiento empresarial.',
            columns: 'Servicios | Servicios\nConsultoría | /\nOptimización | /\nCapacitación | /\nTransformación Digital | /\n---\nEmpresa | Empresa\nNosotros | /\nCasos de éxito | /\nBlog | /\nCarreras | /\n---\nContacto | Contacto\nAgendar llamada | #contacto\nLinkedIn | /\nCorreo | mailto:hola@empresa.com',
            copyright: `© ${new Date().getFullYear()} Empresa. Todos los derechos reservados.`,
            showBrand: true,
          },
          children: {},
        },
      },
    }
  },
})
