import { defineTemplate } from '@raulbellosom/atlas-web-builder'

export const restauranteTemplate = defineTemplate({
  id: 'atlas-restaurante',
  label: 'Restaurante',
  description: 'Sitio elegante para restaurantes y cafeterías con menú, galería y reservaciones.',
  category: 'restaurante',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'menu', 'gallery', 'testimonials', 'booking', 'footer'],
      blocks: {
        navbar: {
          id: 'navbar',
          type: 'NavbarBlock',
          props: {
            variant: 'dark',
            brand: 'El Sabor',
            links: 'Inicio | /\nMenú | #menu\nNosotros | #nosotros\nReservaciones | #reservar',
            ctaLabel: 'Reservar mesa',
            ctaHref: '#reservar',
            ctaVariant: 'solid',
            sticky: true,
            height: '72',
          },
          children: {},
        },
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'image-bg',
            title: 'Sabores que enamoran',
            subtitle: 'Cocina de autor con ingredientes frescos y recetas que conquistan el paladar. Una experiencia gastronómica que no olvidarás.',
            eyebrow: 'Bienvenidos a El Sabor',
            ctaLabel: 'Ver el menú',
            ctaHref: '#menu',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Hacer reservación',
            ctaSecondHref: '#reservar',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '16',
            minHeight: '90vh',
            titleSize: '3xl',
            contentMaxWidth: '65ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Por qué elegirnos',
            title: 'Una experiencia gastronómica única',
            subtitle: 'Cada visita es una ocasión especial. Nos comprometemos con la calidad en cada detalle.',
            columns: '3',
            services: 'Ingredientes frescos\nSeleccionamos los mejores productos locales de temporada para garantizar frescura y sabor incomparables.\n---\nChef de autor\nNuestro equipo culinario fusiona técnicas modernas con recetas tradicionales para crear platillos únicos.\n---\nAmbiente acogedor\nEspacios diseñados para que cada momento sea especial, ya sea una cita íntima o una reunión familiar.',
            cardStyle: 'minimal',
            align: 'center',
          },
          children: {},
        },
        menu: {
          id: 'menu',
          type: 'MenuGridBlock',
          props: {
            eyebrow: 'Lo que servimos',
            title: 'Nuestro Menú',
            subtitle: 'Platillos elaborados con pasión, perfectos para cada ocasión.',
            currency: '$',
            showPrices: true,
            columns: '2',
            menu: 'Entradas\nEnsalada de la Casa | Mixta con aderezo balsámico y queso manchego | 9.00\nSopa de Fideo Seco | Receta tradicional con chipotle y crema | 7.00\nCeviche de Camarón | Camarón fresco, limón, cilantro y chile | 13.00\nAgua de Jamaica | 500ml, flor de jamaica natural | 4.00\n---\nPlatos Fuertes\nFilete a las Brasas | 300g corte premium con guarnición a elegir | 32.00\nPollo en Mole Negro | Mole de 30 ingredientes con arroz y frijoles | 22.00\nPasta al Pesto | Fettuccine con pesto artesanal y parmesano | 18.00\nPescado a la Plancha | Filete del día con verduras asadas | 26.00\n---\nPostres\nFlan de Cajeta | Receta de la abuela, irresistible | 6.00\nPastel de Tres Leches | Esponjoso, húmedo y delicioso | 7.50\nHelado Artesanal | 3 bolas a elegir de nuestra carta | 5.00',
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Nuestro espacio',
            title: 'Galería',
            subtitle: 'Conoce el ambiente que hemos creado para ti.',
            columns: '3',
            gap: 'tight',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Nuestros comensales',
            title: 'Lo que dicen quienes nos visitan',
            columns: '3',
            background: 'muted',
            testimonials: 'Valentina Cruz|Cliente frecuente|5\nSin duda el mejor restaurante de la ciudad. La comida es exquisita y el servicio impecable. Cada vez que vengo es una experiencia diferente y siempre sorprendente.\n---\nRoberto Sánchez|Empresario|5\nLlevé a un cliente importante y quedó encantado. El ambiente es elegante sin ser pretencioso. Los platillos llegaron perfectos y a tiempo. Regresaremos sin duda.\n---\nLaura Ibáñez|Foodie y blogger|4\nUna cocina honesta y llena de sabor. El mole negro es espectacular y el servicio muy atento. Un lugar que recomendaré siempre en mi blog.',
          },
          children: {},
        },
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Reservaciones',
            title: 'Haz tu reservación hoy',
            subtitle: 'Asegura tu lugar para vivir una experiencia gastronómica que no olvidarás. Disponible todos los días de 1pm a 11pm.',
            ctaLabel: 'Reservar mesa',
            ctaHref: '#contacto',
            ctaSecondLabel: 'Llamar ahora',
            ctaSecondHref: 'tel:+525500000000',
            variant: 'gradient-dark',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: {
          id: 'footer',
          type: 'FooterBlock',
          props: {
            variant: 'dark',
            brand: 'El Sabor',
            tagline: 'Cocina de autor con alma y tradición.',
            columns: 'Visítanos | Horario\nLunes a Viernes | /\n1:00pm – 11:00pm | /\n---\nContacto | Contacto\nReservaciones | #reservar\nWhatsApp | /\nInstagram | /\n---\nUbicación | Ubicación\nCentro Histórico | /\nVer en mapa | /',
            copyright: `© ${new Date().getFullYear()} El Sabor. Todos los derechos reservados.`,
            showBrand: true,
          },
          children: {},
        },
      },
    }
  },
})
