import { defineTemplate } from '@raulbellosom/atlas-web-builder'

const BASE_MENU_ITEMS = 'Entradas\nEnsalada de la Casa | Mixta con aderezo balsámico y queso manchego | 9.00\nSopa de Fideo Seco | Receta tradicional con chipotle y crema | 7.00\nCeviche de Camarón | Camarón fresco, limón, cilantro y chile | 13.00\nAgua de Jamaica | 500ml, flor de jamaica natural | 4.00\n---\nPlatos Fuertes\nFilete a las Brasas | 300g corte premium con guarnición a elegir | 32.00\nPollo en Mole Negro | Mole de 30 ingredientes con arroz y frijoles | 22.00\nPasta al Pesto | Fettuccine con pesto artesanal y parmesano | 18.00\nPescado a la Plancha | Filete del día con verduras asadas | 26.00\n---\nPostres\nFlan de Cajeta | Receta de la abuela, irresistible | 6.00\nPastel de Tres Leches | Esponjoso, húmedo y delicioso | 7.50\nHelado Artesanal | 3 bolas a elegir de nuestra carta | 5.00'

const TESTIMONIALS_BLOCK = {
  id: 'testimonials',
  type: 'TestimonialsBlock',
  props: {
    eyebrow: 'Nuestros comensales',
    title: 'Lo que dicen quienes nos visitan',
    columns: '3',
    background: 'muted',
    testimonials: 'Valentina Cruz|Cliente frecuente|5\nSin duda el mejor restaurante de la ciudad. La comida es exquisita y el servicio impecable. Cada vez que vengo es una experiencia diferente y siempre sorprendente.\n---\nRoberto Sánchez|Empresario|5\nLlevé a un cliente importante y quedó encantado. El ambiente es elegante sin ser pretencioso. Los platillos llegaron perfectos y a tiempo. Regresaremos sin duda.\n---\nLaura Ibáñez|Foodie y blogger|4\nUna cocina honesta y llena de sabor. El mole negro es espectacular y el servicio muy atento. Un lugar que recomendaré siempre en mi blog.',
  },
  children: {},
}

const NAVBAR = {
  id: 'navbar',
  type: 'NavbarBlock',
  props: {
    variant: 'dark',
    brand: 'El Sabor',
    links: 'Inicio | /\nMenú | /menu\nGalería | /galeria\nNosotros | /nosotros\nContacto | /contacto',
    ctaLabel: 'Reservar mesa',
    ctaHref: '/contacto',
    ctaVariant: 'solid',
    sticky: true,
    height: '72',
  },
  children: {},
}

const FOOTER = {
  id: 'footer',
  type: 'FooterBlock',
  props: {
    variant: 'dark',
    brand: 'El Sabor',
    tagline: 'Cocina de autor con alma y tradición.',
    columns: 'Navegar | Navegar\nInicio | /\nMenú | /menu\nGalería | /galeria\nNosotros | /nosotros\n---\nContacto | Contacto\nReservaciones | /contacto\nWhatsApp | /\nInstagram | /\n---\nHorario | Horario\nLunes a Viernes | /\n1:00pm – 11:00pm | /\nSábados y Domingos | /\n12:00pm – 11:30pm | /',
    copyright: `© ${new Date().getFullYear()} El Sabor. Todos los derechos reservados.`,
    showBrand: true,
  },
  children: {},
}

export const restauranteTemplate = defineTemplate({
  id: 'atlas-restaurante',
  label: 'Restaurante',
  description: 'Sitio elegante para restaurantes y cafeterías con menú, galería y reservaciones.',
  category: 'restaurante',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'menu', 'gallery', 'testimonials', 'booking', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'image-bg',
            title: 'Sabores que enamoran',
            subtitle: 'Cocina de autor con ingredientes frescos y recetas que conquistan el paladar. Una experiencia gastronómica que no olvidarás.',
            eyebrow: 'Bienvenidos a El Sabor',
            ctaLabel: 'Ver el menú',
            ctaHref: '/menu',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Hacer reservación',
            ctaSecondHref: '/contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '16',
            minHeight: '90vh',
            titleSize: '3xl',
            contentMaxWidth: '65ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Por qué elegirnos',
            title: 'Una experiencia gastronómica única',
            subtitle: 'Cada visita es una ocasión especial. Nos comprometemos con la calidad en cada detalle.',
            columns: '3',
            services: 'Ingredientes frescos\nSeleccionamos los mejores productos locales de temporada para garantizar frescura y sabor incomparables.\n---\nChef de autor\nNuestro equipo culinario fusiona técnicas modernas con recetas tradicionales para crear platillos únicos.\n---\nAmbiente acogedor\nEspacios diseñados para que cada momento sea especial, ya sea una cita íntima o una reunión familiar.',
            cardStyle: 'minimal',
            align: 'center',
          },
          children: {},
        },
        menu: {
          id: 'menu',
          type: 'MenuGridBlock',
          props: {
            eyebrow: 'Lo que servimos',
            title: 'Nuestro Menú',
            subtitle: 'Platillos elaborados con pasión, perfectos para cada ocasión.',
            currency: '$',
            showPrices: true,
            columns: '2',
            menu: BASE_MENU_ITEMS,
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Nuestro espacio',
            title: 'Galería',
            subtitle: 'Conoce el ambiente que hemos creado para ti.',
            columns: '3',
            gap: 'tight',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        testimonials: TESTIMONIALS_BLOCK,
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Reservaciones',
            title: 'Haz tu reservación hoy',
            subtitle: 'Asegura tu lugar para vivir una experiencia gastronómica que no olvidarás. Disponible todos los días de 1pm a 11pm.',
            ctaLabel: 'Reservar mesa',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Llamar ahora',
            ctaSecondHref: 'tel:+525500000000',
            variant: 'gradient-dark',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }
  },
})

export const restauranteSitePages = [
  {
    id: 'menu',
    label: 'Menú',
    routePath: '/menu',
    required: false,
    description: 'Nuestro menú completo con precios.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'menu', 'booking', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestro Menú',
            subtitle: 'Platillos elaborados con ingredientes frescos y pasión por la gastronomía de autor.',
            eyebrow: 'Lo que servimos',
            ctaLabel: '',
            ctaHref: '',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'center',
            paddingY: '12',
            minHeight: '40vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        menu: {
          id: 'menu',
          type: 'MenuGridBlock',
          props: {
            eyebrow: 'Carta completa',
            title: 'Todo nuestro menú',
            subtitle: 'Cada platillo, elaborado con los mejores ingredientes de temporada.',
            currency: '$',
            showPrices: true,
            columns: '2',
            menu: `${BASE_MENU_ITEMS}\n---\nBebidas\nAgua de Fruta | Del día, 500ml | 4.00\nRefrescos | Varios sabores | 3.50\nVino de la Casa | Copa, blanco o tinto | 8.00\nCerveza Artesanal | Botella 355ml | 7.00`,
          },
          children: {},
        },
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Reservaciones',
            title: 'Haz tu reservación hoy',
            subtitle: 'Asegura tu lugar para vivir una experiencia gastronómica que no olvidarás.',
            ctaLabel: 'Reservar mesa',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Llamar ahora',
            ctaSecondHref: 'tel:+525500000000',
            variant: 'gradient-dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'galeria',
    label: 'Galería',
    routePath: '/galeria',
    required: false,
    description: 'Galería de imágenes de nuestro espacio y platillos.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'gallery', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Galería',
            subtitle: 'Conoce el ambiente que hemos creado y los platillos que nos hacen únicos.',
            eyebrow: 'Nuestro espacio',
            ctaLabel: '',
            ctaHref: '',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'center',
            paddingY: '12',
            minHeight: '40vh',
            titleSize: '2xl',
            contentMaxWidth: '55ch',
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Fotos del restaurante',
            title: 'El ambiente que te espera',
            subtitle: 'Espacios diseñados para momentos especiales y platillos que enamoran a la vista.',
            columns: '3',
            gap: 'normal',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: 'Visítanos pronto',
            subtitle: 'Haz tu reservación y vive la experiencia en persona.',
            ctaLabel: 'Reservar mesa',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Ver el menú',
            ctaSecondHref: '/menu',
            variant: 'gradient-dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'nosotros',
    label: 'Nosotros',
    routePath: '/nosotros',
    required: false,
    description: 'Nuestra historia y los valores del restaurante.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'story', 'values', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestra Historia',
            subtitle: 'Conoce la pasión, los valores y las personas que hacen de El Sabor un lugar especial.',
            eyebrow: 'Sobre nosotros',
            ctaLabel: 'Ver el menú',
            ctaHref: '/menu',
            ctaSecondLabel: 'Reservar',
            ctaSecondHref: '/contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '14',
            minHeight: '50vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        story: {
          id: 'story',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Nuestra historia',
            title: 'Más de una década compartiendo sabores',
            subtitle: 'Nacimos de la pasión por la gastronomía y el deseo de crear un espacio donde cada visita sea memorable.',
            layout: 'grid-2',
            iconStyle: 'check',
            background: 'white',
            features: 'Fundados en 2012\nComenzamos como un pequeño bistró familiar con una misión: llevar cocina de autor accesible a nuestra comunidad.\n---\nIngredientes locales\nDesde el primer día apostamos por proveedores locales y productos de temporada para garantizar frescura y apoyar la economía local.\n---\nChef reconocido\nNuestro chef ejecutivo acumula más de 15 años de experiencia en cocinas de México, España e Italia.\n---\nPremio a la calidad\nFuimos reconocidos como uno de los mejores restaurantes de la región en 2022 y 2024.',
          },
          children: {},
        },
        values: {
          id: 'values',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Lo que nos mueve',
            title: 'Nuestros valores',
            subtitle: 'Principios que guían cada platillo que ponemos en tu mesa.',
            columns: '3',
            services: 'Calidad sin compromiso\nSeleccionamos los mejores ingredientes y aplicamos técnicas que garantizan un resultado excepcional en cada platillo.\n---\nServicio con calidez\nCreemos que una gran comida se complementa con un servicio atento, cálido y profesional en cada visita.\n---\nTradición e innovación\nRespetamos las recetas tradicionales mientras exploramos nuevas técnicas y sabores para mantenernos frescos y relevantes.',
            cardStyle: 'minimal',
            align: 'center',
          },
          children: {},
        },
        testimonials: TESTIMONIALS_BLOCK,
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Listo para visitarnos?',
            subtitle: 'Haz tu reservación y vive la experiencia.',
            ctaLabel: 'Reservar mesa',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Ver el menú',
            ctaSecondHref: '/menu',
            variant: 'gradient-dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'contacto',
    label: 'Contacto',
    routePath: '/contacto',
    required: false,
    description: 'Información de contacto y reservaciones.',
    build: () => ({
      rootIds: ['navbar', 'info', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        info: {
          id: 'info',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Cómo encontrarnos',
            title: 'Información de contacto',
            subtitle: 'Estamos aquí para atenderte. Visítanos, llámanos o escríbenos.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Dirección\nCentro Histórico, Ciudad de México. A dos cuadras de la estación de metro.\n---\nHorario\nLunes a viernes: 1:00pm – 11:00pm\nSábados y domingos: 12:00pm – 11:30pm\n---\nTeléfono y WhatsApp\nLlámanos o escríbenos al +52 55 0000 0000. Respondemos en minutos.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Reservaciones',
            title: 'Haz tu reservación hoy',
            subtitle: 'Asegura tu lugar para vivir una experiencia gastronómica que no olvidarás.',
            ctaLabel: 'WhatsApp',
            ctaHref: 'https://wa.me/525500000000',
            ctaSecondLabel: 'Llamar ahora',
            ctaSecondHref: 'tel:+525500000000',
            variant: 'gradient-dark',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
]
