import { defineTemplate } from '@raulbellosom/atlas-web-builder'

const NAVBAR = {
  id: 'navbar',
  type: 'NavbarBlock',
  props: {
    variant: 'light',
    brand: 'Serenity Spa',
    links: 'Inicio | /\nServicios | /servicios\nEquipo | /equipo\nContacto | /contacto',
    ctaLabel: 'Reservar cita',
    ctaHref: '/contacto',
    ctaVariant: 'solid',
    sticky: true,
    height: '68',
  },
  children: {},
}

const FOOTER = {
  id: 'footer',
  type: 'FooterBlock',
  props: {
    variant: 'light',
    brand: 'Serenity Spa',
    tagline: 'Bienestar integral para cuerpo, mente y espíritu.',
    columns: 'Servicios | Servicios\nMasajes | /servicios\nFaciales | /servicios\nAromaterapia | /servicios\nYoga | /servicios\n---\nInformación | Información\nNosotros | /\nEquipo | /equipo\nPolítica de privacidad | /\n---\nContacto | Contacto\nReservar cita | /contacto\nWhatsApp | /\nInstagram | /',
    copyright: `© ${new Date().getFullYear()} Serenity Spa. Todos los derechos reservados.`,
    showBrand: true,
  },
  children: {},
}

export const spaTemplate = defineTemplate({
  id: 'atlas-spa',
  label: 'Spa & Bienestar',
  description: 'Diseño suave y elegante para spas, salones de belleza, yoga y wellness.',
  category: 'belleza',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'services', 'stats', 'features', 'testimonials', 'booking', 'team', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'split',
            title: 'Renueva tu cuerpo y mente',
            subtitle: 'Escápate del mundo y descubre el equilibrio perfecto entre relajación y bienestar. Tu momento de paz te espera.',
            eyebrow: 'Bienvenida a Serenity',
            ctaLabel: 'Ver servicios',
            ctaHref: '/servicios',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Agenda una cita',
            ctaSecondHref: '/contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'left',
            paddingY: '16',
            minHeight: '85vh',
            titleSize: '3xl',
            contentMaxWidth: '55ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Lo que ofrecemos',
            title: 'Nuestros Servicios',
            subtitle: 'Cada tratamiento ha sido diseñado para brindarte una experiencia transformadora.',
            columns: '3',
            services: 'Masajes Terapéuticos\nTécnicas especializadas para aliviar tensiones, mejorar la circulación y restaurar tu bienestar físico y mental.\n---\nFaciales Premium\nTratamientos faciales con productos naturales de primera calidad para una piel radiante y rejuvenecida.\n---\nAromaterapia\nSesiones de relajación profunda con aceites esenciales puros que equilibran cuerpo, mente y espíritu.\n---\nYoga & Meditación\nClases guiadas para todos los niveles que te ayudarán a encontrar el centro y la calma interior.\n---\nHidroterapia\nCircuitos de agua con diferentes temperaturas que estimulan la circulación y eliminan toxinas.\n---\nNutrición Holística\nAsesoría personalizada para complementar tus tratamientos con hábitos alimenticios que transforman.',
            cardStyle: 'card',
            align: 'center',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: '',
            title: '',
            stats: '5,000+\nClientes satisfechas\nConfían en nosotros\n---\n12 años\nDe experiencia\nEn bienestar integral\n---\n98%\nSatisfacción\nTasa de retorno\n---\n25+\nTratamientos\nEspecializados',
            background: 'primary',
            align: 'center',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'La diferencia Serenity',
            title: 'Una experiencia diseñada para ti',
            subtitle: 'Cada detalle de tu visita está pensado para que salgas renovada y con ganas de volver.',
            layout: 'grid-2',
            iconStyle: 'check',
            background: 'muted',
            features: 'Ambiente de total privacidad\nEspacios íntimos diseñados para que te desconectes completamente del mundo exterior.\n---\nProductos 100% naturales\nUtilizamos exclusivamente ingredientes orgánicos y cruelty-free en todos nuestros tratamientos.\n---\nTerapeutas certificadas\nNuestro equipo cuenta con certificaciones internacionales y años de experiencia especializada.\n---\nPersonalización total\nCada tratamiento se adapta a tus necesidades específicas, tipo de piel y objetivos de bienestar.\n---\nReservas fáciles\nAgenda tu cita en minutos a través de nuestra plataforma en línea, disponible 24/7.\n---\nSeguimiento continuo\nTe enviamos recordatorios y recomendaciones personalizadas para mantener tus resultados.',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Experiencias reales',
            title: 'Lo que dicen nuestras clientas',
            columns: '3',
            background: 'white',
            testimonials: 'Mariana López|Clienta desde 2019|5\nSerenity Spa cambió completamente mi rutina de bienestar. Llevo 5 años visitándolas y cada vez la experiencia es mejor. El masaje de aromaterapia es mi favorito absoluto.\n---\nPatricia Ruiz|Empresaria|5\nUn oasis en medio de la ciudad. Vengo cada dos semanas y es lo que me mantiene equilibrada. Las terapeutas son expertas y muy profesionales. ¡Imprescindible!\n---\nAlejandra Torres|Médica|5\nComo profesional de la salud, aprecio la rigurosidad en sus protocolos y la calidad de sus productos. Me siento en muy buenas manos cada vez que vengo.',
          },
          children: {},
        },
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Agenda tu cita',
            title: 'Tu momento de paz comienza hoy',
            subtitle: 'Regálate el descanso que mereces. Primera consulta sin costo y 20% de descuento en tu primer tratamiento.',
            ctaLabel: 'Reservar ahora',
            ctaHref: '/contacto',
            ctaSecondLabel: 'WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-primary',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        team: {
          id: 'team',
          type: 'TeamGridBlock',
          props: {
            eyebrow: 'Nuestras expertas',
            title: 'El equipo que cuida de ti',
            subtitle: 'Profesionales apasionadas y certificadas, dedicadas a tu bienestar.',
            columns: '3',
            layout: 'centered',
            team: 'Dra. Elena Vidal|Directora & Terapeuta Senior\nEspecialista en bienestar holístico con certificación internacional en terapias integrativas y más de 12 años de experiencia.\n---\nCarolina Jiménez|Esteticista Premium\nExperta en tratamientos faciales avanzados y técnicas de rejuvenecimiento no invasivo con productos de alta gama.\n---\nValeria Moreno|Instructora de Yoga\nCertificada en yoga terapéutico y meditación mindfulness. Imparte clases para todos los niveles con enfoque holístico.',
            photo1: '', photo2: '', photo3: '',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }
  },
})

export const spaSitePages = [
  {
    id: 'servicios',
    label: 'Servicios',
    routePath: '/servicios',
    required: false,
    description: 'Catálogo completo de tratamientos y servicios.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'services', 'features', 'booking', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestros Servicios',
            subtitle: 'Cada tratamiento ha sido diseñado para brindarte una experiencia transformadora. Elige el que más necesitas.',
            eyebrow: 'Tratamientos especializados',
            ctaLabel: 'Reservar cita',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'center',
            paddingY: '12',
            minHeight: '45vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Todos nuestros tratamientos',
            title: 'Diseñados para tu bienestar',
            subtitle: 'Cada servicio está personalizado y llevado a cabo por especialistas certificadas.',
            columns: '3',
            services: 'Masajes Terapéuticos\nTécnicas especializadas para aliviar tensiones, mejorar la circulación y restaurar tu bienestar físico y mental. Duración: 60–90 min.\n---\nFaciales Premium\nTratamientos faciales con productos naturales de primera calidad para una piel radiante y rejuvenecida. Para todo tipo de piel.\n---\nAromaterapia\nSesiones de relajación profunda con aceites esenciales puros que equilibran cuerpo, mente y espíritu. Duración: 60 min.\n---\nYoga & Meditación\nClases guiadas para todos los niveles. Te ayudarán a encontrar el centro y la calma interior. Grupos pequeños o privadas.\n---\nHidroterapia\nCircuitos de agua con diferentes temperaturas que estimulan la circulación y eliminan toxinas. Incluye área húmeda completa.\n---\nNutrición Holística\nAsesoría personalizada para complementar tus tratamientos con hábitos alimenticios que transforman. Sesión de 45 min.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Por qué elegirnos',
            title: 'La diferencia Serenity',
            subtitle: 'No somos un spa más. Somos tu aliada en bienestar.',
            layout: 'grid-2',
            iconStyle: 'check',
            background: 'muted',
            features: 'Productos 100% naturales\nUtilizamos exclusivamente ingredientes orgánicos y cruelty-free en todos nuestros tratamientos sin excepción.\n---\nTerapeutas certificadas\nNuestro equipo cuenta con certificaciones internacionales y años de experiencia especializada en cada área.\n---\nPersonalización total\nCada tratamiento se adapta a tus necesidades específicas, tipo de piel y objetivos de bienestar.\n---\nReservas fáciles\nAgenda tu cita en minutos. Disponible 24/7 online o por WhatsApp.',
          },
          children: {},
        },
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Agenda tu cita',
            title: 'Tu momento de paz comienza hoy',
            subtitle: 'Primera consulta sin costo y 20% de descuento en tu primer tratamiento.',
            ctaLabel: 'Reservar ahora',
            ctaHref: '/contacto',
            ctaSecondLabel: 'WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-primary',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'equipo',
    label: 'Equipo',
    routePath: '/equipo',
    required: false,
    description: 'Conoce al equipo de expertas que cuidan de ti.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'team', 'testimonials', 'booking', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestro Equipo',
            subtitle: 'Profesionales apasionadas, certificadas y dedicadas a tu bienestar en cada visita.',
            eyebrow: 'Las manos que cuidan de ti',
            ctaLabel: 'Reservar cita',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'center',
            paddingY: '12',
            minHeight: '45vh',
            titleSize: '2xl',
            contentMaxWidth: '58ch',
          },
          children: {},
        },
        team: {
          id: 'team',
          type: 'TeamGridBlock',
          props: {
            eyebrow: 'Nuestras especialistas',
            title: 'El equipo que cuida de ti',
            subtitle: 'Cada miembro de nuestro equipo está certificada y apasionada por el bienestar.',
            columns: '3',
            layout: 'card',
            team: 'Dra. Elena Vidal|Directora & Terapeuta Senior\nEspecialista en bienestar holístico con certificación internacional en terapias integrativas y más de 12 años de experiencia.\n---\nCarolina Jiménez|Esteticista Premium\nExperta en tratamientos faciales avanzados y técnicas de rejuvenecimiento no invasivo con productos de alta gama.\n---\nValeria Moreno|Instructora de Yoga\nCertificada en yoga terapéutico y meditación mindfulness. Imparte clases para todos los niveles con enfoque holístico.\n---\nSofía Ramírez|Terapeuta en Hidroterapia\nEspecialista en circuitos de agua, baños de inmersión y terapias de contraste para la recuperación y el bienestar.\n---\nAna Gutiérrez|Nutrióloga Holística\nLicenciada en nutrición con enfoque en alimentación consciente y planes personalizados para complementar los tratamientos del spa.\n---\nLorena Castro|Masajista Deportiva\nCertificada en técnicas de masaje deportivo, relajación profunda y liberación miofascial para atletas y personas activas.',
            photo1: '', photo2: '', photo3: '', photo4: '', photo5: '', photo6: '',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Experiencias reales',
            title: 'Lo que dicen nuestras clientas',
            columns: '3',
            background: 'muted',
            testimonials: 'Mariana López|Clienta desde 2019|5\nSerenity Spa cambió completamente mi rutina de bienestar. Llevo 5 años visitándolas y cada vez la experiencia es mejor. El masaje de aromaterapia es mi favorito absoluto.\n---\nPatricia Ruiz|Empresaria|5\nUn oasis en medio de la ciudad. Vengo cada dos semanas y es lo que me mantiene equilibrada. Las terapeutas son expertas y muy profesionales.\n---\nAlejandra Torres|Médica|5\nComo profesional de la salud, aprecio la rigurosidad en sus protocolos y la calidad de sus productos. Me siento en muy buenas manos cada vez que vengo.',
          },
          children: {},
        },
        booking: {
          id: 'booking',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: 'Elige a tu terapeuta favorita',
            subtitle: 'Reserva tu cita y dinos con quién prefieres trabajar.',
            ctaLabel: 'Reservar ahora',
            ctaHref: '/contacto',
            ctaSecondLabel: 'WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'contacto',
    label: 'Contacto',
    routePath: '/contacto',
    required: false,
    description: 'Agenda tu cita e información de contacto.',
    build: () => ({
      rootIds: ['navbar', 'info', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        info: {
          id: 'info',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Cómo encontrarnos',
            title: 'Información de contacto',
            subtitle: 'Estamos aquí para atenderte. Visítanos, llámanos o escríbenos.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Dirección\nColonia Polanco, Ciudad de México. En un ambiente de total privacidad y tranquilidad.\n---\nHorario\nLunes a sábado: 9:00am – 8:00pm\nDomingos: 10:00am – 5:00pm\n---\nTeléfono y WhatsApp\nLlámanos o escríbenos al +52 55 0000 0000 para agendar tu cita de manera rápida.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Agenda tu cita',
            title: 'Tu momento de paz comienza hoy',
            subtitle: 'Primera consulta sin costo y 20% de descuento en tu primer tratamiento.',
            ctaLabel: 'WhatsApp',
            ctaHref: 'https://wa.me/525500000000',
            ctaSecondLabel: 'Llamar ahora',
            ctaSecondHref: 'tel:+525500000000',
            variant: 'gradient-primary',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
]
