import { defineTemplate } from '@raulbellosom/atlas-web-builder'

export const tiendaTemplate = defineTemplate({
  id: 'atlas-tienda',
  label: 'Tienda en línea',
  description: 'Plantilla de e-commerce moderna con grilla de productos, banner promocional y reseñas.',
  category: 'ecommerce',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'products', 'promo', 'categories', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: {
          id: 'navbar',
          type: 'NavbarBlock',
          props: {
            variant: 'light',
            brand: 'Mi Tienda',
            links: 'Inicio | /\nProductos | #productos\nNovedades | #novedades\nOfertas | #ofertas\nContacto | #contacto',
            ctaLabel: 'Ver carrito',
            ctaHref: '#carrito',
            ctaVariant: 'outline',
            sticky: true,
            height: '64',
          },
          children: {},
        },
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'split',
            title: 'Calidad que se siente diferente',
            subtitle: 'Descubre nuestra colección cuidadosamente seleccionada. Envíos rápidos, devoluciones sin preguntas y garantía de satisfacción.',
            eyebrow: 'Nueva colección 2025',
            ctaLabel: 'Comprar ahora',
            ctaHref: '#productos',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Ver novedades',
            ctaSecondHref: '#novedades',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'left',
            paddingY: '16',
            minHeight: '80vh',
            titleSize: '3xl',
            contentMaxWidth: '55ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: '',
            title: '',
            subtitle: '',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Envío gratis desde $500\nEn pedidos superiores a $500 pesos, el envío es completamente gratuito a todo el país.\n---\nDevoluciones sin costo\nSi no estás satisfecho, devuelve tu compra en 30 días sin ningún cargo adicional.\n---\nPago seguro garantizado\nTodas las transacciones están protegidas con encriptación SSL de 256 bits.',
          },
          children: {},
        },
        products: {
          id: 'products',
          type: 'ProductsGridBlock',
          props: {
            categoryId: '',
            limit: 8,
            columns: '4',
            showPrice: true,
            showAddToCart: true,
          },
          children: {},
        },
        promo: {
          id: 'promo',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Oferta especial',
            title: '20% de descuento en tu primera compra',
            subtitle: 'Usa el código BIENVENIDO al finalizar tu compra. Válido por tiempo limitado. ¡No te lo pierdas!',
            ctaLabel: 'Usar descuento',
            ctaHref: '#productos',
            ctaSecondLabel: 'Ver condiciones',
            ctaSecondHref: '#',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        categories: {
          id: 'categories',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Explorar por categoría',
            title: 'Encuentra exactamente lo que buscas',
            subtitle: 'Organizamos nuestro catálogo para que encuentres lo que necesitas en segundos.',
            columns: '4',
            services: 'Nuevos ingresos\nLo último en llegar a nuestra tienda, seleccionado con los más altos estándares de calidad.\n---\nMás vendidos\nLos productos favoritos de nuestros clientes. Los más comprados y mejor valorados.\n---\nOfertas y descuentos\nLas mejores oportunidades de la semana. Precios especiales por tiempo limitado.\n---\nEdición limitada\nColecciones exclusivas disponibles en cantidades muy limitadas. Sé el primero en tenerlas.',
            cardStyle: 'bordered',
            align: 'center',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Reseñas verificadas',
            title: 'Miles de clientes felices',
            columns: '3',
            background: 'muted',
            testimonials: 'Diana Flores|Cliente verificada|5\nLa calidad del producto superó mis expectativas. El empaque es hermoso y llegó en perfectas condiciones. Definitivamente volveré a comprar y recomendaré a mis amigas.\n---\nMiguel Herrera|Comprador frecuente|5\nEl servicio al cliente es excelente. Tuve un pequeño problema con mi pedido y lo resolvieron en menos de 24 horas. Profesionalismo total. Mi tienda de confianza.\n---\nIsabel Navarro|Primera compra|4\nFue mi primera compra en línea aquí y quedé muy satisfecha. El proceso fue sencillo, seguro y el producto llegó antes de lo esperado. Regresaré pronto.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: 'Suscríbete y obtén 10% de descuento',
            subtitle: 'Regístrate en nuestro boletín y sé el primero en enterarte de nuevos productos, ofertas exclusivas y promociones especiales.',
            ctaLabel: 'Suscribirme',
            ctaHref: '#newsletter',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            variant: 'dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: {
          id: 'footer',
          type: 'FooterBlock',
          props: {
            variant: 'dark',
            brand: 'Mi Tienda',
            tagline: 'Calidad, estilo y confianza en cada compra.',
            columns: 'Comprar | Comprar\nNuevos productos | /\nMás vendidos | /\nOfertas | /\nMarcas | /\n---\nAyuda | Ayuda\nCómo comprar | /\nEnvíos y devoluciones | /\nPreguntas frecuentes | /\nContacto | /\n---\nLegal | Legal\nTérminos y condiciones | /\nPolítica de privacidad | /\nCookies | /',
            copyright: `© ${new Date().getFullYear()} Mi Tienda. Todos los derechos reservados.`,
            showBrand: true,
          },
          children: {},
        },
      },
    }
  },
})
