import { defineView } from "@atlas/module-engine";

export default defineView({
  key: "fleet.reports.service.form",
  kind: "FORM",
  version: "0.2.3",
  schema: {
    entity: "report",
    component: "AtlasForm",
    apiPath: "/fleet/reports/service",
    formMode: "page",
    title: "Nuevo Reporte de Servicio",
    submitLabel: "Finalizar reporte",
    cancelLabel: "Cancelar",
    sections: [
      {
        id: "vehicle",
        label: "Vehiculo",
        icon: "Wrench",
        description: "Selecciona el vehiculo al que se le realizo el servicio.",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [
          {
            field: "vehicle_id",
            label: "Seleccionar vehiculo",
            type: "relation",
            required: true,
            relation: {
              apiPath: "/fleet/vehicles",
              labelField: ["plate", "vehicle_model_name"],
              labelSeparator: " · ",
              clearable: false,
              disabledField: "enabled",
              searchParam: "search",
              displayFields: {
                badge: "full_economic_number",
                title: "vehicle_model_name",
                subtitle: ["plate", "vehicle_type_name", "vehicle_brand_name"],
              },
            },
          },
        ],
      },
      {
        id: "service_data",
        label: "Datos del Servicio",
        icon: "CalendarDays",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "title", label: "Titulo del servicio", type: "text", required: true },
          {
            field: "service_subtype",
            label: "Tipo de servicio",
            type: "select",
            required: true,
            options: [
              { label: "General", value: "general" },
              { label: "Diagnostico", value: "diagnostic" },
              { label: "Limpieza", value: "cleaning" },
              { label: "Electrico", value: "electrical" },
              { label: "Otro", value: "other" },
            ],
          },
          { field: "report_date", label: "Fecha del servicio", type: "date", required: true },
          { field: "odometer_km", label: "Kilometraje", type: "number" },
        ],
      },
      {
        id: "workshop",
        label: "Informacion del Taller",
        icon: "Building2",
        description: "Datos del proveedor que realizo el trabajo. Si es taller propio, estos datos son opcionales.",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "is_inhouse_workshop", label: "Taller propio", type: "boolean", default: true, hint: "Si activas esta opcion, no se exigiran datos del taller ni factura." },
          { field: "workshop_name", label: "Nombre del taller", type: "text", visibleWhen: { field: "is_inhouse_workshop", equals: false } },
          { field: "workshop_phone", label: "Telefono", type: "phone", visibleWhen: { field: "is_inhouse_workshop", equals: false } },
          { field: "workshop_address", label: "Direccion", type: "text", visibleWhen: { field: "is_inhouse_workshop", equals: false } },
          {
            field: "invoice_number",
            label: "No. de factura / ticket",
            type: "text",
            visibleWhen: { field: "is_inhouse_workshop", equals: false },
          },
        ],
      },
      {
        id: "parts",
        type: "parts-editor",
        label: "Refacciones / Partes",
        icon: "Package",
        description: "Agrega piezas, cantidades y costo unitario.",
        collapsible: true,
        defaultCollapsed: false,
      },
      {
        id: "costs",
        label: "Resumen de Costos",
        icon: "BadgeDollarSign",
        collapsible: true,
        defaultCollapsed: false,
        columns: 3,
        fields: [
          { field: "labor_cost", label: "Mano de obra", type: "currency" },
          { field: "parts_cost", label: "Costo de refacciones (calculado automaticamente)", type: "currency", readonly: true },
          { field: "total_cost", label: "Costo final total (mano de obra + partes)", type: "currency", readonly: true },
        ],
      },
      {
        id: "notes",
        label: "Observaciones",
        icon: "FileText",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [{ field: "notes", label: "Descripcion / notas", type: "textarea" }],
      },
      {
        id: "attachments",
        type: "attachments",
        label: "Archivos Adjuntos",
        icon: "Paperclip",
        collapsible: true,
        defaultCollapsed: false,
        attachments: {
          createMode: "stage-until-parent-create",
          editMode: "upload-immediately",
          listPath: "/fleet/reports/:id/documents",
          addPath: "/fleet/reports/:id/documents",
          removePath: "/fleet/reports/:id/documents/:docId",
          upload: {
            endpoint: "/files/upload",
            moduleKey: "atlas.fleet",
            entityType: "FleetReport",
          },
          signedUrl: {
            endpointTemplate: "/files/:fileId/signed-url",
          },
          fields: {
            id: "id",
            fileAssetId: "file_asset_id",
            documentType: "document_type",
            label: "label",
            createdAt: "created_at",
            enabled: "enabled",
            fileAsset: "file_asset",
            fileName: "originalName",
            mimeType: "mimeType",
            sizeBytes: "sizeBytes",
          },
          permissions: {
            read: "fleet.reports.read",
            create: "fleet.reports.update",
            remove: "fleet.reports.update",
            fileUpload: "files.assets.create",
            fileRead: "files.assets.read",
          },
          limits: {
            maxFiles: 20,
            maxSizeMB: 10,
            allowMultiple: true,
          },
        },
      },
    ],
  },
});
