import { defineTemplate } from '@raulbellosom/atlas-web-builder'

const NAVBAR = {
  id: 'navbar',
  type: 'NavbarBlock',
  props: {
    variant: 'dark',
    brand: 'Nexus Studio',
    links: 'Inicio | /\nServicios | /servicios\nPortafolio | /portafolio\nEquipo | /equipo\nContacto | /contacto',
    ctaLabel: 'Hablemos',
    ctaHref: '/contacto',
    ctaVariant: 'solid',
    sticky: true,
    height: '68',
  },
  children: {},
}

const FOOTER = {
  id: 'footer',
  type: 'FooterBlock',
  props: {
    variant: 'dark',
    brand: 'Nexus Studio',
    tagline: 'Creatividad, estrategia y tecnología al servicio de tu marca.',
    columns: 'Servicios | Servicios\nBranding | /servicios\nDiseño Web | /servicios\nMarketing Digital | /servicios\nDesarrollo | /servicios\n---\nAgencia | Agencia\nNosotros | /\nPortafolio | /portafolio\nEquipo | /equipo\n---\nContacto | Contacto\nHablemos | /contacto\nLinkedIn | /\nInstagram | /',
    copyright: `© ${new Date().getFullYear()} Nexus Studio. Todos los derechos reservados.`,
    showBrand: true,
  },
  children: {},
}

export const agenciaTemplate = defineTemplate({
  id: 'atlas-agencia',
  label: 'Agencia & Portafolio',
  description: 'Plantilla bold y profesional para agencias creativas, estudios de diseño y portafolios.',
  category: 'agencia',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'services', 'stats', 'gallery', 'features', 'team', 'testimonials', 'contact', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Creamos experiencias digitales que transforman negocios',
            subtitle: 'Agencia creativa especializada en branding, diseño web y estrategia digital. Transformamos tus ideas en resultados medibles.',
            eyebrow: 'Agencia creativa',
            ctaLabel: 'Ver portafolio',
            ctaHref: '/portafolio',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Hablemos de tu proyecto',
            ctaSecondHref: '/contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '16',
            minHeight: '88vh',
            titleSize: '3xl',
            contentMaxWidth: '70ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Nuestras especialidades',
            title: 'Lo que hacemos mejor',
            subtitle: 'Combinamos estrategia, diseño y tecnología para crear soluciones digitales que impulsan tu negocio.',
            columns: '3',
            services: 'Branding & Identidad\nCreamos marcas memorables con personalidad propia. Desde la estrategia hasta el manual de identidad completo.\n---\nDiseño Web\nSitios web modernos, rápidos y optimizados para convertir visitantes en clientes. Mobile-first siempre.\n---\nMarketing Digital\nEstrategias 360° que combinan SEO, redes sociales y publicidad pagada para maximizar tu alcance.\n---\nDiseño UX/UI\nInterfases intuitivas y atractivas que mejoran la experiencia del usuario y aumentan la conversión.\n---\nDesarrollo a Medida\nAplicaciones web y móviles construidas con las tecnologías más modernas del mercado.\n---\nConsultoría Estratégica\nAnálisis profundo de tu negocio digital con recomendaciones accionables y medibles.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: '',
            title: '',
            stats: '200+\nProyectos entregados\nEn 5 años\n---\n50+\nClientes activos\nEn 8 países\n---\n98%\nTasa de retención\nClientes satisfechos\n---\n15\nPremios ganados\nReconocimientos internacionales',
            background: 'dark',
            align: 'center',
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Portafolio selecto',
            title: 'Proyectos que hablan por sí solos',
            subtitle: 'Una muestra de nuestro trabajo más reciente.',
            columns: '3',
            gap: 'normal',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Nuestra metodología',
            title: 'Cómo trabajamos contigo',
            subtitle: 'Un proceso claro, transparente y orientado a resultados en cada etapa.',
            layout: 'grid-3',
            iconStyle: 'number',
            background: 'muted',
            features: 'Descubrimiento\nIniciamos con una sesión profunda para entender tu negocio, tus objetivos y a tu audiencia ideal.\n---\nEstrategia & Propuesta\nDesarrollamos un plan detallado con tiempos, entregables y métricas de éxito claras.\n---\nDiseño & Prototipado\nCreamos wireframes y prototipos interactivos para validar la dirección antes de producción.\n---\nDesarrollo & Producción\nNuestro equipo técnico da vida al diseño con código limpio, rápido y escalable.\n---\nPruebas & Lanzamiento\nRevisamos cada detalle antes del lanzamiento para garantizar una experiencia impecable.\n---\nSoporte & Crecimiento\nNo desaparecemos después del lanzamiento. Te acompañamos en el crecimiento continuo.',
          },
          children: {},
        },
        team: {
          id: 'team',
          type: 'TeamGridBlock',
          props: {
            eyebrow: 'El equipo creativo',
            title: 'Las mentes detrás de Nexus',
            subtitle: 'Diseñadores, estrategas y desarrolladores apasionados por crear cosas extraordinarias.',
            columns: '4',
            layout: 'card',
            team: 'Andrés Villanueva|Director Creativo\nMás de 12 años liderando proyectos de branding y diseño digital para marcas en Europa y América Latina.\n---\nValeria Cruz|Directora de Estrategia\nEspecialista en marketing digital con MBA y experiencia en consultoras globales de primer nivel.\n---\nJorge Medina|Lead Developer\nDesarrollador full-stack apasionado por el código limpio y las arquitecturas modernas y escalables.\n---\nNatalia Ríos|UX Designer\nEspecialista en investigación de usuarios y diseño centrado en la experiencia y la conversión.',
            photo1: '', photo2: '', photo3: '', photo4: '',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Clientes que confían en nosotros',
            title: 'Resultados que hablan',
            columns: '3',
            background: 'white',
            testimonials: 'Ricardo Blanco|CEO, FinTech México|5\nNexus transformó completamente nuestra presencia digital. En 3 meses duplicamos el tráfico orgánico y aumentamos nuestras conversiones en un 180%.\n---\nCristina Pacheco|Directora de Marketing, Retailmex|5\nEl rebrand que hicieron para nuestra marca fue exactamente lo que necesitábamos. Moderno, coherente y con una identidad visual poderosa.\n---\nSamuel Orozco|Fundador, EduTech|5\nConfiamos en Nexus para desarrollar nuestra plataforma educativa desde cero. Entregaron a tiempo, dentro del presupuesto y con una calidad excepcional.',
          },
          children: {},
        },
        contact: {
          id: 'contact',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Siguiente paso',
            title: '¿Listo para transformar tu negocio digital?',
            subtitle: 'Cuéntanos tu proyecto. Respondemos en menos de 24 horas con una propuesta sin compromiso.',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Enviar WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-dark',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }
  },
})

export const agenciaSitePages = [
  {
    id: 'servicios',
    label: 'Servicios',
    routePath: '/servicios',
    required: false,
    description: 'Servicios y especialidades de la agencia.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'services', 'methodology', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestros Servicios',
            subtitle: 'Soluciones creativas y tecnológicas que impulsan el crecimiento de tu negocio digital.',
            eyebrow: 'Lo que hacemos',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Ver portafolio',
            ctaSecondHref: '/portafolio',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '14',
            minHeight: '50vh',
            titleSize: '2xl',
            contentMaxWidth: '65ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Especialidades',
            title: 'Todo lo que necesita tu marca digital',
            subtitle: 'Cada servicio está diseñado para generar resultados reales y medibles para tu negocio.',
            columns: '3',
            services: 'Branding & Identidad\nCreamos marcas memorables con personalidad propia. Estrategia de marca, naming, logotipo y manual de identidad completo.\n---\nDiseño Web\nSitios web modernos, rápidos y optimizados para convertir visitantes en clientes. Mobile-first y SEO-ready desde el día uno.\n---\nMarketing Digital\nEstrategias 360° que combinan SEO, contenidos, redes sociales y publicidad pagada para maximizar tu alcance y ROI.\n---\nDiseño UX/UI\nInterfases intuitivas y atractivas que mejoran la experiencia del usuario y aumentan la tasa de conversión.\n---\nDesarrollo a Medida\nAplicaciones web y móviles construidas con tecnologías modernas, seguras y escalables según tu negocio.\n---\nConsultoría Estratégica\nAuditoría de tu presencia digital actual, identificación de oportunidades y hoja de ruta accionable con métricas claras.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        methodology: {
          id: 'methodology',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Cómo trabajamos',
            title: 'Un proceso claro de inicio a fin',
            subtitle: 'Sin sorpresas. Cada etapa tiene entregables claros y comunicación constante.',
            layout: 'grid-3',
            iconStyle: 'number',
            background: 'muted',
            features: 'Descubrimiento\nSesión inicial para entender tu negocio, competencia, objetivos y audiencia ideal.\n---\nEstrategia\nPlan detallado con tiempos, entregables, responsables y métricas de éxito.\n---\nDiseño\nWireframes y prototipos interactivos validados contigo antes de pasar a producción.\n---\nDesarrollo\nImplementación con código limpio, revisiones constantes y pruebas rigurosas.\n---\nLanzamiento\nDeployment, pruebas finales y entrega con documentación completa.\n---\nSoporte\nAcompañamiento post-lanzamiento, métricas y mejora continua.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Listo para transformar tu negocio digital?',
            subtitle: 'Cuéntanos tu proyecto. Respondemos en menos de 24 horas con una propuesta sin compromiso.',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaSecondLabel: 'WhatsApp',
            ctaSecondHref: 'https://wa.me/525500000000',
            variant: 'gradient-dark',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'portafolio',
    label: 'Portafolio',
    routePath: '/portafolio',
    required: false,
    description: 'Proyectos y trabajos realizados.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'gallery', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestro Portafolio',
            subtitle: 'Proyectos que demuestran nuestra capacidad creativa, técnica y estratégica.',
            eyebrow: 'Trabajo selecto',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '14',
            minHeight: '45vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        gallery: {
          id: 'gallery',
          type: 'GalleryBlock',
          props: {
            eyebrow: 'Proyectos recientes',
            title: 'Trabajo que habla por sí solo',
            subtitle: 'Una selección de los proyectos de los que estamos más orgullosos.',
            columns: '3',
            gap: 'normal',
            aspectRatio: '4/3',
            image1: '', image2: '', image3: '',
            image4: '', image5: '', image6: '',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Clientes que confían en nosotros',
            title: 'Resultados que hablan',
            columns: '3',
            background: 'muted',
            testimonials: 'Ricardo Blanco|CEO, FinTech México|5\nNexus transformó completamente nuestra presencia digital. En 3 meses duplicamos el tráfico orgánico y aumentamos las conversiones en un 180%. Un equipo extraordinario.\n---\nCristina Pacheco|Directora de Marketing, Retailmex|5\nEl rebrand que hicieron para nuestra marca fue exactamente lo que necesitábamos. Moderno, coherente y con una identidad visual poderosa que conecta con nuestra audiencia.\n---\nSamuel Orozco|Fundador, EduTech|5\nConfiamos en Nexus para desarrollar nuestra plataforma educativa desde cero. Entregaron a tiempo, dentro del presupuesto y con una calidad excepcional.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Tu proyecto podría ser el próximo?',
            subtitle: 'Cuéntanos tu idea y construyamos algo extraordinario juntos.',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Ver servicios',
            ctaSecondHref: '/servicios',
            variant: 'gradient-dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'equipo',
    label: 'Equipo',
    routePath: '/equipo',
    required: false,
    description: 'El equipo creativo detrás de la agencia.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'team', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'El Equipo',
            subtitle: 'Diseñadores, estrategas y desarrolladores apasionados por crear cosas extraordinarias.',
            eyebrow: 'Las mentes detrás de Nexus',
            ctaLabel: 'Iniciar proyecto',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'fg' },
            align: 'center',
            paddingY: '14',
            minHeight: '45vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        team: {
          id: 'team',
          type: 'TeamGridBlock',
          props: {
            eyebrow: 'Nuestro equipo',
            title: 'Las personas detrás de cada proyecto',
            subtitle: 'Un equipo multidisciplinar comprometido con la excelencia en cada entrega.',
            columns: '4',
            layout: 'card',
            team: 'Andrés Villanueva|Director Creativo\nMás de 12 años liderando proyectos de branding y diseño digital para marcas en Europa y América Latina.\n---\nValeria Cruz|Directora de Estrategia\nEspecialista en marketing digital con MBA y experiencia en consultoras globales de primer nivel.\n---\nJorge Medina|Lead Developer\nDesarrollador full-stack apasionado por el código limpio y las arquitecturas modernas y escalables.\n---\nNatalia Ríos|UX Designer\nEspecialista en investigación de usuarios y diseño centrado en la experiencia y la conversión.',
            photo1: '', photo2: '', photo3: '', photo4: '',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Quieres trabajar con nosotros?',
            subtitle: 'Estamos creciendo y buscamos talentos apasionados por el diseño y la tecnología.',
            ctaLabel: 'Contáctanos',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Ver proyectos',
            ctaSecondHref: '/portafolio',
            variant: 'gradient-dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'contacto',
    label: 'Contacto',
    routePath: '/contacto',
    required: false,
    description: 'Inicia tu proyecto o envíanos un mensaje.',
    build: () => ({
      rootIds: ['navbar', 'info', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        info: {
          id: 'info',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Hablemos',
            title: 'Inicia tu proyecto hoy',
            subtitle: 'Respondemos en menos de 24 horas con una propuesta sin compromiso.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Correo electrónico\nhola@nexusstudio.com — para proyectos, propuestas y consultas generales.\n---\nWhatsApp\n+52 55 0000 0000 — para consultas rápidas y seguimiento de proyectos activos.\n---\nLinkedIn\nSíguenos en LinkedIn para ver nuestros proyectos más recientes y actualizaciones del equipo.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Siguiente paso',
            title: '¿Listo para transformar tu negocio digital?',
            subtitle: 'Cuéntanos tu proyecto. Sin compromiso, solo una conversación honesta sobre cómo podemos ayudarte.',
            ctaLabel: 'WhatsApp',
            ctaHref: 'https://wa.me/525500000000',
            ctaSecondLabel: 'Ver portafolio',
            ctaSecondHref: '/portafolio',
            variant: 'gradient-dark',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
]
