import { defineTemplate } from '@raulbellosom/atlas-web-builder'

const NAVBAR = {
  id: 'navbar',
  type: 'NavbarBlock',
  props: {
    variant: 'light',
    brand: 'Empresa',
    links: 'Inicio | /\nServicios | /servicios\nNosotros | /nosotros\nContacto | /contacto',
    ctaLabel: 'Solicitar demo',
    ctaHref: '/contacto',
    ctaVariant: 'solid',
    sticky: true,
    height: '64',
  },
  children: {},
}

const FOOTER = {
  id: 'footer',
  type: 'FooterBlock',
  props: {
    variant: 'light',
    brand: 'Empresa',
    tagline: 'Tu aliado estratégico para el crecimiento empresarial.',
    columns: 'Servicios | Servicios\nConsultoría | /servicios\nOptimización | /servicios\nCapacitación | /servicios\nTransformación Digital | /servicios\n---\nEmpresa | Empresa\nNosotros | /nosotros\nCasos de éxito | /\nContacto | /contacto\n---\nLegal | Legal\nPolítica de privacidad | /\nTérminos | /',
    copyright: `© ${new Date().getFullYear()} Empresa. Todos los derechos reservados.`,
    showBrand: true,
  },
  children: {},
}

export const negocioTemplate = defineTemplate({
  id: 'atlas-negocio',
  label: 'Negocio & Servicios',
  description: 'Plantilla versátil para empresas de servicios, consultoras, despachos y negocios B2B.',
  category: 'negocio',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'services', 'stats', 'testimonials', 'pricing', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Soluciones que impulsan tu negocio al siguiente nivel',
            subtitle: 'Ofrecemos servicios especializados con metodología probada para ayudar a empresas como la tuya a crecer de forma sostenible y eficiente.',
            eyebrow: 'Más de 10 años de experiencia',
            ctaLabel: 'Comenzar ahora',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Conocer más',
            ctaSecondHref: '/servicios',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '16',
            minHeight: '80vh',
            titleSize: '3xl',
            contentMaxWidth: '70ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Por qué elegirnos',
            title: 'La ventaja de trabajar con nosotros',
            subtitle: 'No somos proveedores, somos aliados estratégicos de tu crecimiento.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Metodología comprobada\nAplicamos procesos validados en más de 200 proyectos para garantizar resultados consistentes y medibles.\n---\nEquipo senior dedicado\nTu cuenta es atendida por profesionales con experiencia real en tu industria, no por juniors.\n---\nComunicación transparente\nReportes semanales, acceso a tablero en tiempo real y comunicación directa con tu equipo asignado.\n---\nSin contratos forzosos\nMes a mes. Creemos tanto en nuestro trabajo que no necesitamos atarte con contratos largos.\n---\nEnfoque en ROI\nCada decisión que tomamos está orientada a generar retorno real y medible sobre tu inversión.\n---\nEscalabilidad inmediata\nCrecemos contigo. Nuestros servicios se adaptan al tamaño y ritmo de tu empresa en cada etapa.',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Nuestros servicios',
            title: 'Soluciones integrales para tu empresa',
            subtitle: 'Cada servicio está diseñado para resolver un problema real y generar valor tangible.',
            columns: '3',
            services: 'Consultoría Estratégica\nAnálisis profundo de tu modelo de negocio con un plan de acción claro, priorizado y con métricas de seguimiento.\n---\nOptimización de Procesos\nIdentificamos cuellos de botella, eliminamos ineficiencias y automatizamos tareas para reducir costos operativos.\n---\nCapacitación Empresarial\nProgramas de formación personalizados para equipos comerciales, directivos y operativos de tu organización.\n---\nTransformación Digital\nAcompañamos tu proceso de digitalización desde la estrategia hasta la implementación de herramientas tecnológicas.\n---\nGestión de Proyectos\nDirigimos proyectos complejos con metodologías ágiles, garantizando entregas en tiempo, forma y presupuesto.\n---\nAuditoria Financiera\nRevisión integral de la salud financiera de tu empresa con recomendaciones para optimizar recursos y rentabilidad.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: 'Nuestros números',
            title: 'Resultados que respaldan nuestra trayectoria',
            stats: '10+ años\nEn el mercado\nAyudando empresas a crecer\n---\n350+\nEmpresas asesoradas\nEn diversos sectores\n---\n$50M+\nEn ahorros generados\nPara nuestros clientes\n---\n97%\nRenovación de contratos\nClientes que continúan',
            background: 'white',
            align: 'center',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Casos de éxito',
            title: 'Empresas que crecieron con nosotros',
            columns: '3',
            background: 'muted',
            testimonials: 'Fernando Lozano|Director General, Grupo Lozano|5\nEn 6 meses logramos reducir nuestros costos operativos en un 28% sin sacrificar calidad. El equipo de consultoría entendió perfectamente nuestra industria y entregó soluciones prácticas.\n---\nMónica Valdez|CFO, Distribuidora Valdez|5\nLa reestructura financiera que implementaron nos permitió acceder a crédito preferencial por primera vez en 15 años. Un trabajo excepcional, metódico y transparente en todo momento.\n---\nGustavo Aranda|CEO, Tech Startup|5\nNos acompañaron desde el MVP hasta la Serie A. Su experiencia en scale-ups fue fundamental para ordenar nuestra operación y escalar sin perder el control.',
          },
          children: {},
        },
        pricing: {
          id: 'pricing',
          type: 'PricingBlock',
          props: {
            eyebrow: 'Planes y precios',
            title: 'Elige el plan que mejor se adapte a tu empresa',
            subtitle: 'Sin sorpresas, sin cargos ocultos. Precio claro desde el primer día.',
            currency: '$',
            period: 'mes',
            plans: 'Starter\nIdeal para pequeñas empresas y emprendedores\n4,500\nConsultoría mensual (4 hrs)\nDiagnóstico inicial incluido\nReporte mensual de avance\nSoporte por email\n---\nProfesional\nPara empresas en crecimiento activo\n12,000\nConsultoría mensual (16 hrs)\nGestión de 1 proyecto activo\nTablero de métricas en tiempo real\nSoporte WhatsApp prioritario\nCapacitación trimestral\n---\nEnterprise\nPara organizaciones con necesidades complejas\nA medida\nConsultoría ilimitada\nEquipo dedicado senior\nProyectos simultáneos ilimitados\nIntegración con tus sistemas\nSLA con tiempos de respuesta garantizados',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Hablamos de tu empresa?',
            subtitle: 'Agenda una sesión de diagnóstico gratuita de 45 minutos. Sin compromiso, solo valor.',
            ctaLabel: 'Agendar sesión gratuita',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Descargar brochure',
            ctaSecondHref: '#',
            variant: 'gradient-primary',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }
  },
})

export const negocioSitePages = [
  {
    id: 'servicios',
    label: 'Servicios',
    routePath: '/servicios',
    required: false,
    description: 'Catálogo de servicios y planes disponibles.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'services', 'pricing', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestros Servicios',
            subtitle: 'Soluciones especializadas con metodología probada para impulsar el crecimiento de tu empresa.',
            eyebrow: 'Qué ofrecemos',
            ctaLabel: 'Agendar sesión',
            ctaHref: '/contacto',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '14',
            minHeight: '45vh',
            titleSize: '2xl',
            contentMaxWidth: '65ch',
          },
          children: {},
        },
        services: {
          id: 'services',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Soluciones disponibles',
            title: 'Servicios diseñados para empresas como la tuya',
            subtitle: 'Cada servicio genera valor tangible y resultados medibles desde el primer mes.',
            columns: '3',
            services: 'Consultoría Estratégica\nAnálisis profundo de tu modelo de negocio con un plan de acción claro, priorizado y con métricas de seguimiento. Desde 4 horas/mes.\n---\nOptimización de Procesos\nIdentificamos cuellos de botella, eliminamos ineficiencias y automatizamos tareas para reducir costos operativos hasta un 30%.\n---\nCapacitación Empresarial\nProgramas de formación personalizados para equipos comerciales, directivos y operativos. Presencial o en línea.\n---\nTransformación Digital\nAcompañamos tu proceso de digitalización desde la estrategia hasta la implementación de herramientas tecnológicas adecuadas.\n---\nGestión de Proyectos\nDirigimos proyectos complejos con metodologías ágiles garantizando entregas en tiempo, forma y dentro del presupuesto.\n---\nAuditoria Financiera\nRevisión integral de la salud financiera con recomendaciones concretas para optimizar recursos y aumentar la rentabilidad.',
            cardStyle: 'card',
            align: 'left',
          },
          children: {},
        },
        pricing: {
          id: 'pricing',
          type: 'PricingBlock',
          props: {
            eyebrow: 'Inversión',
            title: 'Planes claros y sin sorpresas',
            subtitle: 'Elige el plan que mejor se adapta a tu etapa y necesidades actuales.',
            currency: '$',
            period: 'mes',
            plans: 'Starter\nIdeal para pequeñas empresas y emprendedores\n4,500\nConsultoría mensual (4 hrs)\nDiagnóstico inicial incluido\nReporte mensual de avance\nSoporte por email\n---\nProfesional\nPara empresas en crecimiento activo\n12,000\nConsultoría mensual (16 hrs)\nGestión de 1 proyecto activo\nTablero de métricas en tiempo real\nSoporte WhatsApp prioritario\nCapacitación trimestral\n---\nEnterprise\nPara organizaciones con necesidades complejas\nA medida\nConsultoría ilimitada\nEquipo dedicado senior\nProyectos simultáneos ilimitados\nIntegración con tus sistemas\nSLA con tiempos de respuesta garantizados',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Hablamos de tu empresa?',
            subtitle: 'Agenda una sesión de diagnóstico gratuita de 45 minutos. Sin compromiso, solo valor.',
            ctaLabel: 'Agendar sesión gratuita',
            ctaHref: '/contacto',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'nosotros',
    label: 'Nosotros',
    routePath: '/nosotros',
    required: false,
    description: 'Historia, valores y trayectoria de la empresa.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'story', 'stats', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Sobre Nosotros',
            subtitle: 'Conoce la historia, los valores y el equipo detrás de más de 10 años de resultados comprobados.',
            eyebrow: 'Quiénes somos',
            ctaLabel: 'Ver servicios',
            ctaHref: '/servicios',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Agendar sesión',
            ctaSecondHref: '/contacto',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '14',
            minHeight: '50vh',
            titleSize: '2xl',
            contentMaxWidth: '65ch',
          },
          children: {},
        },
        story: {
          id: 'story',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Nuestra historia',
            title: 'Más de una década generando resultados',
            subtitle: 'Nacimos de la convicción de que las empresas merecen aliados estratégicos reales, no proveedores de servicios genéricos.',
            layout: 'grid-2',
            iconStyle: 'check',
            background: 'white',
            features: 'Fundados en 2014\nComenzamos como una firma boutique de consultoría con foco en empresas medianas del sector industrial y servicios.\n---\nCrecimiento sostenido\nDesde 2018 expandimos nuestras capacidades hacia transformación digital y capacitación, atendiendo hoy a más de 350 empresas.\n---\nEquipo multidisciplinar\nContamos con especialistas en finanzas, operaciones, marketing, tecnología y recursos humanos bajo un mismo techo.\n---\nPresencia nacional\nOperamos en 12 ciudades de México con equipos locales que conocen profundamente cada mercado regional.',
          },
          children: {},
        },
        stats: {
          id: 'stats',
          type: 'StatsBlock',
          props: {
            eyebrow: 'En números',
            title: 'Una trayectoria que habla por sí sola',
            stats: '10+ años\nEn el mercado\nAyudando empresas a crecer\n---\n350+\nEmpresas asesoradas\nEn diversos sectores\n---\n$50M+\nEn ahorros generados\nPara nuestros clientes\n---\n97%\nRenovación de contratos\nClientes que continúan',
            background: 'muted',
            align: 'center',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Casos de éxito',
            title: 'Empresas que crecieron con nosotros',
            columns: '3',
            background: 'white',
            testimonials: 'Fernando Lozano|Director General, Grupo Lozano|5\nEn 6 meses logramos reducir nuestros costos operativos en un 28% sin sacrificar calidad. El equipo entendió perfectamente nuestra industria.\n---\nMónica Valdez|CFO, Distribuidora Valdez|5\nLa reestructura financiera nos permitió acceder a crédito preferencial por primera vez en 15 años. Un trabajo excepcional y transparente.\n---\nGustavo Aranda|CEO, Tech Startup|5\nNos acompañaron desde el MVP hasta la Serie A. Su experiencia fue fundamental para ordenar nuestra operación y escalar sin perder el control.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Hablamos de tu empresa?',
            subtitle: 'Sesión de diagnóstico gratuita de 45 minutos. Sin compromiso, solo valor.',
            ctaLabel: 'Agendar sesión',
            ctaHref: '/contacto',
            ctaSecondLabel: 'Ver servicios',
            ctaSecondHref: '/servicios',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'contacto',
    label: 'Contacto',
    routePath: '/contacto',
    required: false,
    description: 'Agenda una sesión o envíanos un mensaje.',
    build: () => ({
      rootIds: ['navbar', 'info', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        info: {
          id: 'info',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Hablemos',
            title: 'Agenda tu sesión de diagnóstico',
            subtitle: 'Respondemos en menos de 24 horas. Sin compromiso, solo una conversación honesta.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Correo electrónico\nhola@empresa.com — para consultas, propuestas y solicitudes de diagnóstico empresarial.\n---\nWhatsApp\n+52 55 0000 0000 — para consultas rápidas y seguimiento de proyectos activos de lunes a viernes.\n---\nLinkedIn\nSíguenos para ver casos de éxito, artículos y las últimas novedades de nuestros servicios.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Diagnóstico gratuito',
            title: '45 minutos que pueden cambiar tu empresa',
            subtitle: 'Sesión de diagnóstico sin costo. Analizamos tu situación y te decimos honestamente si podemos ayudarte.',
            ctaLabel: 'WhatsApp',
            ctaHref: 'https://wa.me/525500000000',
            ctaSecondLabel: 'Enviar correo',
            ctaSecondHref: 'mailto:hola@empresa.com',
            variant: 'gradient-primary',
            size: 'large',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
]
