import { defineTemplate } from '@raulbellosom/atlas-web-builder'

const NAVBAR = {
  id: 'navbar',
  type: 'NavbarBlock',
  props: {
    variant: 'light',
    brand: 'Mi Tienda',
    links: 'Inicio | /\nProductos | /productos\nNosotros | /nosotros\nContacto | /contacto',
    ctaLabel: 'Ver carrito',
    ctaHref: '#carrito',
    ctaVariant: 'outline',
    sticky: true,
    height: '64',
  },
  children: {},
}

const FOOTER = {
  id: 'footer',
  type: 'FooterBlock',
  props: {
    variant: 'dark',
    brand: 'Mi Tienda',
    tagline: 'Calidad, estilo y confianza en cada compra.',
    columns: 'Comprar | Comprar\nTodos los productos | /productos\nNovedades | /productos\nOfertas | /productos\n---\nAyuda | Ayuda\nEnvíos y devoluciones | /\nPreguntas frecuentes | /\nContacto | /contacto\n---\nLegal | Legal\nTérminos y condiciones | /\nPolítica de privacidad | /\nCookies | /',
    copyright: `© ${new Date().getFullYear()} Mi Tienda. Todos los derechos reservados.`,
    showBrand: true,
  },
  children: {},
}

export const tiendaTemplate = defineTemplate({
  id: 'atlas-tienda',
  label: 'Tienda en línea',
  description: 'Plantilla de e-commerce moderna con grilla de productos, banner promocional y reseñas.',
  category: 'ecommerce',
  build() {
    return {
      rootIds: ['navbar', 'hero', 'features', 'products', 'promo', 'categories', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'split',
            title: 'Calidad que se siente diferente',
            subtitle: 'Descubre nuestra colección cuidadosamente seleccionada. Envíos rápidos, devoluciones sin preguntas y garantía de satisfacción.',
            eyebrow: 'Nueva colección 2025',
            ctaLabel: 'Comprar ahora',
            ctaHref: '/productos',
            ctaVariant: 'solid',
            ctaSecondLabel: 'Ver novedades',
            ctaSecondHref: '/productos',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'left',
            paddingY: '16',
            minHeight: '80vh',
            titleSize: '3xl',
            contentMaxWidth: '55ch',
          },
          children: {},
        },
        features: {
          id: 'features',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: '',
            title: '',
            subtitle: '',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Envío gratis desde $500\nEn pedidos superiores a $500 pesos, el envío es completamente gratuito a todo el país.\n---\nDevoluciones sin costo\nSi no estás satisfecho, devuelve tu compra en 30 días sin ningún cargo adicional.\n---\nPago seguro garantizado\nTodas las transacciones están protegidas con encriptación SSL de 256 bits.',
          },
          children: {},
        },
        products: {
          id: 'products',
          type: 'ProductsGridBlock',
          props: {
            categoryId: '',
            limit: 8,
            columns: '4',
            showPrice: true,
            showAddToCart: true,
          },
          children: {},
        },
        promo: {
          id: 'promo',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Oferta especial',
            title: '20% de descuento en tu primera compra',
            subtitle: 'Usa el código BIENVENIDO al finalizar tu compra. Válido por tiempo limitado.',
            ctaLabel: 'Usar descuento',
            ctaHref: '/productos',
            ctaSecondLabel: 'Ver condiciones',
            ctaSecondHref: '#',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        categories: {
          id: 'categories',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Explorar por categoría',
            title: 'Encuentra exactamente lo que buscas',
            subtitle: 'Organizamos nuestro catálogo para que encuentres lo que necesitas en segundos.',
            columns: '4',
            services: 'Nuevos ingresos\nLo último en llegar a nuestra tienda, seleccionado con los más altos estándares de calidad.\n---\nMás vendidos\nLos productos favoritos de nuestros clientes. Los más comprados y mejor valorados.\n---\nOfertas y descuentos\nLas mejores oportunidades de la semana. Precios especiales por tiempo limitado.\n---\nEdición limitada\nColecciones exclusivas disponibles en cantidades muy limitadas.',
            cardStyle: 'bordered',
            align: 'center',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Reseñas verificadas',
            title: 'Miles de clientes felices',
            columns: '3',
            background: 'muted',
            testimonials: 'Diana Flores|Cliente verificada|5\nLa calidad del producto superó mis expectativas. El empaque es hermoso y llegó en perfectas condiciones. Definitivamente volveré a comprar y recomendaré a mis amigas.\n---\nMiguel Herrera|Comprador frecuente|5\nEl servicio al cliente es excelente. Tuve un pequeño problema con mi pedido y lo resolvieron en menos de 24 horas. Profesionalismo total.\n---\nIsabel Navarro|Primera compra|4\nFue mi primera compra en línea aquí y quedé muy satisfecha. El proceso fue sencillo, seguro y el producto llegó antes de lo esperado.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: 'Suscríbete y obtén 10% de descuento',
            subtitle: 'Regístrate en nuestro boletín y sé el primero en enterarte de nuevos productos, ofertas exclusivas y promociones especiales.',
            ctaLabel: 'Suscribirme',
            ctaHref: '#newsletter',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            variant: 'dark',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }
  },
})

export const tiendaSitePages = [
  {
    id: 'productos',
    label: 'Productos',
    routePath: '/productos',
    required: false,
    description: 'Catálogo completo de productos.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'categories', 'products', 'promo', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Todos nuestros productos',
            subtitle: 'Descubre nuestra colección completa, seleccionada con los más altos estándares de calidad.',
            eyebrow: 'Catálogo',
            ctaLabel: '',
            ctaHref: '',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'muted' },
            align: 'center',
            paddingY: '10',
            minHeight: '35vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        categories: {
          id: 'categories',
          type: 'ServicesGridBlock',
          props: {
            eyebrow: 'Categorías',
            title: 'Explora por categoría',
            subtitle: '',
            columns: '4',
            services: 'Nuevos ingresos\nLo último en llegar a nuestra tienda.\n---\nMás vendidos\nLos favoritos de nuestros clientes.\n---\nOfertas\nPrecios especiales por tiempo limitado.\n---\nEdición limitada\nColecciones exclusivas y únicas.',
            cardStyle: 'bordered',
            align: 'center',
          },
          children: {},
        },
        products: {
          id: 'products',
          type: 'ProductsGridBlock',
          props: {
            categoryId: '',
            limit: 12,
            columns: '4',
            showPrice: true,
            showAddToCart: true,
          },
          children: {},
        },
        promo: {
          id: 'promo',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: 'Oferta especial',
            title: '20% de descuento en tu primera compra',
            subtitle: 'Usa el código BIENVENIDO al finalizar tu compra.',
            ctaLabel: 'Usar descuento',
            ctaHref: '#',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'nosotros',
    label: 'Nosotros',
    routePath: '/nosotros',
    required: false,
    description: 'Nuestra historia y compromiso con la calidad.',
    build: () => ({
      rootIds: ['navbar', 'hero', 'story', 'testimonials', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        hero: {
          id: 'hero',
          type: 'HeroBlock',
          props: {
            variant: 'centered',
            title: 'Nuestra Historia',
            subtitle: 'Conoce los valores y el compromiso que hay detrás de cada producto que ofrecemos.',
            eyebrow: 'Sobre Mi Tienda',
            ctaLabel: 'Ver productos',
            ctaHref: '/productos',
            ctaVariant: 'solid',
            ctaSecondLabel: '',
            ctaSecondHref: '',
            imageSrc: '',
            background: { kind: 'color', token: 'bg' },
            align: 'center',
            paddingY: '14',
            minHeight: '50vh',
            titleSize: '2xl',
            contentMaxWidth: '60ch',
          },
          children: {},
        },
        story: {
          id: 'story',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Quiénes somos',
            title: 'Calidad y confianza en cada compra',
            subtitle: 'Somos una tienda en línea fundada con la misión de ofrecer productos de alta calidad a precios justos.',
            layout: 'grid-2',
            iconStyle: 'check',
            background: 'white',
            features: 'Fundados en 2018\nNacimos de la necesidad de llevar productos de calidad directamente a los consumidores, sin intermediarios innecesarios.\n---\nSelección rigurosa\nCada producto que ofrecemos pasa por un proceso estricto de selección y control de calidad antes de llegar a ti.\n---\nEnvíos rápidos\nTrabajamos con los mejores operadores logísticos para garantizar que tu pedido llegue en tiempo y perfectas condiciones.\n---\nAtención personalizada\nNuestro equipo de atención al cliente está disponible para resolver cualquier duda antes, durante y después de tu compra.',
          },
          children: {},
        },
        testimonials: {
          id: 'testimonials',
          type: 'TestimonialsBlock',
          props: {
            eyebrow: 'Lo que dicen nuestros clientes',
            title: 'Miles de clientes felices',
            columns: '3',
            background: 'muted',
            testimonials: 'Diana Flores|Cliente verificada|5\nLa calidad del producto superó mis expectativas. El empaque es hermoso y llegó en perfectas condiciones.\n---\nMiguel Herrera|Comprador frecuente|5\nEl servicio al cliente es excelente. Tuve un pequeño problema con mi pedido y lo resolvieron en menos de 24 horas.\n---\nIsabel Navarro|Primera compra|4\nFue mi primera compra en línea aquí y quedé muy satisfecha. El proceso fue sencillo y el producto llegó antes de lo esperado.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Listo para comprar?',
            subtitle: 'Descubre nuestra colección y encuentra exactamente lo que buscas.',
            ctaLabel: 'Ver productos',
            ctaHref: '/productos',
            ctaSecondLabel: 'Contactarnos',
            ctaSecondHref: '/contacto',
            variant: 'gradient-primary',
            size: 'compact',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
  {
    id: 'contacto',
    label: 'Contacto',
    routePath: '/contacto',
    required: false,
    description: 'Atención al cliente e información de contacto.',
    build: () => ({
      rootIds: ['navbar', 'info', 'cta', 'footer'],
      blocks: {
        navbar: NAVBAR,
        info: {
          id: 'info',
          type: 'FeaturesSectionBlock',
          props: {
            eyebrow: 'Estamos para ayudarte',
            title: 'Atención al cliente',
            subtitle: 'Resolvemos tus dudas sobre pedidos, envíos, devoluciones y más.',
            layout: 'grid-3',
            iconStyle: 'check',
            background: 'white',
            features: 'Correo electrónico\nEscríbenos a hola@mitienda.com. Respondemos en menos de 24 horas hábiles.\n---\nWhatsApp\nChatea con nosotros al +52 55 0000 0000. Atención de lunes a sábado, 9am–7pm.\n---\nDevoluciones\nSi tu compra no cumple tus expectativas, la devuelves en 30 días sin costo. Garantía total.',
          },
          children: {},
        },
        cta: {
          id: 'cta',
          type: 'CtaBannerBlock',
          props: {
            eyebrow: '',
            title: '¿Tienes alguna duda?',
            subtitle: 'Nuestro equipo está listo para ayudarte a encontrar el producto perfecto.',
            ctaLabel: 'WhatsApp',
            ctaHref: 'https://wa.me/525500000000',
            ctaSecondLabel: 'Ver productos',
            ctaSecondHref: '/productos',
            variant: 'dark',
            size: 'normal',
            align: 'center',
          },
          children: {},
        },
        footer: FOOTER,
      },
    }),
  },
]
