#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const argv = new Set(process.argv.slice(2));
const skipComposeUp = argv.has("--skip-compose-up");
const isWindows = process.platform === "win32";
const npxCommand = "npx";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const installerDir = __dirname;
const composeFile = path.resolve(__dirname, "docker-compose.yml");
const localEnvFile = path.resolve(__dirname, ".env.local");
const supabaseWorkdir = path.resolve(__dirname, ".supabase-local");
const supabaseConfig = path.resolve(supabaseWorkdir, "supabase", "config.toml");

const apiImage =
  process.env.ATLAS_API_LOCAL_IMAGE ?? "raulbellosom/atlaserp:api-local-latest";
const workerImage =
  process.env.ATLAS_WORKER_LOCAL_IMAGE ??
  "raulbellosom/atlaserp:worker-local-latest";
const webImage =
  process.env.ATLAS_WEB_LOCAL_IMAGE ?? "raulbellosom/atlaserp:web-local-latest";

function run(command, args, { cwd = installerDir } = {}) {
  const result = spawnSync(command, args, {
    cwd,
    stdio: "inherit",
    shell: isWindows,
  });
  if (result.error) {
    throw new Error(`${command} ${args.join(" ")} failed: ${result.error.message}`);
  }
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed with exit code ${result.status}`);
  }
}

function capture(command, args, { cwd = installerDir } = {}) {
  const result = spawnSync(command, args, {
    cwd,
    stdio: "pipe",
    encoding: "utf8",
    shell: isWindows,
  });
  if (result.error) {
    throw new Error(`${command} ${args.join(" ")} failed: ${result.error.message}`);
  }
  if (result.status !== 0) {
    const stderr = (result.stderr ?? "").trim();
    throw new Error(
      `${command} ${args.join(" ")} failed with exit code ${result.status}${stderr ? `: ${stderr}` : ""}`
    );
  }
  return result.stdout ?? "";
}

async function exists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

function replaceUrlHost(urlValue, targetHost) {
  if (!urlValue) return urlValue;
  try {
    const url = new URL(urlValue);
    if (["127.0.0.1", "localhost", "host.docker.internal"].includes(url.hostname)) {
      url.hostname = targetHost;
      return url.toString().replace(/\/$/, "");
    }
  } catch {
    return urlValue;
  }
  return urlValue;
}

function parseSupabaseStatusEnv(statusOutput) {
  const envMap = new Map();
  const lines = statusOutput.split(/\r?\n/).map((line) => line.trim());
  for (const line of lines) {
    const match = /^([A-Z0-9_]+)="(.*)"$/.exec(line);
    if (match) {
      envMap.set(match[1], match[2]);
    }
  }
  return envMap;
}

async function writeLocalEnv(envMap) {
  const requiredKeys = ["API_URL", "ANON_KEY", "SERVICE_ROLE_KEY", "JWT_SECRET", "DB_URL"];
  const missing = requiredKeys.filter((key) => !envMap.get(key));
  if (missing.length > 0) {
    throw new Error(
      `Could not read required Supabase variables from status output: ${missing.join(", ")}`
    );
  }

  const containerSupabaseUrl = replaceUrlHost(envMap.get("API_URL"), "host.docker.internal");
  const containerDbUrl = replaceUrlHost(envMap.get("DB_URL"), "host.docker.internal");
  const browserSupabaseUrl = replaceUrlHost(envMap.get("API_URL"), "localhost");

  const envContent = `# Auto-generated by infra/installer/setup-local.mjs
# Re-run the script anytime to refresh local Supabase credentials.

NODE_ENV=production
ATLAS_API_PORT=4010
ATLAS_TIME_ZONE=America/Mexico_City
TZ=America/Mexico_City

SUPABASE_URL=${containerSupabaseUrl}
SUPABASE_ANON_KEY=${envMap.get("ANON_KEY")}
SUPABASE_SERVICE_ROLE_KEY=${envMap.get("SERVICE_ROLE_KEY")}
SUPABASE_JWT_SECRET=${envMap.get("JWT_SECRET")}

# Keep Atlas JWT aligned with Supabase local JWT secret.
JWT_SECRET=${envMap.get("JWT_SECRET")}

DATABASE_URL=${containerDbUrl}
DIRECT_URL=${containerDbUrl}

VITE_SUPABASE_URL=${browserSupabaseUrl}
VITE_SUPABASE_ANON_KEY=${envMap.get("ANON_KEY")}
VITE_ATLAS_API_URL=http://localhost:4010
CORS_ORIGIN=http://localhost:5173
`;

  await fs.writeFile(localEnvFile, envContent, "utf8");
}

async function main() {
  console.log("[1/7] Validating dependencies...");
  run("docker", ["compose", "version"]);
  run(npxCommand, ["--version"]);

  if (!(await exists(supabaseWorkdir))) {
    await fs.mkdir(supabaseWorkdir, { recursive: true });
  }

  console.log("[2/7] Initializing Supabase project (if missing)...");
  if (!(await exists(supabaseConfig))) {
    run(npxCommand, ["--yes", "supabase", "init", "--yes", "--workdir", supabaseWorkdir]);
  }

  console.log("[3/7] Starting Supabase local stack...");
  run(npxCommand, [
    "--yes",
    "supabase",
    "start",
    "--workdir",
    supabaseWorkdir,
    "-x",
    "logflare",
    "-x",
    "vector",
  ]);

  console.log("[4/7] Reading Supabase runtime credentials...");
  const statusOutput = capture(npxCommand, [
    "--yes",
    "supabase",
    "status",
    "--workdir",
    supabaseWorkdir,
    "-o",
    "env",
  ]);
  const envMap = parseSupabaseStatusEnv(statusOutput);
  await writeLocalEnv(envMap);
  console.log(`Generated ${localEnvFile}`);

  if (skipComposeUp) {
    console.log("[5/7] Skipping image pull and compose up (--skip-compose-up).");
    return;
  }

  console.log("[5/7] Pulling Atlas local runtime images...");
  run("docker", ["pull", apiImage]);
  run("docker", ["pull", workerImage]);
  run("docker", ["pull", webImage]);

  console.log("[6/7] Running migrations and seed...");
  run("docker", [
    "run",
    "--rm",
    "--add-host",
    "host.docker.internal:host-gateway",
    "--env-file",
    localEnvFile,
    apiImage,
    "pnpm",
    "db:migrate",
  ]);
  run("docker", [
    "run",
    "--rm",
    "--add-host",
    "host.docker.internal:host-gateway",
    "--env-file",
    localEnvFile,
    apiImage,
    "pnpm",
    "db:seed",
  ]);

  console.log("[7/7] Starting Atlas local profile...");
  run("docker", ["compose", "-f", composeFile, "--profile", "local", "up", "-d"]);

  console.log("");
  console.log("Local installation is ready:");
  console.log("- Atlas web: http://localhost:5173");
  console.log("- Atlas API: http://localhost:4010");
  console.log("- Supabase API gateway: http://localhost:54321");
  console.log("- Supabase Studio: http://localhost:54323");
}

main().catch((error) => {
  console.error("");
  console.error("[setup-local] Error:");
  console.error(error.message);
  process.exit(1);
});
