param(
  [switch]$SkipComposeUp
)

$ErrorActionPreference = 'Stop'

function Require-Command {
  param([string]$Name)
  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command not found: $Name"
  }
}

function Replace-UrlHost {
  param(
    [string]$Url,
    [string]$TargetHost
  )
  if (-not $Url) { return $Url }
  try {
    $uri = [System.Uri]$Url
    if ($uri.Host -in @('127.0.0.1', 'localhost', 'host.docker.internal')) {
      $builder = New-Object System.UriBuilder($uri)
      $builder.Host = $TargetHost
      return $builder.Uri.AbsoluteUri.TrimEnd('/')
    }
  } catch {
    # Keep the original value if parsing fails.
  }
  return $Url
}

function Assert-LastExitCode {
  param(
    [string]$Step
  )
  if ($LASTEXITCODE -ne 0) {
    throw "$Step failed with exit code $LASTEXITCODE"
  }
}

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$installerDir = (Resolve-Path (Join-Path $repoRoot 'infra\installer')).Path
$composeFile = Join-Path $installerDir 'docker-compose.yml'
$localEnvFile = Join-Path $installerDir '.env.local'
$supabaseWorkdir = Join-Path $installerDir '.supabase-local'

Write-Host '[1/8] Validating dependencies...'
Require-Command 'docker'
Require-Command 'npx.cmd'
docker compose version | Out-Null

if (-not (Test-Path $supabaseWorkdir)) {
  New-Item -ItemType Directory -Path $supabaseWorkdir | Out-Null
}

Write-Host '[2/8] Initializing Supabase project (if missing)...'
$configFile = Join-Path $supabaseWorkdir 'supabase\config.toml'
if (-not (Test-Path $configFile)) {
  npx.cmd --yes supabase init --yes --workdir $supabaseWorkdir | Out-Host
}

Write-Host '[3/8] Starting Supabase local stack...'
npx.cmd --yes supabase start --workdir $supabaseWorkdir -x logflare -x vector | Out-Host
Assert-LastExitCode 'supabase start'

Write-Host '[4/8] Reading Supabase runtime credentials...'
$statusLines = npx.cmd --yes supabase status --workdir $supabaseWorkdir -o env
Assert-LastExitCode 'supabase status'

$envMap = @{}
foreach ($line in $statusLines) {
  if ($line -match '^([A-Z0-9_]+)="(.*)"$') {
    $envMap[$matches[1]] = $matches[2]
  }
}

$requiredKeys = @('API_URL', 'ANON_KEY', 'SERVICE_ROLE_KEY', 'JWT_SECRET', 'DB_URL')
$missing = @($requiredKeys | Where-Object { -not $envMap.ContainsKey($_) -or [string]::IsNullOrWhiteSpace($envMap[$_]) })
if ($missing.Count -gt 0) {
  throw "Could not read required Supabase variables from status output: $($missing -join ', ')"
}

$containerSupabaseUrl = Replace-UrlHost -Url $envMap['API_URL'] -TargetHost 'host.docker.internal'
$containerDbUrl = Replace-UrlHost -Url $envMap['DB_URL'] -TargetHost 'host.docker.internal'
$browserSupabaseUrl = Replace-UrlHost -Url $envMap['API_URL'] -TargetHost 'localhost'

$envContent = @"
# Auto-generated by infra/installer/setup-local.ps1
# Re-run the script anytime to refresh local Supabase credentials.

NODE_ENV=production
ATLAS_API_PORT=4010
ATLAS_TIME_ZONE=America/Mexico_City
TZ=America/Mexico_City

SUPABASE_URL=$containerSupabaseUrl
SUPABASE_ANON_KEY=$($envMap['ANON_KEY'])
SUPABASE_SERVICE_ROLE_KEY=$($envMap['SERVICE_ROLE_KEY'])
SUPABASE_JWT_SECRET=$($envMap['JWT_SECRET'])

# Keep Atlas JWT aligned with Supabase local JWT secret.
JWT_SECRET=$($envMap['JWT_SECRET'])

DATABASE_URL=$containerDbUrl
DIRECT_URL=$containerDbUrl

VITE_SUPABASE_URL=$browserSupabaseUrl
VITE_SUPABASE_ANON_KEY=$($envMap['ANON_KEY'])
VITE_ATLAS_API_URL=http://localhost:4010
CORS_ORIGIN=http://localhost:5173
"@

$envContent | Set-Content -Path $localEnvFile -Encoding UTF8
Write-Host "Generated $localEnvFile"

if ($SkipComposeUp) {
  Write-Host '[5/8] Skipping Atlas image build and compose up (SkipComposeUp was set).'
  exit 0
}

Write-Host '[5/8] Building local Atlas images (api, worker, web)...'
$apiLocalImage = if ($env:ATLAS_API_LOCAL_IMAGE) { $env:ATLAS_API_LOCAL_IMAGE } else { 'atlaserp-api-local:dev' }
$workerLocalImage = if ($env:ATLAS_WORKER_LOCAL_IMAGE) { $env:ATLAS_WORKER_LOCAL_IMAGE } else { 'atlaserp-worker-local:dev' }
$webLocalImage = if ($env:ATLAS_WEB_LOCAL_IMAGE) { $env:ATLAS_WEB_LOCAL_IMAGE } else { 'atlaserp-web-local:dev' }

docker build `
  -f (Join-Path $repoRoot 'infra/docker/api.Dockerfile') `
  -t $apiLocalImage `
  $repoRoot
Assert-LastExitCode 'docker build api image'

docker build `
  -f (Join-Path $repoRoot 'infra/docker/worker.Dockerfile') `
  -t $workerLocalImage `
  $repoRoot
Assert-LastExitCode 'docker build worker image'

docker build `
  -f (Join-Path $repoRoot 'infra/docker/web.Dockerfile') `
  --build-arg VITE_ATLAS_API_URL=http://localhost:4010 `
  --build-arg VITE_SUPABASE_URL=$browserSupabaseUrl `
  --build-arg VITE_SUPABASE_ANON_KEY=$($envMap['ANON_KEY']) `
  -t $webLocalImage `
  $repoRoot
Assert-LastExitCode 'docker build web image'

Write-Host '[6/8] Running database migrations for local API image...'
docker run --rm `
  --add-host host.docker.internal:host-gateway `
  --env-file $localEnvFile `
  $apiLocalImage `
  pnpm db:migrate
Assert-LastExitCode 'pnpm db:migrate in api image'

Write-Host '[7/8] Running database seed for local API image...'
docker run --rm `
  --add-host host.docker.internal:host-gateway `
  --env-file $localEnvFile `
  $apiLocalImage `
  pnpm db:seed
Assert-LastExitCode 'pnpm db:seed in api image'

Write-Host '[8/8] Starting Atlas local profile...'
docker compose -f $composeFile --profile local up -d
Assert-LastExitCode 'docker compose up local profile'

Write-Host ''
Write-Host 'Local installation is ready:'
Write-Host '- Atlas web: http://localhost:5173'
Write-Host '- Atlas API: http://localhost:4010'
Write-Host '- Supabase API gateway: http://localhost:54321'
Write-Host '- Supabase Studio: http://localhost:54323'
