import { defineView } from "@atlas/module-engine";

export default defineView({
  key: "fleet.reports.maintenance.form",
  kind: "FORM",
  version: "0.2.0",
  schema: {
    entity: "report",
    component: "AtlasForm",
    apiPath: "/fleet/reports/maintenance",
    formMode: "page",
    title: "Nuevo Reporte de Mantenimiento",
    submitLabel: "Finalizar reporte",
    cancelLabel: "Cancelar",
    sections: [
      {
        id: "vehicle",
        label: "Vehiculo",
        description: "Selecciona el vehiculo al que se aplico el mantenimiento.",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [
          {
            field: "vehicle_id",
            label: "Seleccionar vehiculo",
            type: "relation",
            required: true,
            relation: {
              apiPath: "/fleet/vehicles",
              labelField: ["plate", "vehicle_model_name"],
              labelSeparator: " · ",
              clearable: false,
              disabledField: "enabled",
              searchParam: "search",
              displayFields: {
                badge: "economic_number",
                title: "vehicle_model_name",
                subtitle: ["plate", "vehicle_type_name", "vehicle_brand_name"],
              },
            },
          },
        ],
      },
      {
        id: "service_data",
        label: "Datos del Mantenimiento",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "title", label: "Titulo del servicio", type: "text", required: true },
          {
            field: "maintenance_subtype",
            label: "Tipo de mantenimiento",
            type: "select",
            required: true,
            options: [
              { label: "Preventivo", value: "preventive" },
              { label: "Correctivo", value: "corrective" },
              { label: "Inspeccion", value: "inspection" },
              { label: "Alineacion", value: "alignment" },
              { label: "Cambio de aceite", value: "oil_change" },
              { label: "Llantas", value: "tire_service" },
              { label: "Otro", value: "other" },
            ],
          },
          { field: "report_date", label: "Fecha del servicio", type: "date", required: true },
          { field: "odometer_km", label: "Kilometraje", type: "number" },
        ],
      },
      {
        id: "workshop",
        label: "Informacion del Taller",
        description: "Datos del proveedor que realizo el trabajo.",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "workshop_name", label: "Nombre del taller", type: "text" },
          { field: "workshop_phone", label: "Telefono", type: "phone" },
          { field: "workshop_address", label: "Direccion", type: "text" },
          { field: "invoice_number", label: "No. de factura/ticket", type: "text" },
        ],
      },
      {
        id: "parts",
        type: "parts-editor",
        label: "Refacciones / Partes",
        description: "Agrega piezas, cantidades y costo unitario.",
        collapsible: true,
        defaultCollapsed: false,
      },
      {
        id: "costs",
        label: "Resumen de Costos",
        collapsible: true,
        defaultCollapsed: false,
        columns: 3,
        fields: [
          { field: "labor_cost", label: "Mano de obra", type: "decimal" },
          { field: "parts_cost", label: "Costo de refacciones (calculado automaticamente)", type: "decimal", readonly: true },
          { field: "total_cost", label: "Costo final total (mano de obra + partes)", type: "decimal", readonly: true },
        ],
      },
      {
        id: "notes",
        label: "Observaciones",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [{ field: "notes", label: "Descripcion / notas", type: "textarea" }],
      },
      {
        id: "next_service",
        label: "Proximo Servicio",
        description: "Debes indicar fecha o kilometraje sugerido para el siguiente mantenimiento.",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "next_service_date", label: "Fecha sugerida", type: "date" },
          { field: "next_service_odometer", label: "Kilometraje sugerido", type: "number" },
        ],
      },
      {
        id: "attachments",
        type: "attachments",
        label: "Archivos Adjuntos",
        collapsible: true,
        defaultCollapsed: false,
        attachments: {
          createMode: "stage-until-parent-create",
          editMode: "upload-immediately",
          listPath: "/fleet/reports/:id/documents",
          addPath: "/fleet/reports/:id/documents",
          removePath: "/fleet/reports/:id/documents/:docId",
          upload: {
            endpoint: "/files/upload",
            moduleKey: "custom.fleet",
            entityType: "FleetReport",
          },
          signedUrl: {
            endpointTemplate: "/files/:fileId/signed-url",
          },
          fields: {
            id: "id",
            fileAssetId: "file_asset_id",
            documentType: "document_type",
            label: "label",
            createdAt: "created_at",
            enabled: "enabled",
            fileAsset: "file_asset",
            fileName: "originalName",
            mimeType: "mimeType",
            sizeBytes: "sizeBytes",
          },
          permissions: {
            read: "fleet.reports.read",
            create: "fleet.reports.update",
            remove: "fleet.reports.update",
            fileUpload: "files.assets.create",
            fileRead: "files.assets.read",
          },
          limits: {
            maxFiles: 20,
            maxSizeMB: 10,
            allowMultiple: true,
          },
        },
      },
    ],
  },
});
