import { defineView } from "@atlas/module-engine";

export default defineView({
  key: "fleet.reports.other.form",
  kind: "FORM",
  version: "0.2.1",
  schema: {
    entity: "report",
    component: "AtlasForm",
    apiPath: "/fleet/reports/other",
    formMode: "page",
    title: "Nuevo Reporte - Otro",
    submitLabel: "Finalizar reporte",
    cancelLabel: "Cancelar",
    sections: [
      {
        id: "vehicle",
        label: "Vehiculo",
        icon: "Wrench",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [
          {
            field: "vehicle_id",
            label: "Seleccionar vehiculo",
            type: "relation",
            required: true,
            relation: {
              apiPath: "/fleet/vehicles",
              labelField: ["plate", "vehicle_model_name"],
              labelSeparator: " · ",
              clearable: false,
              disabledField: "enabled",
              searchParam: "search",
              displayFields: {
                badge: "full_economic_number",
                title: "vehicle_model_name",
                subtitle: ["plate", "vehicle_type_name", "vehicle_brand_name"],
              },
            },
          },
        ],
      },
      {
        id: "other_data",
        label: "Datos del Reporte",
        icon: "ClipboardList",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "title", label: "Titulo del reporte", type: "text", required: true },
          {
            field: "other_category_label",
            label: "Categoria personalizada",
            type: "text",
            required: true,
          },
          { field: "report_date", label: "Fecha del reporte", type: "date", required: true },
          { field: "odometer_km", label: "Kilometraje", type: "number" },
        ],
      },
      {
        id: "workshop",
        label: "Informacion del Taller",
        icon: "Building2",
        collapsible: true,
        defaultCollapsed: false,
        columns: 2,
        fields: [
          { field: "workshop_name", label: "Nombre del taller", type: "text" },
          { field: "workshop_phone", label: "Telefono", type: "phone" },
          { field: "workshop_address", label: "Direccion", type: "text" },
          { field: "invoice_number", label: "No. de factura / ticket", type: "text" },
        ],
      },
      {
        id: "parts",
        type: "parts-editor",
        label: "Refacciones / Partes",
        icon: "Package",
        collapsible: true,
        defaultCollapsed: false,
      },
      {
        id: "costs",
        label: "Resumen de Costos",
        icon: "BadgeDollarSign",
        collapsible: true,
        defaultCollapsed: false,
        columns: 3,
        fields: [
          { field: "labor_cost", label: "Mano de obra", type: "decimal" },
          { field: "parts_cost", label: "Costo de refacciones (calculado automaticamente)", type: "decimal", readonly: true },
          { field: "total_cost", label: "Costo final total (mano de obra + partes)", type: "decimal", readonly: true },
        ],
      },
      {
        id: "notes",
        label: "Observaciones",
        icon: "FileText",
        collapsible: true,
        defaultCollapsed: false,
        columns: 1,
        fields: [{ field: "notes", label: "Descripcion / notas", type: "textarea" }],
      },
      {
        id: "attachments",
        type: "attachments",
        label: "Archivos Adjuntos",
        icon: "Paperclip",
        collapsible: true,
        defaultCollapsed: false,
        attachments: {
          createMode: "stage-until-parent-create",
          editMode: "upload-immediately",
          listPath: "/fleet/reports/:id/documents",
          addPath: "/fleet/reports/:id/documents",
          removePath: "/fleet/reports/:id/documents/:docId",
          upload: {
            endpoint: "/files/upload",
            moduleKey: "custom.fleet",
            entityType: "FleetReport",
          },
          signedUrl: {
            endpointTemplate: "/files/:fileId/signed-url",
          },
          fields: {
            id: "id",
            fileAssetId: "file_asset_id",
            documentType: "document_type",
            label: "label",
            createdAt: "created_at",
            enabled: "enabled",
            fileAsset: "file_asset",
            fileName: "originalName",
            mimeType: "mimeType",
            sizeBytes: "sizeBytes",
          },
          permissions: {
            read: "fleet.reports.read",
            create: "fleet.reports.update",
            remove: "fleet.reports.update",
            fileUpload: "files.assets.create",
            fileRead: "files.assets.read",
          },
          limits: {
            maxFiles: 20,
            maxSizeMB: 10,
            allowMultiple: true,
          },
        },
      },
    ],
  },
});
