import { defineView } from '@atlas/module-engine'

export default defineView({
  key: 'fleet.vehicle.form',
  kind: 'FORM',
  version: '0.2.0',
  schema: {
    entity: 'vehicle',
    component: 'AtlasForm',
    apiPath: '/fleet/vehicles',
    sections: [
      {
        label: 'Identificacion del vehiculo',
        icon: 'Truck',
        fields: [
          {
            field: 'plate',
            label: 'Matricula',
            type: 'text',
            required: true,
            hint: 'Placa oficial de circulacion (ej. ABC-1234)',
          },
          {
            field: 'vehicle_model_id',
            label: 'Modelo de vehiculo',
            type: 'relation',
            required: true,
            hint: 'Selecciona la marca, modelo y año del vehiculo',
            relation: {
              apiPath: '/fleet/catalogs/vehicle-models',
              labelField: ['brand_name', 'name', 'year'],
              labelSeparator: ' · ',
              pageSize: 200,
              clearable: true,
              disabledField: 'enabled',
              displayFields: {
                badge: 'economic_group_number',
                title: 'name',
                subtitle: ['brand_name', 'type_name', 'year'],
              },
              create: {
                enabled: true,
                label: 'Crear modelo de vehiculo',
                mode: 'modal',
                title: 'Crear modelo de vehiculo',
                apiPath: '/fleet/catalogs/vehicle-models',
                viewKey: 'fleet.catalog.vehicle_models.form',
                selectCreated: true,
                refreshOptions: true,
                permissionKey: 'fleet.catalogs.create',
              },
            },
          },
          {
            field: 'color',
            label: 'Color del vehiculo',
            type: 'color',
            hint: 'Color exterior principal del vehiculo',
          },
          {
            field: 'status',
            label: 'Estado operativo',
            type: 'select',
            required: true,
            hint: 'Estado actual del vehiculo dentro de la flota',
            options: ['active', 'maintenance', 'inactive', 'retired'],
          },
          {
            field: 'economic_individual_number',
            label: 'No. Economico individual',
            type: 'text',
            hint: 'Numero de unidad asignado internamente (ej. 042)',
          },
        ],
      },
      {
        label: 'Asignacion de conductor',
        icon: 'UserCheck',
        fields: [
          {
            field: 'driver_id',
            label: 'Conductor asignado',
            type: 'relation',
            hint: 'Conductor principal responsable de esta unidad',
            relation: {
              apiPath: '/fleet/drivers',
              labelField: ['first_name', 'last_name'],
              labelSeparator: ' ',
              clearable: true,
              disabledField: 'enabled',
            },
          },
        ],
      },
      {
        label: 'Notas',
        icon: 'FileText',
        fields: [
          {
            field: 'notes',
            label: 'Observaciones adicionales',
            type: 'textarea',
            hint: 'Informacion relevante sobre el vehiculo: condiciones especiales, historial, etc.',
          },
        ],
      },
      {
        id: 'attachments',
        type: 'attachments',
        label: 'Documentos del vehiculo',
        placement: 'aside',
        attachments: {
          createMode: 'stage-until-parent-create',
          editMode: 'upload-immediately',
          listPath: '/fleet/vehicles/:id/documents',
          addPath: '/fleet/vehicles/:id/documents',
          removePath: '/fleet/vehicles/:id/documents/:docId',
          upload: {
            endpoint: '/files/upload',
            moduleKey: 'custom.fleet',
            entityType: 'FleetVehicle',
          },
          signedUrl: {
            endpointTemplate: '/files/:fileId/signed-url',
          },
          fields: {
            id: 'id',
            fileAssetId: 'file_asset_id',
            documentType: 'document_type',
            label: 'label',
            createdAt: 'created_at',
            enabled: 'enabled',
            fileAsset: 'file_asset',
            fileName: 'originalName',
            mimeType: 'mimeType',
            sizeBytes: 'sizeBytes',
          },
          permissions: {
            read: 'fleet.vehicles.read',
            create: 'fleet.vehicles.update',
            remove: 'fleet.vehicles.update',
            fileUpload: 'files.assets.create',
            fileRead: 'files.assets.read',
          },
          limits: {
            maxFiles: 20,
            maxSizeMB: 10,
            allowMultiple: true,
          },
        },
      },
    ],
    submitLabel: 'Guardar vehiculo',
    cancelLabel: 'Cancelar',
  },
})
